# Sensitivity to cell-type label granularity and to the number of empty barcodes (PBMC 8k)

CellSweep fits one expression profile per input label, so the granularity of the labels sets what it treats as shared
cell-type signal. This notebook reruns CellSweep on the 8,381 PBMC 8k cells with labelings from a single label up to
Leiden resolution 20 (190 clusters), the CellTypist Immune_All_High (used elsewhere in the paper) and Immune_All_Low
annotations, and a shuffled-label control; with 10 to all 728,899 non-cellular barcodes; and on simulated data with
known noise. All runs use the raw matrix and empty-droplet calls of the default PBMC 8k CellSweep run
(`benchmarking.ipynb`). The last section draws the paper's Fig. S19.

In [1]:
import os
import numpy as np
import pandas as pd
import scipy.sparse as sp
import anndata as ad
import scanpy as sc
import matplotlib
import matplotlib.pyplot as plt
from matplotlib.legend_handler import HandlerTuple
from scipy.stats import spearmanr
from sklearn.neighbors import NearestNeighbors

import cellsweep.utils as cs_utils
from cellsweep import denoise_count_matrix

cellsweep_dir = os.path.dirname(os.path.abspath(""))
threads = 16
overwrite = False   # rerun labelings and CellSweep runs that already exist

## 1. Labelings (PBMC 8k)

`all_one` (one label), `lineage` (lymphoid/myeloid), `ct_high` (CellTypist Immune_All_High, the default), `ct_low`
(Immune_All_Low), Leiden at resolutions 0.001 to 20 with the same scanpy pipeline as `benchmarking.ipynb`, and
`shuffled` (`ct_high` permuted across cells). Written to `labels.csv` once.

In [2]:
dataset_name = "pbmc8k"
data_dir = os.path.join(cellsweep_dir, "notebooks", "data", dataset_name)
run_dir = os.path.join(data_dir, "celltype_granularity")
os.makedirs(run_dir, exist_ok=True)
default_cellsweep_path = os.path.join(data_dir, "pbmc8k_output_cellsweep.h5ad")
labels_csv = os.path.join(run_dir, "labels.csv")
min_genes = 0
min_cells = 0
max_mt_percentage = None
n_top_genes = 2000
n_pcs = 25
n_neighbors = 20
expected_cells = 8381
cellsweep_max_iter = 2000
cellsweep_init_alpha = 0.7
cellsweep_init_beta = 0.01
existing_leiden_resolutions = [0.1, 0.5, 1.0, 1.5, 2.0, 5.0]
new_leiden_resolutions = [0.001, 0.005, 0.01, 10.0, 20.0]  # 0.001 -> K=1, 0.005 -> K=2, 0.01 -> K=3
LINEAGE = {
    "T cells": "Lymphoid", "ILC": "Lymphoid", "B cells": "Lymphoid",
    "Monocytes": "Myeloid", "DC": "Myeloid", "pDC": "Myeloid", "HSC/MPP": "Myeloid",
}
def res_tag(r):
    return str(float(r)).replace(".", "_")
def load_raw():
    """Raw counts + empty-droplet calls + CellTypist-High labels, from the default run."""
    adata = ad.read_h5ad(default_cellsweep_path)
    adata.X = adata.layers["raw"].copy()
    del adata.layers["raw"]
    adata.obs = adata.obs[["is_empty", "celltype"]].copy()
    for key in list(adata.uns.keys()):
        del adata.uns[key]
    adata.var = adata.var[["gene_ids", "empty_counts"]].copy()
    adata.var_names_make_unique()
    return adata
def make_labels(overwrite=False):
    if os.path.exists(labels_csv) and not overwrite:
        return pd.read_csv(labels_csv, index_col=0, dtype=str)

    adata = load_raw()
    cells = adata[~adata.obs["is_empty"]].copy()
    labels = pd.DataFrame(index=cells.obs_names)

    labels["ct_high"] = cells.obs["celltype"].astype(str)
    labels["all_one"] = "cell"
    labels["lineage"] = labels["ct_high"].map(LINEAGE)
    assert labels["lineage"].notna().all(), labels.loc[labels["lineage"].isna(), "ct_high"].unique()

    rng = np.random.default_rng(0)
    labels["shuffled"] = rng.permutation(labels["ct_high"].values)

    # CellTypist Immune_All_Low (same call the notebook uses for High)
    ct = cs_utils.determine_cell_types(adata, model_pkl="Immune_All_Low.pkl", filter_empty=True, expected_cells=expected_cells, verbose=1)
    labels["ct_low"] = ct.obs["celltype"].astype(str).reindex(labels.index)

    # Leiden labels already used for the notebook sweep
    for r in existing_leiden_resolutions:
        path = os.path.join(data_dir, f"adata_cellsweep_leiden_{res_tag(r)}.h5ad")
        obs = ad.read_h5ad(path, backed="r").obs
        labels[f"leiden_{r:g}"] = obs["celltype"].astype(str).reindex(labels.index)

    # finer Leiden resolutions, same pipeline as the notebook
    for r in new_leiden_resolutions:
        tmp = cs_utils.run_scanpy_preprocessing_and_clustering(cells, min_genes=min_genes, min_cells=min_cells, max_mt_percentage=max_mt_percentage, n_top_genes=n_top_genes, n_pcs=n_pcs, n_neighbors=n_neighbors, leiden_resolution=r, seed=42, verbose=1)
        labels[f"leiden_{r:g}"] = tmp.obs["leiden"].astype(str).reindex(labels.index)

    labels = labels[[c for c in labels.columns if not c.startswith("leiden")] + sorted([c for c in labels.columns if c.startswith("leiden")], key=lambda c: float(c.split("_")[1]))]
    assert not labels.isna().any().any(), labels.isna().sum()
    labels.to_csv(labels_csv)
    return labels
def run_one(condition, threads, overwrite=False):
    out = os.path.join(run_dir, f"adata_cellsweep_{condition}.h5ad")
    if os.path.exists(out) and not overwrite:
        return condition, "exists"
    labels = pd.read_csv(labels_csv, index_col=0, dtype=str)
    adata = load_raw()
    adata.obs["celltype"] = pd.Categorical(labels[condition].reindex(adata.obs_names).fillna("Empty Droplet"))
    cs_utils_log = os.path.join(run_dir, f"cellsweep_{condition}.log")
    from cellsweep import denoise_count_matrix
    denoise_count_matrix(adata, adata_out=out, init_alpha=cellsweep_init_alpha, init_beta=cellsweep_init_beta, freeze_ambient_profile=True, max_iter=cellsweep_max_iter, empty_droplet_method="threshold", expected_cells=expected_cells, threads=threads, verbose=1, log_file=cs_utils_log)
    return condition, "done"

if not overwrite:   # the labels and CellSweep runs of sections 1-3, downloaded from Box instead of recomputed
    from box_data import download_from_box
    download_from_box("data/pbmc8k/celltype_granularity/", "data/pbmc8k/empty_barcode_sweep/")

labels = make_labels(overwrite=overwrite)
labels.nunique()

ct_high           7
all_one           1
lineage           2
shuffled          7
ct_low           18
leiden_0.001      2
leiden_0.005      3
leiden_0.01       3
leiden_0.1        6
leiden_0.5       14
leiden_1         19
leiden_1.5       23
leiden_2         25
leiden_5         48
leiden_10        95
leiden_20       202
dtype: int64

## 2. CellSweep on each labeling

In [3]:
for condition in labels.columns:
    print(condition, run_one(condition, threads, overwrite=overwrite)[1], flush=True)

ct_high exists

all_one exists

lineage exists

shuffled exists

ct_low exists

leiden_0.001 exists

leiden_0.005 exists

leiden_0.01 exists

leiden_0.1 exists

leiden_0.5 exists

leiden_1 exists

leiden_1.5 exists

leiden_2 exists

leiden_5 exists

leiden_10 exists

leiden_20 exists

## 3. Number of empty barcodes

Same cells and `ct_high` labels; the non-cellular barcodes are subsampled (seed 42) to 10 to 500,000, or all are used.

In [4]:
empty_run_dir = os.path.join(data_dir, "empty_barcode_sweep")
os.makedirs(empty_run_dir, exist_ok=True)
EMPTY_BARCODE_NUMBERS = [10, 100, 1_000, 10_000, 50_000, 100_000, 500_000, None]  # None = all of them
SEED = 42
def empty_run_one(n_empty, threads, overwrite=False):
    tag = "all" if n_empty is None else str(n_empty)
    out = os.path.join(empty_run_dir, f"adata_cellsweep_empty_{tag}.h5ad")
    if os.path.exists(out) and not overwrite:
        return tag, "exists"
    from cellsweep import denoise_count_matrix
    labels = pd.read_csv(labels_csv, index_col=0, dtype=str)
    adata = load_raw()
    adata.obs["celltype"] = pd.Categorical(labels["ct_high"].reindex(adata.obs_names).fillna("Empty Droplet"))
    if n_empty is not None:
        empty = adata.obs_names[adata.obs["is_empty"].values]
        rng = np.random.default_rng(SEED)
        keep = set(rng.choice(empty, size=n_empty, replace=False))
        adata = adata[~adata.obs["is_empty"].values | adata.obs_names.isin(keep)].copy()
    denoise_count_matrix(adata, adata_out=out, init_alpha=cellsweep_init_alpha, init_beta=cellsweep_init_beta, freeze_ambient_profile=True, max_iter=cellsweep_max_iter, empty_droplet_method="threshold", expected_cells=expected_cells, threads=threads, verbose=1, log_file=os.path.join(empty_run_dir, f"cellsweep_empty_{tag}.log"))
    return tag, "done"

for n_empty in EMPTY_BARCODE_NUMBERS:
    print(n_empty, empty_run_one(n_empty, threads, overwrite=overwrite)[1], flush=True)

10 exists

100 exists

1000 exists

10000 exists

50000 exists

100000 exists

500000 exists

None exists

## 4. Simulation with ground truth

`simulation1_small_noise` (12 true cell types, known real and noise counts per entry): true types pooled into K groups,
the true labels, random splits of each type, Leiden labels, and shuffled true labels.

In [5]:
sim_dataset_name = "simulation1_small_noise"
sim_data_dir = os.path.join(cellsweep_dir, "notebooks", "data", sim_dataset_name)
sim_out_dir = os.path.join(cellsweep_dir, "notebooks", "output", sim_dataset_name)
sim_run_dir = os.path.join(sim_data_dir, "celltype_granularity")
os.makedirs(sim_run_dir, exist_ok=True)
os.makedirs(sim_out_dir, exist_ok=True)
sim_raw_path = os.path.join(sim_data_dir, "adata_raw.h5ad")
sim_labels_csv = os.path.join(sim_run_dir, "labels.csv")
sim_metrics_csv = os.path.join(sim_out_dir, "celltype_granularity_simulation_metrics.csv")
sim_expected_cells = 10000
sim_cellsweep_max_iter = 2000
def sim_make_labels(overwrite=False):
    if os.path.exists(sim_labels_csv) and not overwrite:
        return pd.read_csv(sim_labels_csv, index_col=0, dtype=str)
    adata = ad.read_h5ad(sim_raw_path)
    cells = adata[~adata.obs["is_empty"]].copy()
    truth = cells.obs["celltype"].astype(str)
    type_idx = truth.str.replace("Type_", "").astype(int).values
    rng = np.random.default_rng(0)

    labels = pd.DataFrame(index=cells.obs_names)
    # pool true types into K groups with a fixed random assignment
    perm = rng.permutation(12)
    for K in [1, 2, 3, 6]:
        group_of_type = {t: int(np.where(perm == t)[0][0]) % K for t in range(12)}
        labels[f"merge_{K}"] = [f"G{group_of_type[t]}" for t in type_idx]
    labels["truth"] = truth.values
    for m in [2, 4, 8]:
        labels[f"split_{m}"] = [f"{t}_{s}" for t, s in zip(truth.values, rng.integers(0, m, size=len(truth)))]
    for r in [1.0, 5.0, 20.0]:
        tmp = cs_utils.run_scanpy_preprocessing_and_clustering(cells, min_genes=0, min_cells=0, max_mt_percentage=None, n_top_genes=2000, n_pcs=25, n_neighbors=20, leiden_resolution=r, seed=42, verbose=0)
        labels[f"leiden_{r:g}"] = tmp.obs["leiden"].astype(str).reindex(labels.index)
    labels["shuffled"] = rng.permutation(truth.values)
    assert not labels.isna().any().any()
    labels.to_csv(sim_labels_csv)
    return labels
def sim_run_one(condition, threads, overwrite=False):
    out = os.path.join(sim_run_dir, f"adata_cellsweep_{condition}.h5ad")
    if os.path.exists(out) and not overwrite:
        return condition, "exists"
    from cellsweep import denoise_count_matrix
    labels = pd.read_csv(sim_labels_csv, index_col=0, dtype=str)
    adata = ad.read_h5ad(sim_raw_path)
    adata.obs["celltype"] = pd.Categorical(labels[condition].reindex(adata.obs_names).fillna("Empty Droplet"))
    denoise_count_matrix(adata, adata_out=out, init_alpha=0.7, init_beta=0.01, freeze_ambient_profile=True, max_iter=sim_cellsweep_max_iter, empty_droplet_method="threshold", expected_cells=sim_expected_cells, threads=threads, verbose=1, log_file=os.path.join(sim_run_dir, f"cellsweep_{condition}.log"))
    return condition, "done"
def sim_score(condition, labels):
    a = ad.read_h5ad(os.path.join(sim_run_dir, f"adata_cellsweep_{condition}.h5ad"))
    a = a[~a.obs["is_empty"]].copy()
    raw = sp.csr_matrix(a.layers["raw"]).astype(np.float64)
    den = sp.csr_matrix(a.X).astype(np.float64)
    real = sp.csr_matrix(a.layers["real"]).astype(np.float64)
    noise = sp.csr_matrix(a.layers["noise"]).astype(np.float64)
    removed = raw - den
    removed.data = np.clip(removed.data, 0, None)

    correctly_removed = removed.minimum(noise).sum()
    real_retained = den.minimum(real).sum()

    # per-entry error on entries that are nonzero in raw
    err = (den - real)
    # per-cell contamination fraction
    raw_tot = np.asarray(raw.sum(1)).ravel()
    est_frac = np.asarray(removed.sum(1)).ravel() / raw_tot
    true_frac = np.asarray(noise.sum(1)).ravel() / raw_tot

    # off-target markers: markers of type t counted in cells whose TRUE type is not t
    marker_sets = a.uns["marker_sets"]
    truth = labels["truth"].reindex(a.obs_names).values
    off_raw = off_rem = on_raw = on_ret = 0.0
    raw_c, den_c = raw.tocsc(), den.tocsc()
    for t, genes in enumerate(marker_sets):
        genes = np.asarray(genes).astype(int)
        on_mask = truth == f"Type_{t}"
        r = raw_c[:, genes]
        d = den_c[:, genes]
        off_raw += r[~on_mask].sum()
        off_rem += (r[~on_mask] - d[~on_mask]).sum()
        on_raw += r[on_mask].sum()
        on_ret += d[on_mask].sum()

    return dict(
        condition=condition,
        n_labels=labels[condition].nunique(),
        noise_recall=correctly_removed / noise.sum(),
        removal_precision=correctly_removed / removed.sum(),
        real_retained=real_retained / real.sum(),
        fraction_removed=removed.sum() / raw.sum(),
        true_fraction_noise=noise.sum() / raw.sum(),
        entry_rmse=np.sqrt(err.multiply(err).sum() / raw.nnz),
        cell_frac_spearman=spearmanr(est_frac, true_frac).correlation,
        cell_frac_mae=np.mean(np.abs(est_frac - true_frac)),
        offtarget_marker_removed=off_rem / off_raw,
        ontarget_marker_retained=on_ret / on_raw,
        mean_cell_size_per_label=len(labels) / labels[condition].nunique(),
    )

sim_labels = sim_make_labels(overwrite=overwrite)
for condition in sim_labels.columns:
    print(condition, sim_run_one(condition, threads, overwrite=overwrite)[1], flush=True)
sim_metrics = pd.DataFrame([sim_score(c, sim_labels) for c in sim_labels.columns])
sim_metrics.to_csv(sim_metrics_csv, index=False)
sim_metrics.round(4)

22:45:12 - INFO - Starting cellsweep denoising at 2026-10-03 22:45:12, cellsweep version 0.1.3

22:45:12 - INFO - Inferring celltype profiles.

22:45:12 - INFO - Number of celltypes: 1

22:45:12 - INFO - Inferring the ambient profile from empty droplets.

Logging to /home/mcaskey/cellsweep/notebooks/data/simulation1_small_noise/celltype_granularity/cellsweep_merge_1.log

22:45:12 - INFO - adata.obs does not have 'init_alpha'. Setting to `init_alpha` argument.

22:45:12 - INFO - Performing Sparse EM with 32 Numba thread(s)

22:45:17 - INFO - EM Iter   1: ll=-1999.4587 log_delta_p=inf log_delta_a=inf min_alpha=0.6940 mean_alpha=0.7022 median_alpha=0.7025 max_alpha=0.7142 beta=0.0101

22:45:21 - INFO - EM Iter   2: ll=-2005.9005 log_delta_p=inf log_delta_a=inf min_alpha=0.6806 mean_alpha=0.7003 median_alpha=0.7012 max_alpha=0.7343 beta=0.0104

22:45:21 - INFO - EM Iter   3: ll=-2005.8237 log_delta_p=-4.2979 log_delta_a=-10.3735 min_alpha=0.6636 mean_alpha=0.6983 median_alpha=0.7002 max_alpha=0.7620 beta=0.0107

22:45:21 - INFO - EM Iter   4: ll=-2005.7050 log_delta_p=-4.2787 log_delta_a=-11.5365 min_alpha=0.6429 mean_alpha=0.6962 median_alpha=0.6995 max_alpha=0.7963 beta=0.0110

22:45:21 - INFO - EM Iter   5: ll=-2005.5037 log_delta_p=-4.1429 log_delta_a=-11.5737 min_alpha=0.6179 mean_alpha=0.6940 median_alpha=0.6994 max_alpha=0.8360 beta=0.0113

22:45:21 - INFO - EM Iter   6: ll=-2005.1616 log_delta_p=-3.9432 log_delta_a=-11.6074 min_alpha=0.5836 mean_alpha=0.6915 median_alpha=0.7002 max_alpha=0.8780 beta=0.0116

22:45:21 - INFO - EM Iter   7: ll=-2004.6006 log_delta_p=-3.7178 log_delta_a=-11.5734 min_alpha=0.5354 mean_alpha=0.6886 median_alpha=0.7021 max_alpha=0.9000 beta=0.0119

22:45:21 - INFO - EM Iter   8: ll=-2003.7426 log_delta_p=-3.4934 log_delta_a=-11.5955 min_alpha=0.4757 mean_alpha=0.6848 median_alpha=0.7058 max_alpha=0.9000 beta=0.0121

22:45:21 - INFO - EM Iter   9: ll=-2002.5680 log_delta_p=-3.3013 log_delta_a=-11.6192 min_alpha=0.4067 mean_alpha=0.6791 median_alpha=0.7122 max_alpha=0.9000 beta=0.0124

22:45:21 - INFO - EM Iter  10: ll=-2001.1101 log_delta_p=-3.0934 log_delta_a=-11.6494 min_alpha=0.3333 mean_alpha=0.6736 median_alpha=0.7220 max_alpha=0.9000 beta=0.0126

22:45:21 - INFO - EM Iter  11: ll=-1999.1986 log_delta_p=-3.0183 log_delta_a=-11.7571 min_alpha=0.2627 mean_alpha=0.6692 median_alpha=0.7370 max_alpha=0.9000 beta=0.0127

22:45:21 - INFO - EM Iter  12: ll=-1996.6918 log_delta_p=-3.0236 log_delta_a=-11.9067 min_alpha=0.2005 mean_alpha=0.6650 median_alpha=0.7570 max_alpha=0.9000 beta=0.0128

22:45:21 - INFO - EM Iter  13: ll=-1993.7483 log_delta_p=-3.0451 log_delta_a=-12.2040 min_alpha=0.1498 mean_alpha=0.6552 median_alpha=0.7831 max_alpha=0.9000 beta=0.0129

22:45:21 - INFO - EM Iter  14: ll=-1991.2163 log_delta_p=-3.1223 log_delta_a=-12.2828 min_alpha=0.1111 mean_alpha=0.6412 median_alpha=0.8171 max_alpha=0.9000 beta=0.0128

22:45:21 - INFO - EM Iter  15: ll=-1989.3898 log_delta_p=-2.8777 log_delta_a=-12.6629 min_alpha=0.0836 mean_alpha=0.6298 median_alpha=0.8538 max_alpha=0.9000 beta=0.0128

22:45:21 - INFO - EM Iter  16: ll=-1987.8760 log_delta_p=-3.7885 log_delta_a=-12.6188 min_alpha=0.0640 mean_alpha=0.6191 median_alpha=0.8889 max_alpha=0.9000 beta=0.0128

22:45:21 - INFO - EM Iter  17: ll=-1986.5010 log_delta_p=-3.9922 log_delta_a=-12.7654 min_alpha=0.0499 mean_alpha=0.6091 median_alpha=0.9000 max_alpha=0.9000 beta=0.0128

22:45:21 - INFO - EM Iter  18: ll=-1985.3501 log_delta_p=-4.3265 log_delta_a=-12.6012 min_alpha=0.0399 mean_alpha=0.5987 median_alpha=0.9000 max_alpha=0.9000 beta=0.0127

22:45:21 - INFO - EM Iter  19: ll=-1984.5702 log_delta_p=-4.5417 log_delta_a=-12.5351 min_alpha=0.0326 mean_alpha=0.5892 median_alpha=0.9000 max_alpha=0.9000 beta=0.0127

22:45:21 - INFO - EM Iter  20: ll=-1984.0966 log_delta_p=-5.1626 log_delta_a=-12.5769 min_alpha=0.0265 mean_alpha=0.5815 median_alpha=0.9000 max_alpha=0.9000 beta=0.0127

22:45:21 - INFO - EM Iter  21: ll=-1983.7310 log_delta_p=-4.8445 log_delta_a=-12.6988 min_alpha=0.0214 mean_alpha=0.5750 median_alpha=0.9000 max_alpha=0.9000 beta=0.0127

22:45:22 - INFO - EM Iter  22: ll=-1983.4475 log_delta_p=-4.9790 log_delta_a=-12.8348 min_alpha=0.0173 mean_alpha=0.5697 median_alpha=0.9000 max_alpha=0.9000 beta=0.0128

22:45:22 - INFO - EM Iter  23: ll=-1983.2288 log_delta_p=-5.2028 log_delta_a=-12.7822 min_alpha=0.0141 mean_alpha=0.5654 median_alpha=0.9000 max_alpha=0.9000 beta=0.0129

22:45:22 - INFO - EM Iter  24: ll=-1983.0603 log_delta_p=-5.4309 log_delta_a=-12.5780 min_alpha=0.0117 mean_alpha=0.5618 median_alpha=0.9000 max_alpha=0.9000 beta=0.0130

22:45:22 - INFO - EM Iter  25: ll=-1982.9304 log_delta_p=-5.6563 log_delta_a=-12.3773 min_alpha=0.0099 mean_alpha=0.5589 median_alpha=0.9000 max_alpha=0.9000 beta=0.0131

22:45:22 - INFO - EM Iter  26: ll=-1982.8314 log_delta_p=-5.8792 log_delta_a=-12.3362 min_alpha=0.0084 mean_alpha=0.5566 median_alpha=0.9000 max_alpha=0.9000 beta=0.0133

22:45:22 - INFO - EM Iter  27: ll=-1982.7571 log_delta_p=-6.1047 log_delta_a=-12.1261 min_alpha=0.0072 mean_alpha=0.5546 median_alpha=0.9000 max_alpha=0.9000 beta=0.0135

22:45:22 - INFO - EM Iter  28: ll=-1982.7003 log_delta_p=-6.3307 log_delta_a=-12.2157 min_alpha=0.0063 mean_alpha=0.5530 median_alpha=0.9000 max_alpha=0.9000 beta=0.0137

22:45:22 - INFO - EM Iter  29: ll=-1982.6570 log_delta_p=-6.5549 log_delta_a=-11.8821 min_alpha=0.0055 mean_alpha=0.5517 median_alpha=0.9000 max_alpha=0.9000 beta=0.0140

22:45:22 - INFO - EM Iter  30: ll=-1982.6235 log_delta_p=-6.7776 log_delta_a=-11.8338 min_alpha=0.0048 mean_alpha=0.5506 median_alpha=0.9000 max_alpha=0.9000 beta=0.0142

22:45:22 - INFO - EM Iter  31: ll=-1982.5968 log_delta_p=-6.9990 log_delta_a=-11.6744 min_alpha=0.0043 mean_alpha=0.5497 median_alpha=0.9000 max_alpha=0.9000 beta=0.0146

22:45:22 - INFO - EM Iter  32: ll=-1982.5755 log_delta_p=-7.2193 log_delta_a=-11.5880 min_alpha=0.0038 mean_alpha=0.5489 median_alpha=0.9000 max_alpha=0.9000 beta=0.0149

22:45:22 - INFO - EM Iter  33: ll=-1982.5582 log_delta_p=-7.4390 log_delta_a=-11.5272 min_alpha=0.0033 mean_alpha=0.5483 median_alpha=0.9000 max_alpha=0.9000 beta=0.0153

22:45:22 - INFO - EM Iter  34: ll=-1982.5434 log_delta_p=-7.6587 log_delta_a=-11.4695 min_alpha=0.0027 mean_alpha=0.5477 median_alpha=0.9000 max_alpha=0.9000 beta=0.0157

22:45:22 - INFO - EM Iter  35: ll=-1982.5309 log_delta_p=-7.8791 log_delta_a=-11.4198 min_alpha=0.0023 mean_alpha=0.5472 median_alpha=0.9000 max_alpha=0.9000 beta=0.0161

22:45:22 - INFO - EM Iter  36: ll=-1982.5195 log_delta_p=-8.1016 log_delta_a=-11.3264 min_alpha=0.0019 mean_alpha=0.5468 median_alpha=0.9000 max_alpha=0.9000 beta=0.0165

22:45:22 - INFO - EM Iter  37: ll=-1982.5098 log_delta_p=-8.3275 log_delta_a=-11.3027 min_alpha=0.0016 mean_alpha=0.5464 median_alpha=0.9000 max_alpha=0.9000 beta=0.0170

22:45:22 - INFO - EM Iter  38: ll=-1982.5003 log_delta_p=-8.5588 log_delta_a=-11.2655 min_alpha=0.0013 mean_alpha=0.5461 median_alpha=0.9000 max_alpha=0.9000 beta=0.0175

22:45:22 - INFO - EM Iter  39: ll=-1982.4915 log_delta_p=-8.7986 log_delta_a=-11.2182 min_alpha=0.0011 mean_alpha=0.5458 median_alpha=0.9000 max_alpha=0.9000 beta=0.0179

22:45:22 - INFO - EM Iter  40: ll=-1982.4830 log_delta_p=-9.0510 log_delta_a=-11.1658 min_alpha=0.0009 mean_alpha=0.5455 median_alpha=0.9000 max_alpha=0.9000 beta=0.0184

22:45:22 - INFO - EM Iter  41: ll=-1982.4749 log_delta_p=-9.3215 log_delta_a=-11.1639 min_alpha=0.0007 mean_alpha=0.5452 median_alpha=0.9000 max_alpha=0.9000 beta=0.0190

22:45:22 - INFO - EM Iter  42: ll=-1982.4670 log_delta_p=-9.6183 log_delta_a=-11.0965 min_alpha=0.0006 mean_alpha=0.5449 median_alpha=0.9000 max_alpha=0.9000 beta=0.0195

22:45:22 - INFO - EM Iter  43: ll=-1982.4595 log_delta_p=-9.9402 log_delta_a=-11.0882 min_alpha=0.0005 mean_alpha=0.5447 median_alpha=0.9000 max_alpha=0.9000 beta=0.0201

22:45:22 - INFO - EM Iter  44: ll=-1982.4518 log_delta_p=-10.3005 log_delta_a=-11.0597 min_alpha=0.0004 mean_alpha=0.5445 median_alpha=0.9000 max_alpha=0.9000 beta=0.0206

22:45:22 - INFO - EM Iter  45: ll=-1982.4440 log_delta_p=-10.7089 log_delta_a=-11.0492 min_alpha=0.0003 mean_alpha=0.5443 median_alpha=0.9000 max_alpha=0.9000 beta=0.0212

22:45:22 - INFO - EM Iter  46: ll=-1982.4365 log_delta_p=-11.0232 log_delta_a=-11.0214 min_alpha=0.0003 mean_alpha=0.5440 median_alpha=0.9000 max_alpha=0.9000 beta=0.0218

22:45:22 - INFO - EM Iter  47: ll=-1982.4291 log_delta_p=-11.0360 log_delta_a=-11.0023 min_alpha=0.0002 mean_alpha=0.5438 median_alpha=0.9000 max_alpha=0.9000 beta=0.0224

22:45:22 - INFO - EM Iter  48: ll=-1982.4219 log_delta_p=-10.8710 log_delta_a=-10.9657 min_alpha=0.0002 mean_alpha=0.5436 median_alpha=0.9000 max_alpha=0.9000 beta=0.0230

22:45:22 - INFO - EM Iter  49: ll=-1982.4144 log_delta_p=-10.6825 log_delta_a=-10.9798 min_alpha=0.0002 mean_alpha=0.5434 median_alpha=0.9000 max_alpha=0.9000 beta=0.0236

22:45:22 - INFO - EM Iter  50: ll=-1982.4069 log_delta_p=-10.4318 log_delta_a=-10.9163 min_alpha=0.0001 mean_alpha=0.5432 median_alpha=0.9000 max_alpha=0.9000 beta=0.0242

22:45:22 - INFO - EM Iter  51: ll=-1982.3994 log_delta_p=-10.2475 log_delta_a=-10.9541 min_alpha=0.0001 mean_alpha=0.5431 median_alpha=0.9000 max_alpha=0.9000 beta=0.0248

22:45:22 - INFO - EM Iter  52: ll=-1982.3918 log_delta_p=-10.1068 log_delta_a=-10.8975 min_alpha=0.0001 mean_alpha=0.5429 median_alpha=0.9000 max_alpha=0.9000 beta=0.0254

22:45:22 - INFO - EM Iter  53: ll=-1982.3850 log_delta_p=-9.9936 log_delta_a=-10.9005 min_alpha=0.0001 mean_alpha=0.5427 median_alpha=0.9000 max_alpha=0.9000 beta=0.0261

22:45:22 - INFO - EM Iter  54: ll=-1982.3774 log_delta_p=-9.9004 log_delta_a=-10.8899 min_alpha=0.0001 mean_alpha=0.5425 median_alpha=0.9000 max_alpha=0.9000 beta=0.0267

22:45:22 - INFO - EM Iter  55: ll=-1982.3702 log_delta_p=-9.8230 log_delta_a=-10.8762 min_alpha=0.0000 mean_alpha=0.5423 median_alpha=0.9000 max_alpha=0.9000 beta=0.0274

22:45:22 - INFO - EM Iter  56: ll=-1982.3627 log_delta_p=-9.7581 log_delta_a=-10.8557 min_alpha=0.0000 mean_alpha=0.5421 median_alpha=0.9000 max_alpha=0.9000 beta=0.0280

22:45:22 - INFO - EM Iter  57: ll=-1982.3558 log_delta_p=-9.7018 log_delta_a=-10.8461 min_alpha=0.0000 mean_alpha=0.5419 median_alpha=0.9000 max_alpha=0.9000 beta=0.0287

22:45:22 - INFO - EM Iter  58: ll=-1982.3486 log_delta_p=-9.6529 log_delta_a=-10.8656 min_alpha=0.0000 mean_alpha=0.5418 median_alpha=0.9000 max_alpha=0.9000 beta=0.0294

22:45:22 - INFO - EM Iter  59: ll=-1982.3413 log_delta_p=-9.6092 log_delta_a=-10.8628 min_alpha=0.0000 mean_alpha=0.5416 median_alpha=0.9000 max_alpha=0.9000 beta=0.0300

22:45:22 - INFO - EM Iter  60: ll=-1982.3346 log_delta_p=-9.5703 log_delta_a=-10.8537 min_alpha=0.0000 mean_alpha=0.5414 median_alpha=0.9000 max_alpha=0.9000 beta=0.0307

22:45:22 - INFO - EM Iter  61: ll=-1982.3274 log_delta_p=-9.5325 log_delta_a=-10.8479 min_alpha=0.0000 mean_alpha=0.5412 median_alpha=0.9000 max_alpha=0.9000 beta=0.0314

22:45:22 - INFO - EM Iter  62: ll=-1982.3203 log_delta_p=-9.5000 log_delta_a=-10.8343 min_alpha=0.0000 mean_alpha=0.5411 median_alpha=0.9000 max_alpha=0.9000 beta=0.0321

22:45:22 - INFO - EM Iter  63: ll=-1982.3138 log_delta_p=-9.4687 log_delta_a=-10.8000 min_alpha=0.0000 mean_alpha=0.5409 median_alpha=0.9000 max_alpha=0.9000 beta=0.0327

22:45:22 - INFO - EM Iter  64: ll=-1982.3070 log_delta_p=-9.4412 log_delta_a=-10.8225 min_alpha=0.0000 mean_alpha=0.5407 median_alpha=0.9000 max_alpha=0.9000 beta=0.0334

22:45:22 - INFO - EM Iter  65: ll=-1982.3002 log_delta_p=-9.4151 log_delta_a=-10.8058 min_alpha=0.0000 mean_alpha=0.5406 median_alpha=0.9000 max_alpha=0.9000 beta=0.0341

22:45:22 - INFO - EM Iter  66: ll=-1982.2936 log_delta_p=-9.3912 log_delta_a=-10.7925 min_alpha=0.0000 mean_alpha=0.5404 median_alpha=0.9000 max_alpha=0.9000 beta=0.0348

22:45:23 - INFO - EM Iter  67: ll=-1982.2872 log_delta_p=-9.3683 log_delta_a=-10.8123 min_alpha=0.0000 mean_alpha=0.5402 median_alpha=0.9000 max_alpha=0.9000 beta=0.0354

22:45:23 - INFO - EM Iter  68: ll=-1982.2808 log_delta_p=-9.3486 log_delta_a=-10.8002 min_alpha=0.0000 mean_alpha=0.5607 median_alpha=0.9302 max_alpha=0.9511 beta=0.0361

22:45:23 - INFO - EM Iter  69: ll=-1972.9107 log_delta_p=-9.3288 log_delta_a=-10.8019 min_alpha=0.0000 mean_alpha=0.5738 median_alpha=0.9512 max_alpha=0.9761 beta=0.0356

22:45:23 - INFO - EM Iter  70: ll=-1971.7864 log_delta_p=-3.2280 log_delta_a=-9.4352 min_alpha=0.0000 mean_alpha=0.5818 median_alpha=0.9650 max_alpha=0.9879 beta=0.0349

22:45:23 - INFO - EM Iter  71: ll=-1971.1534 log_delta_p=-4.5152 log_delta_a=-11.1002 min_alpha=0.0000 mean_alpha=0.5871 median_alpha=0.9750 max_alpha=0.9940 beta=0.0342

22:45:23 - INFO - EM Iter  72: ll=-1970.7283 log_delta_p=-4.7355 log_delta_a=-10.8669 min_alpha=0.0000 mean_alpha=0.5908 median_alpha=0.9822 max_alpha=0.9970 beta=0.0336

22:45:23 - INFO - EM Iter  73: ll=-1970.4446 log_delta_p=-5.1157 log_delta_a=-10.8861 min_alpha=0.0000 mean_alpha=0.5933 median_alpha=0.9874 max_alpha=0.9985 beta=0.0329

22:45:23 - INFO - EM Iter  74: ll=-1970.2555 log_delta_p=-5.5161 log_delta_a=-10.9327 min_alpha=0.0000 mean_alpha=0.5949 median_alpha=0.9911 max_alpha=0.9993 beta=0.0324

22:45:23 - INFO - EM Iter  75: ll=-1970.1294 log_delta_p=-5.9278 log_delta_a=-10.9722 min_alpha=0.0000 mean_alpha=0.5960 median_alpha=0.9938 max_alpha=0.9996 beta=0.0318

22:45:23 - INFO - EM Iter  76: ll=-1970.0451 log_delta_p=-6.3489 log_delta_a=-11.0351 min_alpha=0.0000 mean_alpha=0.5968 median_alpha=0.9956 max_alpha=0.9998 beta=0.0313

22:45:23 - INFO - EM Iter  77: ll=-1969.9891 log_delta_p=-6.7796 log_delta_a=-11.1012 min_alpha=0.0000 mean_alpha=0.5974 median_alpha=0.9969 max_alpha=0.9999 beta=0.0308

22:45:23 - INFO - EM Iter  78: ll=-1969.9510 log_delta_p=-7.2222 log_delta_a=-11.1710 min_alpha=0.0000 mean_alpha=0.5977 median_alpha=0.9978 max_alpha=1.0000 beta=0.0303

22:45:23 - INFO - EM Iter  79: ll=-1969.9253 log_delta_p=-7.6811 log_delta_a=-11.2529 min_alpha=0.0000 mean_alpha=0.5980 median_alpha=0.9985 max_alpha=1.0000 beta=0.0299

22:45:23 - INFO - EM Iter  80: ll=-1969.9082 log_delta_p=-8.1651 log_delta_a=-11.2524 min_alpha=0.0000 mean_alpha=0.5982 median_alpha=0.9989 max_alpha=1.0000 beta=0.0295

22:45:23 - INFO - EM Iter  81: ll=-1969.8958 log_delta_p=-8.6899 log_delta_a=-11.3169 min_alpha=0.0000 mean_alpha=0.5984 median_alpha=0.9992 max_alpha=1.0000 beta=0.0291

22:45:23 - INFO - EM Iter  82: ll=-1969.8877 log_delta_p=-9.2883 log_delta_a=-11.3803 min_alpha=0.0000 mean_alpha=0.5985 median_alpha=0.9995 max_alpha=1.0000 beta=0.0287

22:45:23 - INFO - EM Iter  83: ll=-1969.8816 log_delta_p=-10.0446 log_delta_a=-11.4237 min_alpha=0.0000 mean_alpha=0.5986 median_alpha=0.9996 max_alpha=1.0000 beta=0.0284

22:45:23 - INFO - EM Iter  84: ll=-1969.8773 log_delta_p=-11.3145 log_delta_a=-11.5306 min_alpha=0.0000 mean_alpha=0.5987 median_alpha=0.9997 max_alpha=1.0000 beta=0.0280

22:45:23 - INFO - EM Iter  85: ll=-1969.8742 log_delta_p=-11.4955 log_delta_a=-11.5052 min_alpha=0.0000 mean_alpha=0.5988 median_alpha=0.9998 max_alpha=1.0000 beta=0.0277

22:45:23 - INFO - EM Iter  86: ll=-1969.8720 log_delta_p=-10.7385 log_delta_a=-11.5725 min_alpha=0.0000 mean_alpha=0.5988 median_alpha=0.9999 max_alpha=1.0000 beta=0.0274

22:45:23 - INFO - EM Iter  87: ll=-1969.8704 log_delta_p=-10.4710 log_delta_a=-11.6144 min_alpha=0.0000 mean_alpha=0.5989 median_alpha=0.9999 max_alpha=1.0000 beta=0.0271

22:45:23 - INFO - EM Iter  88: ll=-1969.8693 log_delta_p=-10.3606 log_delta_a=-11.6067 min_alpha=0.0000 mean_alpha=0.5990 median_alpha=0.9999 max_alpha=1.0000 beta=0.0269

22:45:23 - INFO - EM Iter  89: ll=-1969.8683 log_delta_p=-10.3226 log_delta_a=-11.6549 min_alpha=0.0000 mean_alpha=0.5990 median_alpha=1.0000 max_alpha=1.0000 beta=0.0266

22:45:23 - INFO - EM Iter  90: ll=-1969.8672 log_delta_p=-10.3269 log_delta_a=-11.7264 min_alpha=0.0000 mean_alpha=0.5991 median_alpha=1.0000 max_alpha=1.0000 beta=0.0264

22:45:23 - INFO - EM Iter  91: ll=-1969.8666 log_delta_p=-10.3579 log_delta_a=-11.7473 min_alpha=0.0000 mean_alpha=0.5992 median_alpha=1.0000 max_alpha=1.0000 beta=0.0261

22:45:23 - INFO - EM Iter  92: ll=-1969.8659 log_delta_p=-10.4043 log_delta_a=-11.8248 min_alpha=0.0000 mean_alpha=0.5992 median_alpha=1.0000 max_alpha=1.0000 beta=0.0259

22:45:23 - INFO - EM Iter  93: ll=-1969.8656 log_delta_p=-10.4619 log_delta_a=-11.9181 min_alpha=0.0000 mean_alpha=0.5993 median_alpha=1.0000 max_alpha=1.0000 beta=0.0257

22:45:23 - INFO - EM Iter  94: ll=-1969.8651 log_delta_p=-10.5299 log_delta_a=-11.7895 min_alpha=0.0000 mean_alpha=0.5994 median_alpha=1.0000 max_alpha=1.0000 beta=0.0254

22:45:23 - INFO - EM Iter  95: ll=-1969.8648 log_delta_p=-10.5996 log_delta_a=-11.9328 min_alpha=0.0000 mean_alpha=0.5994 median_alpha=1.0000 max_alpha=1.0000 beta=0.0252

22:45:23 - INFO - EM Iter  96: ll=-1969.8643 log_delta_p=-10.6757 log_delta_a=-11.8901 min_alpha=0.0000 mean_alpha=0.5995 median_alpha=1.0000 max_alpha=1.0000 beta=0.0250

22:45:23 - INFO - EM Iter  97: ll=-1969.8640 log_delta_p=-10.7540 log_delta_a=-11.8790 min_alpha=0.0000 mean_alpha=0.5995 median_alpha=1.0000 max_alpha=1.0000 beta=0.0248

22:45:23 - INFO - EM Iter  98: ll=-1969.8638 log_delta_p=-10.8305 log_delta_a=-11.9017 min_alpha=0.0000 mean_alpha=0.5996 median_alpha=1.0000 max_alpha=1.0000 beta=0.0247

22:45:23 - INFO - EM Iter  99: ll=-1969.8635 log_delta_p=-10.9133 log_delta_a=-11.9573 min_alpha=0.0000 mean_alpha=0.5997 median_alpha=1.0000 max_alpha=1.0000 beta=0.0245

22:45:23 - INFO - EM Iter 100: ll=-1969.8634 log_delta_p=-10.9925 log_delta_a=-12.0488 min_alpha=0.0000 mean_alpha=0.5997 median_alpha=1.0000 max_alpha=1.0000 beta=0.0243

22:45:23 - INFO - EM Iter 101: ll=-1969.8632 log_delta_p=-11.0759 log_delta_a=-12.2048 min_alpha=0.0000 mean_alpha=0.5998 median_alpha=1.0000 max_alpha=1.0000 beta=0.0241

22:45:23 - INFO - EM Iter 102: ll=-1969.8630 log_delta_p=-11.1556 log_delta_a=-12.0978 min_alpha=0.0000 mean_alpha=0.5998 median_alpha=1.0000 max_alpha=1.0000 beta=0.0240

22:45:23 - INFO - EM Iter 103: ll=-1969.8629 log_delta_p=-11.2358 log_delta_a=-12.0335 min_alpha=0.0000 mean_alpha=0.5999 median_alpha=1.0000 max_alpha=1.0000 beta=0.0238

22:45:23 - INFO - EM Iter 104: ll=-1969.8622 log_delta_p=-11.3186 log_delta_a=-12.0744 min_alpha=0.0000 mean_alpha=0.5999 median_alpha=1.0000 max_alpha=1.0000 beta=0.0237

22:45:23 - INFO - EM Iter 105: ll=-1969.8622 log_delta_p=-11.4012 log_delta_a=-12.0791 min_alpha=0.0000 mean_alpha=0.6000 median_alpha=1.0000 max_alpha=1.0000 beta=0.0235

22:45:23 - INFO - EM Iter 106: ll=-1969.8619 log_delta_p=-11.4804 log_delta_a=-12.1388 min_alpha=0.0000 mean_alpha=0.6000 median_alpha=1.0000 max_alpha=1.0000 beta=0.0234

22:45:23 - INFO - EM Iter 107: ll=-1969.8619 log_delta_p=-11.5635 log_delta_a=-12.2139 min_alpha=0.0000 mean_alpha=0.6001 median_alpha=1.0000 max_alpha=1.0000 beta=0.0232

22:45:23 - INFO - EM Iter 108: ll=-1969.8618 log_delta_p=-11.6397 log_delta_a=-12.1178 min_alpha=0.0000 mean_alpha=0.6001 median_alpha=1.0000 max_alpha=1.0000 beta=0.0231

22:45:23 - INFO - EM Iter 109: ll=-1969.8618 log_delta_p=-11.7211 log_delta_a=-12.1325 min_alpha=0.0000 mean_alpha=0.6002 median_alpha=1.0000 max_alpha=1.0000 beta=0.0229

22:45:23 - INFO - Converged.

22:45:24 - INFO - Saving inferred adata to '/home/mcaskey/cellsweep/notebooks/data/simulation1_small_noise/celltype_granularity/adata_cellsweep_merge_1.h5ad'

merge_1 done

22:45:24 - INFO - Starting cellsweep denoising at 2026-10-03 22:45:24, cellsweep version 0.1.3

22:45:24 - INFO - Inferring celltype profiles.

22:45:25 - INFO - Number of celltypes: 2

22:45:25 - INFO - Inferring the ambient profile from empty droplets.

Logging to /home/mcaskey/cellsweep/notebooks/data/simulation1_small_noise/celltype_granularity/cellsweep_merge_2.log

22:45:25 - INFO - adata.obs does not have 'init_alpha'. Setting to `init_alpha` argument.

22:45:25 - INFO - Performing Sparse EM with 32 Numba thread(s)

22:45:25 - INFO - EM Iter   1: ll=-1979.7154 log_delta_p=inf log_delta_a=inf min_alpha=0.5980 mean_alpha=0.6498 median_alpha=0.6585 max_alpha=0.6815 beta=0.0095

22:45:25 - INFO - EM Iter   2: ll=-1979.2293 log_delta_p=inf log_delta_a=inf min_alpha=0.4791 mean_alpha=0.5953 median_alpha=0.6070 max_alpha=0.6709 beta=0.0092

22:45:25 - INFO - EM Iter   3: ll=-1975.6782 log_delta_p=-2.3801 log_delta_a=-11.0612 min_alpha=0.3806 mean_alpha=0.5484 median_alpha=0.5587 max_alpha=0.6713 beta=0.0089

22:45:25 - INFO - EM Iter   4: ll=-1973.4102 log_delta_p=-3.4872 log_delta_a=-11.5719 min_alpha=0.3015 mean_alpha=0.5064 median_alpha=0.5147 max_alpha=0.6789 beta=0.0087

22:45:25 - INFO - EM Iter   5: ll=-1971.4506 log_delta_p=-3.0548 log_delta_a=-11.7325 min_alpha=0.2366 mean_alpha=0.4666 median_alpha=0.4727 max_alpha=0.6909 beta=0.0084

22:45:25 - INFO - EM Iter   6: ll=-1969.5909 log_delta_p=-2.9530 log_delta_a=-11.7244 min_alpha=0.1835 mean_alpha=0.4282 median_alpha=0.4312 max_alpha=0.7064 beta=0.0081

22:45:25 - INFO - EM Iter   7: ll=-1967.8238 log_delta_p=-3.0736 log_delta_a=-11.7019 min_alpha=0.1412 mean_alpha=0.3914 median_alpha=0.3908 max_alpha=0.7256 beta=0.0078

22:45:25 - INFO - EM Iter   8: ll=-1966.1773 log_delta_p=-3.2702 log_delta_a=-11.5378 min_alpha=0.1079 mean_alpha=0.3566 median_alpha=0.3516 max_alpha=0.7489 beta=0.0074

22:45:25 - INFO - EM Iter   9: ll=-1964.6742 log_delta_p=-3.4967 log_delta_a=-11.5349 min_alpha=0.0826 mean_alpha=0.3242 median_alpha=0.3143 max_alpha=0.7768 beta=0.0071

22:45:25 - INFO - EM Iter  10: ll=-1963.3266 log_delta_p=-3.7351 log_delta_a=-11.4822 min_alpha=0.0638 mean_alpha=0.2945 median_alpha=0.2791 max_alpha=0.8091 beta=0.0067

22:45:25 - INFO - EM Iter  11: ll=-1962.1352 log_delta_p=-3.9265 log_delta_a=-11.4675 min_alpha=0.0500 mean_alpha=0.2677 median_alpha=0.2472 max_alpha=0.8443 beta=0.0064

22:45:25 - INFO - EM Iter  12: ll=-1961.0930 log_delta_p=-4.0762 log_delta_a=-11.4573 min_alpha=0.0400 mean_alpha=0.2436 median_alpha=0.2181 max_alpha=0.8800 beta=0.0061

22:45:25 - INFO - EM Iter  13: ll=-1960.1891 log_delta_p=-4.2321 log_delta_a=-11.5296 min_alpha=0.0328 mean_alpha=0.2223 median_alpha=0.1926 max_alpha=0.9000 beta=0.0058

22:45:25 - INFO - EM Iter  14: ll=-1959.4149 log_delta_p=-4.3915 log_delta_a=-11.5257 min_alpha=0.0276 mean_alpha=0.2034 median_alpha=0.1699 max_alpha=0.9000 beta=0.0055

22:45:25 - INFO - EM Iter  15: ll=-1958.7675 log_delta_p=-4.5563 log_delta_a=-11.5639 min_alpha=0.0235 mean_alpha=0.1868 median_alpha=0.1502 max_alpha=0.9000 beta=0.0053

22:45:25 - INFO - EM Iter  16: ll=-1958.2272 log_delta_p=-4.7350 log_delta_a=-11.7175 min_alpha=0.0198 mean_alpha=0.1724 median_alpha=0.1334 max_alpha=0.9000 beta=0.0051

22:45:25 - INFO - EM Iter  17: ll=-1957.7749 log_delta_p=-4.8328 log_delta_a=-11.8066 min_alpha=0.0166 mean_alpha=0.1600 median_alpha=0.1190 max_alpha=0.9000 beta=0.0049

22:45:25 - INFO - EM Iter  18: ll=-1957.3902 log_delta_p=-4.9500 log_delta_a=-11.8771 min_alpha=0.0142 mean_alpha=0.1494 median_alpha=0.1067 max_alpha=0.9000 beta=0.0047

22:45:25 - INFO - EM Iter  19: ll=-1957.0571 log_delta_p=-5.0300 log_delta_a=-11.9624 min_alpha=0.0123 mean_alpha=0.1405 median_alpha=0.0964 max_alpha=0.9000 beta=0.0046

22:45:25 - INFO - EM Iter  20: ll=-1956.7606 log_delta_p=-5.0878 log_delta_a=-12.0525 min_alpha=0.0110 mean_alpha=0.1332 median_alpha=0.0876 max_alpha=0.9000 beta=0.0045

22:45:25 - INFO - EM Iter  21: ll=-1956.4830 log_delta_p=-5.1282 log_delta_a=-12.1630 min_alpha=0.0100 mean_alpha=0.1274 median_alpha=0.0801 max_alpha=0.9000 beta=0.0044

22:45:25 - INFO - EM Iter  22: ll=-1956.2037 log_delta_p=-5.1492 log_delta_a=-12.2367 min_alpha=0.0092 mean_alpha=0.1230 median_alpha=0.0737 max_alpha=0.9000 beta=0.0044

22:45:25 - INFO - EM Iter  23: ll=-1955.8965 log_delta_p=-5.1507 log_delta_a=-12.4064 min_alpha=0.0083 mean_alpha=0.1199 median_alpha=0.0683 max_alpha=0.9000 beta=0.0043

22:45:25 - INFO - EM Iter  24: ll=-1955.5314 log_delta_p=-5.1267 log_delta_a=-12.7726 min_alpha=0.0074 mean_alpha=0.1180 median_alpha=0.0638 max_alpha=0.9000 beta=0.0043

22:45:25 - INFO - EM Iter  25: ll=-1955.0878 log_delta_p=-5.0772 log_delta_a=-12.5918 min_alpha=0.0066 mean_alpha=0.1169 median_alpha=0.0600 max_alpha=0.9000 beta=0.0043

22:45:25 - INFO - EM Iter  26: ll=-1954.5864 log_delta_p=-5.1304 log_delta_a=-12.6651 min_alpha=0.0055 mean_alpha=0.1162 median_alpha=0.0564 max_alpha=0.9000 beta=0.0043

22:45:25 - INFO - EM Iter  27: ll=-1954.1110 log_delta_p=-5.3944 log_delta_a=-12.9747 min_alpha=0.0046 mean_alpha=0.1147 median_alpha=0.0534 max_alpha=0.9000 beta=0.0043

22:45:25 - INFO - EM Iter  28: ll=-1953.8109 log_delta_p=-5.8824 log_delta_a=-12.9435 min_alpha=0.0040 mean_alpha=0.1119 median_alpha=0.0510 max_alpha=0.9000 beta=0.0044

22:45:25 - INFO - EM Iter  29: ll=-1953.7107 log_delta_p=-5.1705 log_delta_a=-12.7059 min_alpha=0.0035 mean_alpha=0.1097 median_alpha=0.0490 max_alpha=0.9000 beta=0.0044

22:45:25 - INFO - EM Iter  30: ll=-1953.6574 log_delta_p=-6.7686 log_delta_a=-12.6581 min_alpha=0.0033 mean_alpha=0.1078 median_alpha=0.0472 max_alpha=0.9000 beta=0.0045

22:45:25 - INFO - EM Iter  31: ll=-1953.6262 log_delta_p=-6.6726 log_delta_a=-13.0991 min_alpha=0.0031 mean_alpha=0.1062 median_alpha=0.0458 max_alpha=0.9000 beta=0.0046

22:45:25 - INFO - EM Iter  32: ll=-1953.6027 log_delta_p=-6.8726 log_delta_a=-12.4535 min_alpha=0.0030 mean_alpha=0.1049 median_alpha=0.0445 max_alpha=0.9000 beta=0.0047

22:45:25 - INFO - EM Iter  33: ll=-1953.5843 log_delta_p=-7.0570 log_delta_a=-12.4552 min_alpha=0.0030 mean_alpha=0.1037 median_alpha=0.0434 max_alpha=0.9000 beta=0.0048

22:45:25 - INFO - EM Iter  34: ll=-1953.5701 log_delta_p=-7.2254 log_delta_a=-12.3722 min_alpha=0.0030 mean_alpha=0.1027 median_alpha=0.0423 max_alpha=0.9000 beta=0.0049

22:45:25 - INFO - EM Iter  35: ll=-1953.5586 log_delta_p=-7.3862 log_delta_a=-12.3537 min_alpha=0.0029 mean_alpha=0.1018 median_alpha=0.0414 max_alpha=0.9000 beta=0.0050

22:45:25 - INFO - EM Iter  36: ll=-1953.5490 log_delta_p=-7.5426 log_delta_a=-12.5055 min_alpha=0.0029 mean_alpha=0.1010 median_alpha=0.0406 max_alpha=0.9000 beta=0.0051

22:45:25 - INFO - EM Iter  37: ll=-1953.5413 log_delta_p=-7.6969 log_delta_a=-12.2640 min_alpha=0.0028 mean_alpha=0.1003 median_alpha=0.0398 max_alpha=0.9000 beta=0.0052

22:45:25 - INFO - EM Iter  38: ll=-1953.5347 log_delta_p=-7.8498 log_delta_a=-12.1740 min_alpha=0.0026 mean_alpha=0.0997 median_alpha=0.0392 max_alpha=0.9000 beta=0.0054

22:45:25 - INFO - EM Iter  39: ll=-1953.5294 log_delta_p=-8.0019 log_delta_a=-12.1505 min_alpha=0.0024 mean_alpha=0.0992 median_alpha=0.0387 max_alpha=0.9000 beta=0.0055

22:45:25 - INFO - EM Iter  40: ll=-1953.5251 log_delta_p=-8.1528 log_delta_a=-12.1964 min_alpha=0.0023 mean_alpha=0.0987 median_alpha=0.0382 max_alpha=0.9000 beta=0.0057

22:45:25 - INFO - EM Iter  41: ll=-1953.5211 log_delta_p=-8.3030 log_delta_a=-12.0933 min_alpha=0.0021 mean_alpha=0.0983 median_alpha=0.0377 max_alpha=0.9000 beta=0.0058

22:45:25 - INFO - EM Iter  42: ll=-1953.5181 log_delta_p=-8.4535 log_delta_a=-12.0961 min_alpha=0.0020 mean_alpha=0.0979 median_alpha=0.0373 max_alpha=0.9000 beta=0.0060

22:45:25 - INFO - EM Iter  43: ll=-1953.5149 log_delta_p=-8.6023 log_delta_a=-12.1336 min_alpha=0.0018 mean_alpha=0.0975 median_alpha=0.0369 max_alpha=0.9000 beta=0.0061

22:45:26 - INFO - EM Iter  44: ll=-1953.5122 log_delta_p=-8.7515 log_delta_a=-12.0106 min_alpha=0.0017 mean_alpha=0.0972 median_alpha=0.0366 max_alpha=0.9000 beta=0.0063

22:45:26 - INFO - EM Iter  45: ll=-1953.5098 log_delta_p=-8.9000 log_delta_a=-12.0413 min_alpha=0.0016 mean_alpha=0.0969 median_alpha=0.0363 max_alpha=0.9000 beta=0.0065

22:45:26 - INFO - EM Iter  46: ll=-1953.5069 log_delta_p=-9.0484 log_delta_a=-12.1873 min_alpha=0.0015 mean_alpha=0.0966 median_alpha=0.0359 max_alpha=0.9000 beta=0.0066

22:45:26 - INFO - EM Iter  47: ll=-1953.5048 log_delta_p=-9.1972 log_delta_a=-12.1023 min_alpha=0.0014 mean_alpha=0.0964 median_alpha=0.0357 max_alpha=0.9000 beta=0.0068

22:45:26 - INFO - EM Iter  48: ll=-1953.5029 log_delta_p=-9.3438 log_delta_a=-12.0200 min_alpha=0.0013 mean_alpha=0.0961 median_alpha=0.0354 max_alpha=0.9000 beta=0.0070

22:45:26 - INFO - EM Iter  49: ll=-1953.5010 log_delta_p=-9.4941 log_delta_a=-12.0095 min_alpha=0.0012 mean_alpha=0.0982 median_alpha=0.0351 max_alpha=0.9464 beta=0.0072

22:45:26 - INFO - EM Iter  50: ll=-1945.4726 log_delta_p=-9.6415 log_delta_a=-11.9213 min_alpha=0.0011 mean_alpha=0.0994 median_alpha=0.0349 max_alpha=0.9712 beta=0.0072

22:45:26 - INFO - EM Iter  51: ll=-1945.3514 log_delta_p=-5.3769 log_delta_a=-11.0825 min_alpha=0.0010 mean_alpha=0.1001 median_alpha=0.0347 max_alpha=0.9845 beta=0.0071

22:45:26 - INFO - EM Iter  52: ll=-1945.2755 log_delta_p=-6.5643 log_delta_a=-12.6829 min_alpha=0.0009 mean_alpha=0.1006 median_alpha=0.0345 max_alpha=0.9916 beta=0.0071

22:45:26 - INFO - EM Iter  53: ll=-1945.2270 log_delta_p=-6.8902 log_delta_a=-12.6938 min_alpha=0.0008 mean_alpha=0.1009 median_alpha=0.0343 max_alpha=0.9955 beta=0.0071

22:45:26 - INFO - EM Iter  54: ll=-1945.1955 log_delta_p=-7.3102 log_delta_a=-12.8841 min_alpha=0.0007 mean_alpha=0.1010 median_alpha=0.0342 max_alpha=0.9976 beta=0.0071

22:45:26 - INFO - EM Iter  55: ll=-1945.1747 log_delta_p=-7.7309 log_delta_a=-13.1005 min_alpha=0.0006 mean_alpha=0.1011 median_alpha=0.0341 max_alpha=0.9987 beta=0.0071

22:45:26 - INFO - EM Iter  56: ll=-1945.1611 log_delta_p=-8.1490 log_delta_a=-15.1914 min_alpha=0.0005 mean_alpha=0.1011 median_alpha=0.0340 max_alpha=0.9993 beta=0.0071

22:45:26 - INFO - EM Iter  57: ll=-1945.1523 log_delta_p=-8.5644 log_delta_a=-13.1298 min_alpha=0.0004 mean_alpha=0.1011 median_alpha=0.0339 max_alpha=0.9996 beta=0.0072

22:45:26 - INFO - EM Iter  58: ll=-1945.1462 log_delta_p=-8.9771 log_delta_a=-12.9088 min_alpha=0.0004 mean_alpha=0.1011 median_alpha=0.0339 max_alpha=0.9998 beta=0.0072

22:45:26 - INFO - EM Iter  59: ll=-1945.1419 log_delta_p=-9.3867 log_delta_a=-12.9757 min_alpha=0.0003 mean_alpha=0.1011 median_alpha=0.0338 max_alpha=0.9999 beta=0.0072

22:45:26 - INFO - EM Iter  60: ll=-1945.1395 log_delta_p=-9.7931 log_delta_a=-12.7738 min_alpha=0.0003 mean_alpha=0.1011 median_alpha=0.0337 max_alpha=0.9999 beta=0.0072

22:45:26 - INFO - EM Iter  61: ll=-1945.1378 log_delta_p=-10.1988 log_delta_a=-12.7547 min_alpha=0.0002 mean_alpha=0.1010 median_alpha=0.0337 max_alpha=1.0000 beta=0.0072

22:45:26 - INFO - EM Iter  62: ll=-1945.1363 log_delta_p=-10.5964 log_delta_a=-12.6804 min_alpha=0.0002 mean_alpha=0.1010 median_alpha=0.0336 max_alpha=1.0000 beta=0.0072

22:45:26 - INFO - EM Iter  63: ll=-1945.1358 log_delta_p=-10.9480 log_delta_a=-12.6551 min_alpha=0.0002 mean_alpha=0.1010 median_alpha=0.0336 max_alpha=1.0000 beta=0.0072

22:45:26 - INFO - EM Iter  64: ll=-1945.1352 log_delta_p=-11.0784 log_delta_a=-12.6451 min_alpha=0.0001 mean_alpha=0.1010 median_alpha=0.0336 max_alpha=1.0000 beta=0.0072

22:45:26 - INFO - Converged.

22:45:26 - INFO - Saving inferred adata to '/home/mcaskey/cellsweep/notebooks/data/simulation1_small_noise/celltype_granularity/adata_cellsweep_merge_2.h5ad'

merge_2 done

22:45:27 - INFO - Starting cellsweep denoising at 2026-10-03 22:45:27, cellsweep version 0.1.3

22:45:27 - INFO - Inferring celltype profiles.

22:45:27 - INFO - Number of celltypes: 3

22:45:27 - INFO - Inferring the ambient profile from empty droplets.

Logging to /home/mcaskey/cellsweep/notebooks/data/simulation1_small_noise/celltype_granularity/cellsweep_merge_3.log

22:45:27 - INFO - adata.obs does not have 'init_alpha'. Setting to `init_alpha` argument.

22:45:27 - INFO - Performing Sparse EM with 32 Numba thread(s)

22:45:27 - INFO - EM Iter   1: ll=-1964.5653 log_delta_p=inf log_delta_a=inf min_alpha=0.5311 mean_alpha=0.6189 median_alpha=0.6327 max_alpha=0.6715 beta=0.0092

22:45:27 - INFO - EM Iter   2: ll=-1956.3427 log_delta_p=inf log_delta_a=inf min_alpha=0.3871 mean_alpha=0.5457 median_alpha=0.5563 max_alpha=0.6481 beta=0.0086

22:45:27 - INFO - EM Iter   3: ll=-1951.0998 log_delta_p=-2.3771 log_delta_a=-11.7732 min_alpha=0.2971 mean_alpha=0.4899 median_alpha=0.4963 max_alpha=0.6377 beta=0.0082

22:45:27 - INFO - EM Iter   4: ll=-1947.8803 log_delta_p=-2.8383 log_delta_a=-11.0761 min_alpha=0.2296 mean_alpha=0.4399 median_alpha=0.4427 max_alpha=0.6306 beta=0.0079

22:45:27 - INFO - EM Iter   5: ll=-1944.9475 log_delta_p=-2.5476 log_delta_a=-11.3087 min_alpha=0.1731 mean_alpha=0.3921 median_alpha=0.3909 max_alpha=0.6219 beta=0.0074

22:45:27 - INFO - EM Iter   6: ll=-1942.1781 log_delta_p=-2.6544 log_delta_a=-11.3726 min_alpha=0.1253 mean_alpha=0.3465 median_alpha=0.3416 max_alpha=0.6099 beta=0.0070

22:45:27 - INFO - EM Iter   7: ll=-1939.6394 log_delta_p=-2.8583 log_delta_a=-11.3041 min_alpha=0.0897 mean_alpha=0.3040 median_alpha=0.2953 max_alpha=0.5947 beta=0.0065

22:45:27 - INFO - EM Iter   8: ll=-1937.3949 log_delta_p=-3.1021 log_delta_a=-11.2460 min_alpha=0.0642 mean_alpha=0.2655 median_alpha=0.2528 max_alpha=0.5766 beta=0.0061

22:45:27 - INFO - EM Iter   9: ll=-1935.4731 log_delta_p=-3.3676 log_delta_a=-11.2004 min_alpha=0.0464 mean_alpha=0.2313 median_alpha=0.2162 max_alpha=0.5560 beta=0.0056

22:45:28 - INFO - EM Iter  10: ll=-1933.8709 log_delta_p=-3.6460 log_delta_a=-11.2147 min_alpha=0.0343 mean_alpha=0.2016 median_alpha=0.1837 max_alpha=0.5334 beta=0.0052

22:45:28 - INFO - EM Iter  11: ll=-1932.5626 log_delta_p=-3.9318 log_delta_a=-11.3216 min_alpha=0.0262 mean_alpha=0.1760 median_alpha=0.1573 max_alpha=0.5121 beta=0.0048

22:45:28 - INFO - EM Iter  12: ll=-1931.5107 log_delta_p=-4.1446 log_delta_a=-11.3195 min_alpha=0.0207 mean_alpha=0.1543 median_alpha=0.1347 max_alpha=0.4915 beta=0.0045

22:45:28 - INFO - EM Iter  13: ll=-1930.6752 log_delta_p=-4.3441 log_delta_a=-11.4203 min_alpha=0.0167 mean_alpha=0.1359 median_alpha=0.1164 max_alpha=0.4707 beta=0.0043

22:45:28 - INFO - EM Iter  14: ll=-1930.0168 log_delta_p=-4.5407 log_delta_a=-11.5400 min_alpha=0.0135 mean_alpha=0.1204 median_alpha=0.1018 max_alpha=0.4500 beta=0.0040

22:45:28 - INFO - EM Iter  15: ll=-1929.5003 log_delta_p=-4.7339 log_delta_a=-11.6650 min_alpha=0.0113 mean_alpha=0.1075 median_alpha=0.0899 max_alpha=0.4296 beta=0.0039

22:45:28 - INFO - EM Iter  16: ll=-1929.0963 log_delta_p=-4.9237 log_delta_a=-12.0204 min_alpha=0.0098 mean_alpha=0.0966 median_alpha=0.0804 max_alpha=0.4097 beta=0.0037

22:45:28 - INFO - EM Iter  17: ll=-1928.7803 log_delta_p=-5.1102 log_delta_a=-11.9583 min_alpha=0.0088 mean_alpha=0.0875 median_alpha=0.0730 max_alpha=0.3906 beta=0.0036

22:45:28 - INFO - EM Iter  18: ll=-1928.5334 log_delta_p=-5.2930 log_delta_a=-12.2153 min_alpha=0.0080 mean_alpha=0.0800 median_alpha=0.0666 max_alpha=0.3724 beta=0.0036

22:45:28 - INFO - EM Iter  19: ll=-1928.3411 log_delta_p=-5.4727 log_delta_a=-12.2690 min_alpha=0.0075 mean_alpha=0.0737 median_alpha=0.0616 max_alpha=0.3556 beta=0.0035

22:45:28 - INFO - EM Iter  20: ll=-1928.1912 log_delta_p=-5.6491 log_delta_a=-12.3580 min_alpha=0.0065 mean_alpha=0.0684 median_alpha=0.0576 max_alpha=0.3404 beta=0.0035

22:45:28 - INFO - EM Iter  21: ll=-1928.0747 log_delta_p=-5.8234 log_delta_a=-12.5701 min_alpha=0.0057 mean_alpha=0.0640 median_alpha=0.0541 max_alpha=0.3296 beta=0.0035

22:45:28 - INFO - EM Iter  22: ll=-1927.9845 log_delta_p=-5.9958 log_delta_a=-12.6941 min_alpha=0.0051 mean_alpha=0.0603 median_alpha=0.0512 max_alpha=0.3199 beta=0.0035

22:45:28 - INFO - EM Iter  23: ll=-1927.9141 log_delta_p=-6.1679 log_delta_a=-14.4856 min_alpha=0.0046 mean_alpha=0.0573 median_alpha=0.0487 max_alpha=0.3112 beta=0.0035

22:45:28 - INFO - EM Iter  24: ll=-1927.8595 log_delta_p=-6.3400 log_delta_a=-12.6906 min_alpha=0.0042 mean_alpha=0.0547 median_alpha=0.0466 max_alpha=0.3034 beta=0.0036

22:45:28 - INFO - EM Iter  25: ll=-1927.8174 log_delta_p=-6.5120 log_delta_a=-12.7014 min_alpha=0.0039 mean_alpha=0.0526 median_alpha=0.0449 max_alpha=0.2965 beta=0.0037

22:45:28 - INFO - EM Iter  26: ll=-1927.7850 log_delta_p=-6.6842 log_delta_a=-12.6812 min_alpha=0.0036 mean_alpha=0.0508 median_alpha=0.0434 max_alpha=0.2903 beta=0.0037

22:45:28 - INFO - EM Iter  27: ll=-1927.7598 log_delta_p=-6.8563 log_delta_a=-12.6277 min_alpha=0.0034 mean_alpha=0.0493 median_alpha=0.0421 max_alpha=0.2849 beta=0.0038

22:45:28 - INFO - EM Iter  28: ll=-1927.7403 log_delta_p=-7.0283 log_delta_a=-12.4844 min_alpha=0.0032 mean_alpha=0.0480 median_alpha=0.0411 max_alpha=0.2801 beta=0.0039

22:45:28 - INFO - EM Iter  29: ll=-1927.7253 log_delta_p=-7.2003 log_delta_a=-12.5481 min_alpha=0.0030 mean_alpha=0.0469 median_alpha=0.0400 max_alpha=0.2797 beta=0.0040

22:45:28 - INFO - EM Iter  30: ll=-1927.7134 log_delta_p=-7.3719 log_delta_a=-12.2960 min_alpha=0.0029 mean_alpha=0.0460 median_alpha=0.0393 max_alpha=0.2794 beta=0.0041

22:45:28 - INFO - EM Iter  31: ll=-1927.7043 log_delta_p=-7.5436 log_delta_a=-12.2479 min_alpha=0.0027 mean_alpha=0.0452 median_alpha=0.0385 max_alpha=0.2792 beta=0.0042

22:45:28 - INFO - EM Iter  32: ll=-1927.6970 log_delta_p=-7.7149 log_delta_a=-12.4777 min_alpha=0.0026 mean_alpha=0.0445 median_alpha=0.0377 max_alpha=0.2790 beta=0.0043

22:45:28 - INFO - EM Iter  33: ll=-1927.6910 log_delta_p=-7.8857 log_delta_a=-12.3254 min_alpha=0.0025 mean_alpha=0.0439 median_alpha=0.0373 max_alpha=0.2788 beta=0.0045

22:45:28 - INFO - EM Iter  34: ll=-1919.8320 log_delta_p=-8.0564 log_delta_a=-12.1921 min_alpha=0.0023 mean_alpha=0.0434 median_alpha=0.0367 max_alpha=0.2787 beta=0.0045

22:45:28 - INFO - EM Iter  35: ll=-1919.8290 log_delta_p=-8.2266 log_delta_a=-11.5339 min_alpha=0.0022 mean_alpha=0.0429 median_alpha=0.0364 max_alpha=0.2786 beta=0.0045

22:45:28 - INFO - EM Iter  36: ll=-1919.8264 log_delta_p=-8.2965 log_delta_a=-12.6925 min_alpha=0.0021 mean_alpha=0.0426 median_alpha=0.0360 max_alpha=0.2785 beta=0.0045

22:45:28 - INFO - EM Iter  37: ll=-1919.8245 log_delta_p=-8.4620 log_delta_a=-12.6685 min_alpha=0.0018 mean_alpha=0.0422 median_alpha=0.0358 max_alpha=0.2784 beta=0.0046

22:45:28 - INFO - EM Iter  38: ll=-1919.8232 log_delta_p=-8.6283 log_delta_a=-12.6877 min_alpha=0.0017 mean_alpha=0.0420 median_alpha=0.0356 max_alpha=0.2783 beta=0.0046

22:45:28 - INFO - EM Iter  39: ll=-1919.8221 log_delta_p=-8.7941 log_delta_a=-12.6778 min_alpha=0.0015 mean_alpha=0.0417 median_alpha=0.0353 max_alpha=0.2783 beta=0.0046

22:45:28 - INFO - EM Iter  40: ll=-1919.8213 log_delta_p=-8.9584 log_delta_a=-13.0028 min_alpha=0.0013 mean_alpha=0.0415 median_alpha=0.0352 max_alpha=0.2782 beta=0.0046

22:45:28 - INFO - EM Iter  41: ll=-1919.8208 log_delta_p=-9.1222 log_delta_a=-12.7192 min_alpha=0.0012 mean_alpha=0.0414 median_alpha=0.0350 max_alpha=0.2782 beta=0.0047

22:45:28 - INFO - EM Iter  42: ll=-1919.8202 log_delta_p=-9.2853 log_delta_a=-12.5692 min_alpha=0.0011 mean_alpha=0.0412 median_alpha=0.0348 max_alpha=0.2781 beta=0.0047

22:45:28 - INFO - EM Iter  43: ll=-1919.8198 log_delta_p=-9.4466 log_delta_a=-12.5959 min_alpha=0.0010 mean_alpha=0.0411 median_alpha=0.0347 max_alpha=0.2781 beta=0.0048

22:45:28 - INFO - EM Iter  44: ll=-1919.8195 log_delta_p=-9.6067 log_delta_a=-12.5556 min_alpha=0.0009 mean_alpha=0.0410 median_alpha=0.0345 max_alpha=0.2781 beta=0.0048

22:45:28 - INFO - EM Iter  45: ll=-1919.8195 log_delta_p=-9.7667 log_delta_a=-12.6543 min_alpha=0.0008 mean_alpha=0.0408 median_alpha=0.0344 max_alpha=0.2780 beta=0.0048

22:45:28 - INFO - EM Iter  46: ll=-1919.8192 log_delta_p=-9.9234 log_delta_a=-12.5445 min_alpha=0.0007 mean_alpha=0.0408 median_alpha=0.0343 max_alpha=0.2780 beta=0.0049

22:45:28 - INFO - EM Iter  47: ll=-1919.8192 log_delta_p=-10.0810 log_delta_a=-12.4971 min_alpha=0.0007 mean_alpha=0.0407 median_alpha=0.0343 max_alpha=0.2780 beta=0.0049

22:45:28 - INFO - EM Iter  48: ll=-1919.8192 log_delta_p=-10.2379 log_delta_a=-12.5257 min_alpha=0.0006 mean_alpha=0.0406 median_alpha=0.0342 max_alpha=0.2779 beta=0.0050

22:45:28 - INFO - EM Iter  49: ll=-1919.8186 log_delta_p=-10.3880 log_delta_a=-12.5777 min_alpha=0.0005 mean_alpha=0.0405 median_alpha=0.0341 max_alpha=0.2779 beta=0.0050

22:45:28 - INFO - EM Iter  50: ll=-1919.8186 log_delta_p=-10.5426 log_delta_a=-12.5401 min_alpha=0.0005 mean_alpha=0.0404 median_alpha=0.0341 max_alpha=0.2779 beta=0.0051

22:45:28 - INFO - EM Iter  51: ll=-1919.8186 log_delta_p=-10.6915 log_delta_a=-12.5986 min_alpha=0.0004 mean_alpha=0.0404 median_alpha=0.0340 max_alpha=0.2778 beta=0.0051

22:45:28 - INFO - Converged.

22:45:29 - INFO - Saving inferred adata to '/home/mcaskey/cellsweep/notebooks/data/simulation1_small_noise/celltype_granularity/adata_cellsweep_merge_3.h5ad'

merge_3 done

22:45:29 - INFO - Starting cellsweep denoising at 2026-10-03 22:45:29, cellsweep version 0.1.3

22:45:30 - INFO - Inferring celltype profiles.

22:45:30 - INFO - Number of celltypes: 6

22:45:30 - INFO - Inferring the ambient profile from empty droplets.

Logging to /home/mcaskey/cellsweep/notebooks/data/simulation1_small_noise/celltype_granularity/cellsweep_merge_6.log

22:45:30 - INFO - adata.obs does not have 'init_alpha'. Setting to `init_alpha` argument.

22:45:30 - INFO - Performing Sparse EM with 32 Numba thread(s)

22:45:30 - INFO - EM Iter   1: ll=-1937.7658 log_delta_p=inf log_delta_a=inf min_alpha=0.3800 mean_alpha=0.5755 median_alpha=0.5783 max_alpha=0.6400 beta=0.0087

22:45:30 - INFO - EM Iter   2: ll=-1917.6488 log_delta_p=inf log_delta_a=inf min_alpha=0.2841 mean_alpha=0.4857 median_alpha=0.4866 max_alpha=0.6010 beta=0.0080

22:45:30 - INFO - EM Iter   3: ll=-1910.8003 log_delta_p=-2.1387 log_delta_a=-11.7778 min_alpha=0.2110 mean_alpha=0.4234 median_alpha=0.4234 max_alpha=0.5783 beta=0.0074

22:45:30 - INFO - EM Iter   4: ll=-1906.3752 log_delta_p=-2.1604 log_delta_a=-10.7536 min_alpha=0.1526 mean_alpha=0.3663 median_alpha=0.3653 max_alpha=0.5547 beta=0.0069

22:45:30 - INFO - EM Iter   5: ll=-1902.1843 log_delta_p=-2.3744 log_delta_a=-11.0724 min_alpha=0.1085 mean_alpha=0.3115 median_alpha=0.3090 max_alpha=0.5269 beta=0.0063

22:45:30 - INFO - EM Iter   6: ll=-1898.3299 log_delta_p=-2.6422 log_delta_a=-11.0861 min_alpha=0.0728 mean_alpha=0.2608 median_alpha=0.2571 max_alpha=0.4962 beta=0.0057

22:45:30 - INFO - EM Iter   7: ll=-1894.9811 log_delta_p=-2.8534 log_delta_a=-11.0005 min_alpha=0.0485 mean_alpha=0.2162 median_alpha=0.2113 max_alpha=0.4645 beta=0.0052

22:45:30 - INFO - EM Iter   8: ll=-1892.2213 log_delta_p=-3.1015 log_delta_a=-10.9754 min_alpha=0.0331 mean_alpha=0.1785 median_alpha=0.1729 max_alpha=0.4335 beta=0.0047

22:45:30 - INFO - EM Iter   9: ll=-1890.0506 log_delta_p=-3.3716 log_delta_a=-11.0184 min_alpha=0.0236 mean_alpha=0.1476 median_alpha=0.1412 max_alpha=0.4043 beta=0.0042

22:45:30 - INFO - EM Iter  10: ll=-1888.4109 log_delta_p=-3.6550 log_delta_a=-11.1075 min_alpha=0.0179 mean_alpha=0.1230 median_alpha=0.1159 max_alpha=0.3784 beta=0.0038

22:45:30 - INFO - EM Iter  11: ll=-1887.2147 log_delta_p=-3.9463 log_delta_a=-11.2351 min_alpha=0.0144 mean_alpha=0.1038 median_alpha=0.0967 max_alpha=0.3594 beta=0.0035

22:45:30 - INFO - EM Iter  12: ll=-1886.3675 log_delta_p=-4.2419 log_delta_a=-11.4341 min_alpha=0.0123 mean_alpha=0.0889 median_alpha=0.0820 max_alpha=0.3436 beta=0.0033

22:45:30 - INFO - EM Iter  13: ll=-1885.7830 log_delta_p=-4.5397 log_delta_a=-11.5341 min_alpha=0.0110 mean_alpha=0.0776 median_alpha=0.0707 max_alpha=0.3306 beta=0.0031

22:45:30 - INFO - EM Iter  14: ll=-1885.3890 log_delta_p=-4.8244 log_delta_a=-11.7531 min_alpha=0.0102 mean_alpha=0.0690 median_alpha=0.0622 max_alpha=0.3200 beta=0.0030

22:45:30 - INFO - EM Iter  15: ll=-1885.1282 log_delta_p=-5.1031 log_delta_a=-11.9658 min_alpha=0.0098 mean_alpha=0.0625 median_alpha=0.0559 max_alpha=0.3115 beta=0.0029

22:45:30 - INFO - EM Iter  16: ll=-1884.9584 log_delta_p=-5.3816 log_delta_a=-12.1016 min_alpha=0.0095 mean_alpha=0.0575 median_alpha=0.0512 max_alpha=0.3048 beta=0.0029

22:45:30 - INFO - EM Iter  17: ll=-1884.8490 log_delta_p=-5.6595 log_delta_a=-12.3474 min_alpha=0.0090 mean_alpha=0.0538 median_alpha=0.0474 max_alpha=0.2995 beta=0.0029

22:45:30 - INFO - EM Iter  18: ll=-1884.7792 log_delta_p=-5.9364 log_delta_a=-12.6037 min_alpha=0.0079 mean_alpha=0.0510 median_alpha=0.0446 max_alpha=0.2952 beta=0.0029

22:45:30 - INFO - EM Iter  19: ll=-1884.7347 log_delta_p=-6.2124 log_delta_a=-13.5193 min_alpha=0.0070 mean_alpha=0.0489 median_alpha=0.0425 max_alpha=0.2919 beta=0.0029

22:45:30 - INFO - EM Iter  20: ll=-1884.7064 log_delta_p=-6.4871 log_delta_a=-12.7322 min_alpha=0.0062 mean_alpha=0.0473 median_alpha=0.0408 max_alpha=0.2893 beta=0.0030

22:45:30 - INFO - EM Iter  21: ll=-1884.6885 log_delta_p=-6.7605 log_delta_a=-12.6260 min_alpha=0.0055 mean_alpha=0.0461 median_alpha=0.0396 max_alpha=0.2873 beta=0.0031

22:45:30 - INFO - EM Iter  22: ll=-1884.6763 log_delta_p=-7.0324 log_delta_a=-12.4648 min_alpha=0.0050 mean_alpha=0.0451 median_alpha=0.0387 max_alpha=0.2857 beta=0.0032

22:45:30 - INFO - EM Iter  23: ll=-1876.8034 log_delta_p=-7.3027 log_delta_a=-12.4115 min_alpha=0.0046 mean_alpha=0.0443 median_alpha=0.0379 max_alpha=0.2844 beta=0.0032

22:45:30 - INFO - EM Iter  24: ll=-1876.7984 log_delta_p=-7.5720 log_delta_a=-12.0150 min_alpha=0.0042 mean_alpha=0.0438 median_alpha=0.0374 max_alpha=0.2834 beta=0.0032

22:45:30 - INFO - EM Iter  25: ll=-1876.7952 log_delta_p=-7.7701 log_delta_a=-12.7561 min_alpha=0.0039 mean_alpha=0.0433 median_alpha=0.0370 max_alpha=0.2827 beta=0.0033

22:45:30 - INFO - EM Iter  26: ll=-1876.7931 log_delta_p=-8.0333 log_delta_a=-12.7987 min_alpha=0.0037 mean_alpha=0.0430 median_alpha=0.0366 max_alpha=0.2821 beta=0.0033

22:45:30 - INFO - EM Iter  27: ll=-1876.7922 log_delta_p=-8.2957 log_delta_a=-12.5899 min_alpha=0.0035 mean_alpha=0.0427 median_alpha=0.0364 max_alpha=0.2816 beta=0.0034

22:45:30 - INFO - EM Iter  28: ll=-1876.7914 log_delta_p=-8.5562 log_delta_a=-12.6180 min_alpha=0.0033 mean_alpha=0.0424 median_alpha=0.0361 max_alpha=0.2812 beta=0.0034

22:45:30 - INFO - EM Iter  29: ll=-1876.7907 log_delta_p=-8.8144 log_delta_a=-12.5587 min_alpha=0.0032 mean_alpha=0.0423 median_alpha=0.0359 max_alpha=0.2809 beta=0.0035

22:45:30 - INFO - EM Iter  30: ll=-1876.7904 log_delta_p=-9.0700 log_delta_a=-12.5270 min_alpha=0.0030 mean_alpha=0.0421 median_alpha=0.0358 max_alpha=0.2807 beta=0.0035

22:45:30 - INFO - EM Iter  31: ll=-1876.7901 log_delta_p=-9.3226 log_delta_a=-12.6080 min_alpha=0.0029 mean_alpha=0.0420 median_alpha=0.0357 max_alpha=0.2805 beta=0.0036

22:45:30 - INFO - EM Iter  32: ll=-1876.7899 log_delta_p=-9.5708 log_delta_a=-12.6566 min_alpha=0.0028 mean_alpha=0.0418 median_alpha=0.0356 max_alpha=0.2803 beta=0.0036

22:45:30 - INFO - EM Iter  33: ll=-1876.7893 log_delta_p=-9.5634 log_delta_a=-12.6928 min_alpha=0.0027 mean_alpha=0.0417 median_alpha=0.0354 max_alpha=0.2802 beta=0.0037

22:45:30 - INFO - EM Iter  34: ll=-1876.7893 log_delta_p=-9.4823 log_delta_a=-12.7566 min_alpha=0.0026 mean_alpha=0.0416 median_alpha=0.0353 max_alpha=0.2801 beta=0.0038

22:45:30 - INFO - EM Iter  35: ll=-1876.7891 log_delta_p=-9.4003 log_delta_a=-12.7093 min_alpha=0.0025 mean_alpha=0.0416 median_alpha=0.0352 max_alpha=0.2800 beta=0.0038

22:45:30 - INFO - Converged.

22:45:31 - INFO - Saving inferred adata to '/home/mcaskey/cellsweep/notebooks/data/simulation1_small_noise/celltype_granularity/adata_cellsweep_merge_6.h5ad'

merge_6 done

22:45:31 - INFO - Starting cellsweep denoising at 2026-10-03 22:45:31, cellsweep version 0.1.3

22:45:31 - INFO - Inferring celltype profiles.

22:45:31 - INFO - Number of celltypes: 12

22:45:32 - INFO - Inferring the ambient profile from empty droplets.

Logging to /home/mcaskey/cellsweep/notebooks/data/simulation1_small_noise/celltype_granularity/cellsweep_truth.log

22:45:32 - INFO - adata.obs does not have 'init_alpha'. Setting to `init_alpha` argument.

22:45:32 - INFO - Performing Sparse EM with 32 Numba thread(s)

22:45:32 - INFO - EM Iter   1: ll=-1906.9072 log_delta_p=inf log_delta_a=inf min_alpha=0.3746 mean_alpha=0.5410 median_alpha=0.5452 max_alpha=0.6161 beta=0.0083

22:45:32 - INFO - EM Iter   2: ll=-1876.8997 log_delta_p=inf log_delta_a=inf min_alpha=0.2859 mean_alpha=0.4519 median_alpha=0.4535 max_alpha=0.5797 beta=0.0076

22:45:32 - INFO - EM Iter   3: ll=-1870.1086 log_delta_p=-2.0291 log_delta_a=-10.9970 min_alpha=0.2163 mean_alpha=0.3892 median_alpha=0.3896 max_alpha=0.5638 beta=0.0070

22:45:32 - INFO - EM Iter   4: ll=-1864.9784 log_delta_p=-2.1575 log_delta_a=-10.7430 min_alpha=0.1598 mean_alpha=0.3290 median_alpha=0.3282 max_alpha=0.5383 beta=0.0064

22:45:32 - INFO - EM Iter   5: ll=-1860.1005 log_delta_p=-2.3686 log_delta_a=-11.0525 min_alpha=0.1087 mean_alpha=0.2719 median_alpha=0.2700 max_alpha=0.5052 beta=0.0058

22:45:32 - INFO - EM Iter   6: ll=-1855.7539 log_delta_p=-2.5908 log_delta_a=-10.9905 min_alpha=0.0723 mean_alpha=0.2210 median_alpha=0.2181 max_alpha=0.4707 beta=0.0052

22:45:32 - INFO - EM Iter   7: ll=-1852.1456 log_delta_p=-2.8318 log_delta_a=-10.9179 min_alpha=0.0481 mean_alpha=0.1781 median_alpha=0.1741 max_alpha=0.4391 beta=0.0046

22:45:32 - INFO - EM Iter   8: ll=-1849.3370 log_delta_p=-3.1051 log_delta_a=-10.9199 min_alpha=0.0328 mean_alpha=0.1437 median_alpha=0.1387 max_alpha=0.4103 beta=0.0041

22:45:32 - INFO - EM Iter   9: ll=-1847.2702 log_delta_p=-3.4022 log_delta_a=-10.9701 min_alpha=0.0235 mean_alpha=0.1169 median_alpha=0.1115 max_alpha=0.3850 beta=0.0036

22:45:32 - INFO - EM Iter  10: ll=-1845.8229 log_delta_p=-3.7147 log_delta_a=-11.1145 min_alpha=0.0179 mean_alpha=0.0967 median_alpha=0.0910 max_alpha=0.3636 beta=0.0033

22:45:32 - INFO - EM Iter  11: ll=-1844.8514 log_delta_p=-4.0366 log_delta_a=-11.2709 min_alpha=0.0145 mean_alpha=0.0818 median_alpha=0.0757 max_alpha=0.3460 beta=0.0030

22:45:32 - INFO - EM Iter  12: ll=-1844.2235 log_delta_p=-4.3640 log_delta_a=-11.5029 min_alpha=0.0124 mean_alpha=0.0708 median_alpha=0.0647 max_alpha=0.3317 beta=0.0029

22:45:32 - INFO - EM Iter  13: ll=-1843.8310 log_delta_p=-4.6947 log_delta_a=-11.7029 min_alpha=0.0112 mean_alpha=0.0629 median_alpha=0.0567 max_alpha=0.3203 beta=0.0028

22:45:32 - INFO - EM Iter  14: ll=-1843.5922 log_delta_p=-5.0270 log_delta_a=-11.9522 min_alpha=0.0100 mean_alpha=0.0572 median_alpha=0.0510 max_alpha=0.3114 beta=0.0027

22:45:32 - INFO - EM Iter  15: ll=-1843.4498 log_delta_p=-5.3598 log_delta_a=-12.3189 min_alpha=0.0091 mean_alpha=0.0531 median_alpha=0.0468 max_alpha=0.3045 beta=0.0027

22:45:32 - INFO - EM Iter  16: ll=-1843.3666 log_delta_p=-5.6922 log_delta_a=-12.7320 min_alpha=0.0085 mean_alpha=0.0501 median_alpha=0.0438 max_alpha=0.2991 beta=0.0027

22:45:32 - INFO - EM Iter  17: ll=-1843.3182 log_delta_p=-6.0237 log_delta_a=-12.6090 min_alpha=0.0081 mean_alpha=0.0480 median_alpha=0.0416 max_alpha=0.2949 beta=0.0027

22:45:32 - INFO - EM Iter  18: ll=-1843.2904 log_delta_p=-6.3537 log_delta_a=-12.6083 min_alpha=0.0071 mean_alpha=0.0464 median_alpha=0.0399 max_alpha=0.2917 beta=0.0028

22:45:32 - INFO - EM Iter  19: ll=-1843.2733 log_delta_p=-6.6818 log_delta_a=-12.6041 min_alpha=0.0062 mean_alpha=0.0452 median_alpha=0.0388 max_alpha=0.2893 beta=0.0029

22:45:32 - INFO - EM Iter  20: ll=-1835.3955 log_delta_p=-7.0081 log_delta_a=-12.4184 min_alpha=0.0055 mean_alpha=0.0444 median_alpha=0.0379 max_alpha=0.2874 beta=0.0029

22:45:32 - INFO - EM Iter  21: ll=-1835.3898 log_delta_p=-7.3325 log_delta_a=-11.8925 min_alpha=0.0049 mean_alpha=0.0437 median_alpha=0.0373 max_alpha=0.2860 beta=0.0029

22:45:32 - INFO - EM Iter  22: ll=-1835.3864 log_delta_p=-7.5849 log_delta_a=-12.6999 min_alpha=0.0045 mean_alpha=0.0433 median_alpha=0.0369 max_alpha=0.2849 beta=0.0030

22:45:32 - INFO - EM Iter  23: ll=-1835.3840 log_delta_p=-7.9031 log_delta_a=-12.6355 min_alpha=0.0041 mean_alpha=0.0429 median_alpha=0.0365 max_alpha=0.2841 beta=0.0030

22:45:32 - INFO - EM Iter  24: ll=-1835.3829 log_delta_p=-8.2187 log_delta_a=-12.5551 min_alpha=0.0038 mean_alpha=0.0426 median_alpha=0.0362 max_alpha=0.2835 beta=0.0031

22:45:32 - INFO - EM Iter  25: ll=-1835.3821 log_delta_p=-8.4067 log_delta_a=-12.5664 min_alpha=0.0036 mean_alpha=0.0424 median_alpha=0.0360 max_alpha=0.2830 beta=0.0031

22:45:32 - INFO - EM Iter  26: ll=-1835.3813 log_delta_p=-8.5190 log_delta_a=-12.6148 min_alpha=0.0034 mean_alpha=0.0422 median_alpha=0.0358 max_alpha=0.2826 beta=0.0032

22:45:32 - INFO - EM Iter  27: ll=-1835.3811 log_delta_p=-8.5920 log_delta_a=-12.6083 min_alpha=0.0032 mean_alpha=0.0421 median_alpha=0.0357 max_alpha=0.2823 beta=0.0033

22:45:32 - INFO - EM Iter  28: ll=-1835.3806 log_delta_p=-8.5533 log_delta_a=-12.7564 min_alpha=0.0030 mean_alpha=0.0420 median_alpha=0.0355 max_alpha=0.2821 beta=0.0033

22:45:32 - INFO - EM Iter  29: ll=-1835.3802 log_delta_p=-8.5348 log_delta_a=-13.1408 min_alpha=0.0028 mean_alpha=0.0418 median_alpha=0.0354 max_alpha=0.2819 beta=0.0034

22:45:32 - INFO - EM Iter  30: ll=-1835.3798 log_delta_p=-8.5536 log_delta_a=-13.1983 min_alpha=0.0027 mean_alpha=0.0417 median_alpha=0.0353 max_alpha=0.2817 beta=0.0034

22:45:32 - INFO - EM Iter  31: ll=-1835.3797 log_delta_p=-8.6062 log_delta_a=-13.2640 min_alpha=0.0025 mean_alpha=0.0417 median_alpha=0.0352 max_alpha=0.2816 beta=0.0035

22:45:32 - INFO - EM Iter  32: ll=-1835.3795 log_delta_p=-8.6759 log_delta_a=-13.0742 min_alpha=0.0024 mean_alpha=0.0416 median_alpha=0.0352 max_alpha=0.2815 beta=0.0036

22:45:32 - INFO - EM Iter  33: ll=-1835.3794 log_delta_p=-8.7507 log_delta_a=-13.2211 min_alpha=0.0023 mean_alpha=0.0415 median_alpha=0.0351 max_alpha=0.2814 beta=0.0036

22:45:32 - INFO - EM Iter  34: ll=-1835.3790 log_delta_p=-8.8235 log_delta_a=-13.1616 min_alpha=0.0021 mean_alpha=0.0414 median_alpha=0.0350 max_alpha=0.2813 beta=0.0037

22:45:32 - INFO - EM Iter  35: ll=-1835.3790 log_delta_p=-8.8895 log_delta_a=-13.2174 min_alpha=0.0020 mean_alpha=0.0413 median_alpha=0.0350 max_alpha=0.2813 beta=0.0038

22:45:32 - INFO - EM Iter  36: ll=-1835.3790 log_delta_p=-8.9366 log_delta_a=-13.0077 min_alpha=0.0019 mean_alpha=0.0413 median_alpha=0.0349 max_alpha=0.2812 beta=0.0038

22:45:32 - INFO - EM Iter  37: ll=-1835.3787 log_delta_p=-8.9627 log_delta_a=-13.0829 min_alpha=0.0017 mean_alpha=0.0412 median_alpha=0.0348 max_alpha=0.2812 beta=0.0039

22:45:32 - INFO - EM Iter  38: ll=-1835.3786 log_delta_p=-8.9696 log_delta_a=-12.9854 min_alpha=0.0016 mean_alpha=0.0411 median_alpha=0.0348 max_alpha=0.2811 beta=0.0039

22:45:32 - INFO - EM Iter  39: ll=-1835.3784 log_delta_p=-8.9557 log_delta_a=-12.8322 min_alpha=0.0015 mean_alpha=0.0411 median_alpha=0.0347 max_alpha=0.2811 beta=0.0040

22:45:32 - INFO - EM Iter  40: ll=-1835.3784 log_delta_p=-8.9269 log_delta_a=-12.6846 min_alpha=0.0014 mean_alpha=0.0410 median_alpha=0.0347 max_alpha=0.2810 beta=0.0040

22:45:32 - INFO - EM Iter  41: ll=-1835.3779 log_delta_p=-8.8970 log_delta_a=-12.8140 min_alpha=0.0013 mean_alpha=0.0410 median_alpha=0.0346 max_alpha=0.2810 beta=0.0041

22:45:32 - INFO - EM Iter  42: ll=-1835.3778 log_delta_p=-8.8721 log_delta_a=-12.8165 min_alpha=0.0012 mean_alpha=0.0409 median_alpha=0.0345 max_alpha=0.2809 beta=0.0042

22:45:33 - INFO - EM Iter  43: ll=-1835.3778 log_delta_p=-8.8581 log_delta_a=-12.8290 min_alpha=0.0012 mean_alpha=0.0408 median_alpha=0.0345 max_alpha=0.2809 beta=0.0042

22:45:33 - INFO - EM Iter  44: ll=-1835.3778 log_delta_p=-8.8583 log_delta_a=-12.6829 min_alpha=0.0011 mean_alpha=0.0408 median_alpha=0.0344 max_alpha=0.2808 beta=0.0043

22:45:33 - INFO - EM Iter  45: ll=-1835.3776 log_delta_p=-8.8692 log_delta_a=-12.6811 min_alpha=0.0010 mean_alpha=0.0407 median_alpha=0.0344 max_alpha=0.2808 beta=0.0043

22:45:33 - INFO - EM Iter  46: ll=-1835.3774 log_delta_p=-8.8892 log_delta_a=-12.6545 min_alpha=0.0010 mean_alpha=0.0407 median_alpha=0.0343 max_alpha=0.2807 beta=0.0044

22:45:33 - INFO - EM Iter  47: ll=-1835.3774 log_delta_p=-8.9179 log_delta_a=-12.5667 min_alpha=0.0009 mean_alpha=0.0406 median_alpha=0.0343 max_alpha=0.2807 beta=0.0044

22:45:33 - INFO - EM Iter  48: ll=-1835.3774 log_delta_p=-8.9490 log_delta_a=-12.5764 min_alpha=0.0009 mean_alpha=0.0405 median_alpha=0.0342 max_alpha=0.2807 beta=0.0045

22:45:33 - INFO - EM Iter  49: ll=-1835.3771 log_delta_p=-8.9800 log_delta_a=-12.5952 min_alpha=0.0008 mean_alpha=0.0405 median_alpha=0.0341 max_alpha=0.2806 beta=0.0045

22:45:33 - INFO - EM Iter  50: ll=-1835.3771 log_delta_p=-9.0079 log_delta_a=-12.6568 min_alpha=0.0008 mean_alpha=0.0404 median_alpha=0.0341 max_alpha=0.2806 beta=0.0046

22:45:33 - INFO - EM Iter  51: ll=-1835.3771 log_delta_p=-9.0298 log_delta_a=-12.6426 min_alpha=0.0007 mean_alpha=0.0404 median_alpha=0.0340 max_alpha=0.2805 beta=0.0046

22:45:33 - INFO - EM Iter  52: ll=-1835.3770 log_delta_p=-9.0416 log_delta_a=-12.6864 min_alpha=0.0007 mean_alpha=0.0403 median_alpha=0.0340 max_alpha=0.2805 beta=0.0047

22:45:33 - INFO - EM Iter  53: ll=-1835.3768 log_delta_p=-9.0456 log_delta_a=-12.5297 min_alpha=0.0006 mean_alpha=0.0403 median_alpha=0.0339 max_alpha=0.2805 beta=0.0048

22:45:33 - INFO - EM Iter  54: ll=-1835.3768 log_delta_p=-9.0424 log_delta_a=-12.5521 min_alpha=0.0006 mean_alpha=0.0402 median_alpha=0.0339 max_alpha=0.2804 beta=0.0048

22:45:33 - INFO - EM Iter  55: ll=-1835.3766 log_delta_p=-9.0410 log_delta_a=-12.5214 min_alpha=0.0005 mean_alpha=0.0402 median_alpha=0.0338 max_alpha=0.2804 beta=0.0049

22:45:33 - INFO - EM Iter  56: ll=-1835.3766 log_delta_p=-9.0461 log_delta_a=-12.5675 min_alpha=0.0005 mean_alpha=0.0401 median_alpha=0.0338 max_alpha=0.2803 beta=0.0049

22:45:33 - INFO - EM Iter  57: ll=-1835.3766 log_delta_p=-9.0591 log_delta_a=-12.5681 min_alpha=0.0005 mean_alpha=0.0401 median_alpha=0.0337 max_alpha=0.2803 beta=0.0050

22:45:33 - INFO - EM Iter  58: ll=-1835.3765 log_delta_p=-9.0826 log_delta_a=-12.5371 min_alpha=0.0004 mean_alpha=0.0400 median_alpha=0.0337 max_alpha=0.2803 beta=0.0050

22:45:33 - INFO - EM Iter  59: ll=-1835.3763 log_delta_p=-9.1159 log_delta_a=-12.5153 min_alpha=0.0004 mean_alpha=0.0400 median_alpha=0.0336 max_alpha=0.2802 beta=0.0050

22:45:33 - INFO - EM Iter  60: ll=-1835.3763 log_delta_p=-9.1578 log_delta_a=-12.5022 min_alpha=0.0004 mean_alpha=0.0399 median_alpha=0.0336 max_alpha=0.2802 beta=0.0051

22:45:33 - INFO - EM Iter  61: ll=-1835.3763 log_delta_p=-9.2073 log_delta_a=-12.5375 min_alpha=0.0004 mean_alpha=0.0399 median_alpha=0.0335 max_alpha=0.2802 beta=0.0051

22:45:33 - INFO - EM Iter  62: ll=-1835.3763 log_delta_p=-9.2644 log_delta_a=-12.5085 min_alpha=0.0003 mean_alpha=0.0398 median_alpha=0.0335 max_alpha=0.2801 beta=0.0052

22:45:33 - INFO - Converged.

22:45:33 - INFO - Saving inferred adata to '/home/mcaskey/cellsweep/notebooks/data/simulation1_small_noise/celltype_granularity/adata_cellsweep_truth.h5ad'

truth done

22:45:34 - INFO - Starting cellsweep denoising at 2026-10-03 22:45:34, cellsweep version 0.1.3

22:45:34 - INFO - Inferring celltype profiles.

22:45:34 - INFO - Number of celltypes: 24

22:45:34 - INFO - Inferring the ambient profile from empty droplets.

Logging to /home/mcaskey/cellsweep/notebooks/data/simulation1_small_noise/celltype_granularity/cellsweep_split_2.log

22:45:34 - INFO - adata.obs does not have 'init_alpha'. Setting to `init_alpha` argument.

22:45:34 - INFO - Performing Sparse EM with 32 Numba thread(s)

22:45:34 - INFO - EM Iter   1: ll=-1906.8280 log_delta_p=inf log_delta_a=inf min_alpha=0.3724 mean_alpha=0.5409 median_alpha=0.5452 max_alpha=0.6160 beta=0.0083

22:45:34 - INFO - EM Iter   2: ll=-1876.7827 log_delta_p=inf log_delta_a=inf min_alpha=0.2807 mean_alpha=0.4517 median_alpha=0.4533 max_alpha=0.5782 beta=0.0076

22:45:34 - INFO - EM Iter   3: ll=-1869.9670 log_delta_p=-1.9869 log_delta_a=-10.9955 min_alpha=0.2115 mean_alpha=0.3889 median_alpha=0.3894 max_alpha=0.5620 beta=0.0070

22:45:34 - INFO - EM Iter   4: ll=-1864.8358 log_delta_p=-2.1631 log_delta_a=-10.7415 min_alpha=0.1571 mean_alpha=0.3288 median_alpha=0.3280 max_alpha=0.5378 beta=0.0064

22:45:34 - INFO - EM Iter   5: ll=-1859.9674 log_delta_p=-2.3741 log_delta_a=-11.0464 min_alpha=0.1096 mean_alpha=0.2719 median_alpha=0.2701 max_alpha=0.5078 beta=0.0058

22:45:34 - INFO - EM Iter   6: ll=-1855.6293 log_delta_p=-2.5920 log_delta_a=-10.9836 min_alpha=0.0729 mean_alpha=0.2210 median_alpha=0.2179 max_alpha=0.4758 beta=0.0052

22:45:34 - INFO - EM Iter   7: ll=-1852.0243 log_delta_p=-2.8269 log_delta_a=-10.9123 min_alpha=0.0486 mean_alpha=0.1782 median_alpha=0.1739 max_alpha=0.4444 beta=0.0046

22:45:34 - INFO - EM Iter   8: ll=-1849.2162 log_delta_p=-3.0983 log_delta_a=-10.9237 min_alpha=0.0332 mean_alpha=0.1437 median_alpha=0.1387 max_alpha=0.4156 beta=0.0041

22:45:35 - INFO - EM Iter   9: ll=-1847.1491 log_delta_p=-3.3941 log_delta_a=-10.9695 min_alpha=0.0237 mean_alpha=0.1170 median_alpha=0.1115 max_alpha=0.3902 beta=0.0036

22:45:35 - INFO - EM Iter  10: ll=-1845.7008 log_delta_p=-3.7057 log_delta_a=-11.1078 min_alpha=0.0180 mean_alpha=0.0968 median_alpha=0.0910 max_alpha=0.3687 beta=0.0033

22:45:35 - INFO - EM Iter  11: ll=-1844.7285 log_delta_p=-4.0271 log_delta_a=-11.2755 min_alpha=0.0146 mean_alpha=0.0818 median_alpha=0.0757 max_alpha=0.3508 beta=0.0030

22:45:35 - INFO - EM Iter  12: ll=-1844.1000 log_delta_p=-4.3542 log_delta_a=-11.5099 min_alpha=0.0125 mean_alpha=0.0709 median_alpha=0.0648 max_alpha=0.3363 beta=0.0029

22:45:35 - INFO - EM Iter  13: ll=-1843.7067 log_delta_p=-4.6847 log_delta_a=-11.6880 min_alpha=0.0111 mean_alpha=0.0629 median_alpha=0.0568 max_alpha=0.3247 beta=0.0028

22:45:35 - INFO - EM Iter  14: ll=-1843.4670 log_delta_p=-5.0169 log_delta_a=-11.9608 min_alpha=0.0098 mean_alpha=0.0572 median_alpha=0.0510 max_alpha=0.3156 beta=0.0027

22:45:35 - INFO - EM Iter  15: ll=-1843.3242 log_delta_p=-5.3493 log_delta_a=-12.3226 min_alpha=0.0090 mean_alpha=0.0531 median_alpha=0.0468 max_alpha=0.3085 beta=0.0027

22:45:35 - INFO - EM Iter  16: ll=-1843.2402 log_delta_p=-5.6811 log_delta_a=-12.7030 min_alpha=0.0083 mean_alpha=0.0501 median_alpha=0.0438 max_alpha=0.3029 beta=0.0027

22:45:35 - INFO - EM Iter  17: ll=-1843.1909 log_delta_p=-6.0117 log_delta_a=-12.5890 min_alpha=0.0074 mean_alpha=0.0479 median_alpha=0.0415 max_alpha=0.2986 beta=0.0027

22:45:35 - INFO - EM Iter  18: ll=-1843.1624 log_delta_p=-6.3406 log_delta_a=-12.5878 min_alpha=0.0063 mean_alpha=0.0464 median_alpha=0.0399 max_alpha=0.2954 beta=0.0028

22:45:35 - INFO - EM Iter  19: ll=-1843.1451 log_delta_p=-6.6678 log_delta_a=-12.5939 min_alpha=0.0055 mean_alpha=0.0452 median_alpha=0.0387 max_alpha=0.2928 beta=0.0029

22:45:35 - INFO - EM Iter  20: ll=-1835.2670 log_delta_p=-6.9929 log_delta_a=-12.4448 min_alpha=0.0049 mean_alpha=0.0443 median_alpha=0.0379 max_alpha=0.2909 beta=0.0029

22:45:35 - INFO - EM Iter  21: ll=-1835.2606 log_delta_p=-7.3046 log_delta_a=-11.8962 min_alpha=0.0044 mean_alpha=0.0437 median_alpha=0.0372 max_alpha=0.2894 beta=0.0029

22:45:35 - INFO - EM Iter  22: ll=-1835.2568 log_delta_p=-7.2972 log_delta_a=-12.6756 min_alpha=0.0040 mean_alpha=0.0432 median_alpha=0.0368 max_alpha=0.2883 beta=0.0030

22:45:35 - INFO - EM Iter  23: ll=-1835.2546 log_delta_p=-7.3742 log_delta_a=-12.6355 min_alpha=0.0037 mean_alpha=0.0428 median_alpha=0.0364 max_alpha=0.2874 beta=0.0030

22:45:35 - INFO - EM Iter  24: ll=-1835.2525 log_delta_p=-7.4704 log_delta_a=-12.5388 min_alpha=0.0035 mean_alpha=0.0425 median_alpha=0.0361 max_alpha=0.2868 beta=0.0031

22:45:35 - INFO - EM Iter  25: ll=-1835.2515 log_delta_p=-7.5103 log_delta_a=-12.5427 min_alpha=0.0033 mean_alpha=0.0423 median_alpha=0.0359 max_alpha=0.2862 beta=0.0031

22:45:35 - INFO - EM Iter  26: ll=-1835.2504 log_delta_p=-7.5260 log_delta_a=-12.5420 min_alpha=0.0031 mean_alpha=0.0421 median_alpha=0.0357 max_alpha=0.2859 beta=0.0032

22:45:35 - INFO - EM Iter  27: ll=-1835.2496 log_delta_p=-7.5716 log_delta_a=-12.6684 min_alpha=0.0029 mean_alpha=0.0419 median_alpha=0.0356 max_alpha=0.2855 beta=0.0033

22:45:35 - INFO - EM Iter  28: ll=-1835.2490 log_delta_p=-7.6283 log_delta_a=-12.7545 min_alpha=0.0027 mean_alpha=0.0418 median_alpha=0.0354 max_alpha=0.2853 beta=0.0033

22:45:35 - INFO - EM Iter  29: ll=-1835.2483 log_delta_p=-7.6893 log_delta_a=-12.9518 min_alpha=0.0026 mean_alpha=0.0417 median_alpha=0.0354 max_alpha=0.2851 beta=0.0034

22:45:35 - INFO - EM Iter  30: ll=-1835.2477 log_delta_p=-7.7497 log_delta_a=-13.1246 min_alpha=0.0023 mean_alpha=0.0416 median_alpha=0.0353 max_alpha=0.2850 beta=0.0034

22:45:35 - INFO - EM Iter  31: ll=-1835.2472 log_delta_p=-7.8082 log_delta_a=-13.2595 min_alpha=0.0020 mean_alpha=0.0415 median_alpha=0.0352 max_alpha=0.2848 beta=0.0035

22:45:35 - INFO - EM Iter  32: ll=-1835.2467 log_delta_p=-7.8676 log_delta_a=-13.0727 min_alpha=0.0017 mean_alpha=0.0414 median_alpha=0.0351 max_alpha=0.2847 beta=0.0036

22:45:35 - INFO - EM Iter  33: ll=-1835.2466 log_delta_p=-7.9283 log_delta_a=-13.2358 min_alpha=0.0015 mean_alpha=0.0413 median_alpha=0.0350 max_alpha=0.2846 beta=0.0036

22:45:35 - INFO - EM Iter  34: ll=-1835.2461 log_delta_p=-7.9878 log_delta_a=-13.1895 min_alpha=0.0013 mean_alpha=0.0412 median_alpha=0.0349 max_alpha=0.2845 beta=0.0037

22:45:35 - INFO - EM Iter  35: ll=-1835.2459 log_delta_p=-8.0371 log_delta_a=-13.3379 min_alpha=0.0011 mean_alpha=0.0412 median_alpha=0.0349 max_alpha=0.2845 beta=0.0038

22:45:35 - INFO - EM Iter  36: ll=-1835.2456 log_delta_p=-8.0723 log_delta_a=-13.0438 min_alpha=0.0009 mean_alpha=0.0411 median_alpha=0.0348 max_alpha=0.2844 beta=0.0038

22:45:35 - INFO - EM Iter  37: ll=-1835.2451 log_delta_p=-8.0907 log_delta_a=-13.0885 min_alpha=0.0007 mean_alpha=0.0410 median_alpha=0.0347 max_alpha=0.2843 beta=0.0039

22:45:35 - INFO - EM Iter  38: ll=-1835.2448 log_delta_p=-8.0964 log_delta_a=-13.0305 min_alpha=0.0006 mean_alpha=0.0409 median_alpha=0.0347 max_alpha=0.2843 beta=0.0039

22:45:35 - INFO - EM Iter  39: ll=-1835.2445 log_delta_p=-8.0958 log_delta_a=-12.9910 min_alpha=0.0005 mean_alpha=0.0409 median_alpha=0.0346 max_alpha=0.2842 beta=0.0040

22:45:35 - INFO - EM Iter  40: ll=-1835.2445 log_delta_p=-8.1006 log_delta_a=-12.7424 min_alpha=0.0004 mean_alpha=0.0408 median_alpha=0.0345 max_alpha=0.2842 beta=0.0040

22:45:35 - INFO - EM Iter  41: ll=-1835.2442 log_delta_p=-8.1124 log_delta_a=-12.9116 min_alpha=0.0003 mean_alpha=0.0407 median_alpha=0.0345 max_alpha=0.2841 beta=0.0041

22:45:35 - INFO - EM Iter  42: ll=-1835.2440 log_delta_p=-8.1313 log_delta_a=-12.7930 min_alpha=0.0003 mean_alpha=0.0407 median_alpha=0.0344 max_alpha=0.2841 beta=0.0042

22:45:35 - INFO - EM Iter  43: ll=-1835.2440 log_delta_p=-8.1567 log_delta_a=-12.8099 min_alpha=0.0002 mean_alpha=0.0406 median_alpha=0.0343 max_alpha=0.2841 beta=0.0042

22:45:35 - INFO - EM Iter  44: ll=-1835.2437 log_delta_p=-8.1894 log_delta_a=-12.6392 min_alpha=0.0002 mean_alpha=0.0405 median_alpha=0.0343 max_alpha=0.2840 beta=0.0043

22:45:35 - INFO - EM Iter  45: ll=-1835.2434 log_delta_p=-8.2280 log_delta_a=-12.6679 min_alpha=0.0001 mean_alpha=0.0405 median_alpha=0.0342 max_alpha=0.2840 beta=0.0043

22:45:35 - INFO - EM Iter  46: ll=-1835.2434 log_delta_p=-8.2718 log_delta_a=-12.6907 min_alpha=0.0001 mean_alpha=0.0404 median_alpha=0.0341 max_alpha=0.2839 beta=0.0044

22:45:35 - INFO - EM Iter  47: ll=-1835.2429 log_delta_p=-8.3152 log_delta_a=-12.5969 min_alpha=0.0001 mean_alpha=0.0403 median_alpha=0.0341 max_alpha=0.2839 beta=0.0044

22:45:35 - INFO - EM Iter  48: ll=-1835.2427 log_delta_p=-8.3585 log_delta_a=-12.5658 min_alpha=0.0001 mean_alpha=0.0403 median_alpha=0.0340 max_alpha=0.2838 beta=0.0045

22:45:36 - INFO - EM Iter  49: ll=-1835.2427 log_delta_p=-8.3969 log_delta_a=-12.6041 min_alpha=0.0001 mean_alpha=0.0402 median_alpha=0.0339 max_alpha=0.2838 beta=0.0045

22:45:36 - INFO - EM Iter  50: ll=-1835.2427 log_delta_p=-8.4314 log_delta_a=-12.6327 min_alpha=0.0000 mean_alpha=0.0402 median_alpha=0.0339 max_alpha=0.2838 beta=0.0046

22:45:36 - INFO - EM Iter  51: ll=-1835.2424 log_delta_p=-8.4585 log_delta_a=-12.6296 min_alpha=0.0000 mean_alpha=0.0401 median_alpha=0.0338 max_alpha=0.2837 beta=0.0046

22:45:36 - INFO - EM Iter  52: ll=-1835.2424 log_delta_p=-8.4788 log_delta_a=-12.7466 min_alpha=0.0000 mean_alpha=0.0400 median_alpha=0.0337 max_alpha=0.2837 beta=0.0047

22:45:36 - INFO - EM Iter  53: ll=-1835.2422 log_delta_p=-8.4983 log_delta_a=-12.5409 min_alpha=0.0000 mean_alpha=0.0400 median_alpha=0.0337 max_alpha=0.2836 beta=0.0048

22:45:36 - INFO - EM Iter  54: ll=-1835.2421 log_delta_p=-8.5192 log_delta_a=-12.5979 min_alpha=0.0000 mean_alpha=0.0399 median_alpha=0.0336 max_alpha=0.2836 beta=0.0048

22:45:36 - INFO - EM Iter  55: ll=-1835.2419 log_delta_p=-8.5426 log_delta_a=-12.5772 min_alpha=0.0000 mean_alpha=0.0399 median_alpha=0.0336 max_alpha=0.2836 beta=0.0049

22:45:36 - INFO - EM Iter  56: ll=-1835.2418 log_delta_p=-8.5707 log_delta_a=-12.5522 min_alpha=0.0000 mean_alpha=0.0398 median_alpha=0.0335 max_alpha=0.2835 beta=0.0049

22:45:36 - INFO - EM Iter  57: ll=-1835.2418 log_delta_p=-8.6031 log_delta_a=-12.5877 min_alpha=0.0000 mean_alpha=0.0398 median_alpha=0.0335 max_alpha=0.2835 beta=0.0050

22:45:36 - INFO - EM Iter  58: ll=-1835.2416 log_delta_p=-8.6396 log_delta_a=-12.4710 min_alpha=0.0000 mean_alpha=0.0397 median_alpha=0.0334 max_alpha=0.2835 beta=0.0050

22:45:36 - INFO - EM Iter  59: ll=-1835.2414 log_delta_p=-8.6795 log_delta_a=-12.5848 min_alpha=0.0000 mean_alpha=0.0397 median_alpha=0.0334 max_alpha=0.2834 beta=0.0051

22:45:36 - INFO - EM Iter  60: ll=-1835.2414 log_delta_p=-8.7189 log_delta_a=-12.5189 min_alpha=0.0000 mean_alpha=0.0396 median_alpha=0.0333 max_alpha=0.2834 beta=0.0051

22:45:36 - INFO - EM Iter  61: ll=-1835.2411 log_delta_p=-8.7560 log_delta_a=-12.5408 min_alpha=0.0000 mean_alpha=0.0396 median_alpha=0.0333 max_alpha=0.2833 beta=0.0051

22:45:36 - INFO - EM Iter  62: ll=-1835.2411 log_delta_p=-8.7914 log_delta_a=-12.5299 min_alpha=0.0000 mean_alpha=0.0395 median_alpha=0.0332 max_alpha=0.2833 beta=0.0052

22:45:36 - INFO - EM Iter  63: ll=-1835.2411 log_delta_p=-8.8237 log_delta_a=-12.4781 min_alpha=0.0000 mean_alpha=0.0395 median_alpha=0.0332 max_alpha=0.2833 beta=0.0052

22:45:36 - INFO - EM Iter  64: ll=-1835.2410 log_delta_p=-8.8550 log_delta_a=-12.5524 min_alpha=0.0000 mean_alpha=0.0394 median_alpha=0.0331 max_alpha=0.2832 beta=0.0053

22:45:36 - INFO - EM Iter  65: ll=-1835.2408 log_delta_p=-8.8873 log_delta_a=-12.5330 min_alpha=0.0000 mean_alpha=0.0394 median_alpha=0.0331 max_alpha=0.2832 beta=0.0053

22:45:36 - INFO - EM Iter  66: ll=-1835.2408 log_delta_p=-8.9231 log_delta_a=-12.5818 min_alpha=0.0000 mean_alpha=0.0393 median_alpha=0.0330 max_alpha=0.2832 beta=0.0054

22:45:36 - INFO - EM Iter  67: ll=-1835.2408 log_delta_p=-8.9631 log_delta_a=-12.5371 min_alpha=0.0000 mean_alpha=0.0393 median_alpha=0.0330 max_alpha=0.2831 beta=0.0054

22:45:36 - INFO - EM Iter  68: ll=-1835.2408 log_delta_p=-9.0072 log_delta_a=-12.6001 min_alpha=0.0000 mean_alpha=0.0392 median_alpha=0.0329 max_alpha=0.2831 beta=0.0055

22:45:36 - INFO - EM Iter  69: ll=-1835.2408 log_delta_p=-9.0519 log_delta_a=-12.5495 min_alpha=0.0000 mean_alpha=0.0392 median_alpha=0.0329 max_alpha=0.2831 beta=0.0055

22:45:36 - INFO - EM Iter  70: ll=-1835.2405 log_delta_p=-9.0938 log_delta_a=-12.5491 min_alpha=0.0000 mean_alpha=0.0391 median_alpha=0.0328 max_alpha=0.2830 beta=0.0056

22:45:36 - INFO - EM Iter  71: ll=-1835.2405 log_delta_p=-9.1327 log_delta_a=-12.5816 min_alpha=0.0000 mean_alpha=0.0391 median_alpha=0.0328 max_alpha=0.2830 beta=0.0056

22:45:36 - INFO - EM Iter  72: ll=-1835.2405 log_delta_p=-9.1636 log_delta_a=-12.6076 min_alpha=0.0000 mean_alpha=0.0390 median_alpha=0.0327 max_alpha=0.2830 beta=0.0056

22:45:36 - INFO - EM Iter  73: ll=-1835.2403 log_delta_p=-9.1929 log_delta_a=-12.5303 min_alpha=0.0000 mean_alpha=0.0390 median_alpha=0.0327 max_alpha=0.2829 beta=0.0057

22:45:36 - INFO - EM Iter  74: ll=-1835.2403 log_delta_p=-9.2199 log_delta_a=-12.5973 min_alpha=0.0000 mean_alpha=0.0389 median_alpha=0.0326 max_alpha=0.2829 beta=0.0057

22:45:36 - INFO - Converged.

22:45:37 - INFO - Saving inferred adata to '/home/mcaskey/cellsweep/notebooks/data/simulation1_small_noise/celltype_granularity/adata_cellsweep_split_2.h5ad'

split_2 done

22:45:37 - INFO - Starting cellsweep denoising at 2026-10-03 22:45:37, cellsweep version 0.1.3

22:45:37 - INFO - Inferring celltype profiles.

22:45:37 - INFO - Number of celltypes: 48

22:45:37 - INFO - Inferring the ambient profile from empty droplets.

Logging to /home/mcaskey/cellsweep/notebooks/data/simulation1_small_noise/celltype_granularity/cellsweep_split_4.log

22:45:37 - INFO - adata.obs does not have 'init_alpha'. Setting to `init_alpha` argument.

22:45:37 - INFO - Performing Sparse EM with 32 Numba thread(s)

22:45:37 - INFO - EM Iter   1: ll=-1906.6806 log_delta_p=inf log_delta_a=inf min_alpha=0.3702 mean_alpha=0.5407 median_alpha=0.5450 max_alpha=0.6168 beta=0.0083

22:45:37 - INFO - EM Iter   2: ll=-1876.5627 log_delta_p=inf log_delta_a=inf min_alpha=0.2788 mean_alpha=0.4513 median_alpha=0.4531 max_alpha=0.5790 beta=0.0076

22:45:37 - INFO - EM Iter   3: ll=-1869.6982 log_delta_p=-1.9020 log_delta_a=-10.9687 min_alpha=0.2107 mean_alpha=0.3885 median_alpha=0.3888 max_alpha=0.5629 beta=0.0070

22:45:38 - INFO - EM Iter   4: ll=-1864.5637 log_delta_p=-2.1612 log_delta_a=-10.7446 min_alpha=0.1568 mean_alpha=0.3285 median_alpha=0.3278 max_alpha=0.5374 beta=0.0064

22:45:38 - INFO - EM Iter   5: ll=-1859.7130 log_delta_p=-2.3751 log_delta_a=-11.0486 min_alpha=0.1056 mean_alpha=0.2718 median_alpha=0.2702 max_alpha=0.5043 beta=0.0058

22:45:38 - INFO - EM Iter   6: ll=-1855.3902 log_delta_p=-2.5953 log_delta_a=-10.9687 min_alpha=0.0698 mean_alpha=0.2211 median_alpha=0.2180 max_alpha=0.4677 beta=0.0052

22:45:38 - INFO - EM Iter   7: ll=-1851.7931 log_delta_p=-2.8349 log_delta_a=-10.9209 min_alpha=0.0463 mean_alpha=0.1784 median_alpha=0.1741 max_alpha=0.4361 beta=0.0046

22:45:38 - INFO - EM Iter   8: ll=-1848.9870 log_delta_p=-3.1062 log_delta_a=-10.9198 min_alpha=0.0315 mean_alpha=0.1439 median_alpha=0.1388 max_alpha=0.4073 beta=0.0041

22:45:38 - INFO - EM Iter   9: ll=-1846.9195 log_delta_p=-3.4017 log_delta_a=-10.9751 min_alpha=0.0226 mean_alpha=0.1171 median_alpha=0.1116 max_alpha=0.3822 beta=0.0036

22:45:38 - INFO - EM Iter  10: ll=-1845.4699 log_delta_p=-3.7125 log_delta_a=-11.1126 min_alpha=0.0172 mean_alpha=0.0969 median_alpha=0.0909 max_alpha=0.3610 beta=0.0033

22:45:38 - INFO - EM Iter  11: ll=-1844.4962 log_delta_p=-4.0333 log_delta_a=-11.2816 min_alpha=0.0140 mean_alpha=0.0819 median_alpha=0.0758 max_alpha=0.3435 beta=0.0030

22:45:38 - INFO - EM Iter  12: ll=-1843.8661 log_delta_p=-4.3600 log_delta_a=-11.5043 min_alpha=0.0121 mean_alpha=0.0710 median_alpha=0.0648 max_alpha=0.3294 beta=0.0029

22:45:38 - INFO - EM Iter  13: ll=-1843.4712 log_delta_p=-4.6896 log_delta_a=-11.7134 min_alpha=0.0108 mean_alpha=0.0630 median_alpha=0.0569 max_alpha=0.3182 beta=0.0028

22:45:38 - INFO - EM Iter  14: ll=-1843.2299 log_delta_p=-5.0203 log_delta_a=-11.9688 min_alpha=0.0096 mean_alpha=0.0573 median_alpha=0.0510 max_alpha=0.3093 beta=0.0027

22:45:38 - INFO - EM Iter  15: ll=-1843.0856 log_delta_p=-5.3514 log_delta_a=-12.2979 min_alpha=0.0087 mean_alpha=0.0531 median_alpha=0.0468 max_alpha=0.3025 beta=0.0027

22:45:38 - INFO - EM Iter  16: ll=-1843.0000 log_delta_p=-5.6824 log_delta_a=-12.6840 min_alpha=0.0076 mean_alpha=0.0501 median_alpha=0.0438 max_alpha=0.2972 beta=0.0027

22:45:38 - INFO - EM Iter  17: ll=-1842.9498 log_delta_p=-6.0120 log_delta_a=-12.5706 min_alpha=0.0067 mean_alpha=0.0479 median_alpha=0.0415 max_alpha=0.2931 beta=0.0027

22:45:38 - INFO - EM Iter  18: ll=-1842.9197 log_delta_p=-6.3394 log_delta_a=-12.5596 min_alpha=0.0059 mean_alpha=0.0463 median_alpha=0.0398 max_alpha=0.2900 beta=0.0028

22:45:38 - INFO - EM Iter  19: ll=-1842.9014 log_delta_p=-6.4659 log_delta_a=-12.5394 min_alpha=0.0047 mean_alpha=0.0451 median_alpha=0.0386 max_alpha=0.2876 beta=0.0029

22:45:38 - INFO - EM Iter  20: ll=-1835.0219 log_delta_p=-6.4975 log_delta_a=-12.4748 min_alpha=0.0036 mean_alpha=0.0442 median_alpha=0.0377 max_alpha=0.2857 beta=0.0029

22:45:38 - INFO - EM Iter  21: ll=-1835.0149 log_delta_p=-6.5512 log_delta_a=-11.9148 min_alpha=0.0027 mean_alpha=0.0436 median_alpha=0.0371 max_alpha=0.2843 beta=0.0029

22:45:38 - INFO - EM Iter  22: ll=-1835.0098 log_delta_p=-6.6148 log_delta_a=-12.7628 min_alpha=0.0020 mean_alpha=0.0430 median_alpha=0.0366 max_alpha=0.2833 beta=0.0030

22:45:38 - INFO - EM Iter  23: ll=-1835.0066 log_delta_p=-6.6777 log_delta_a=-12.6936 min_alpha=0.0014 mean_alpha=0.0427 median_alpha=0.0363 max_alpha=0.2824 beta=0.0030

22:45:38 - INFO - EM Iter  24: ll=-1835.0043 log_delta_p=-6.7336 log_delta_a=-12.6344 min_alpha=0.0010 mean_alpha=0.0424 median_alpha=0.0359 max_alpha=0.2818 beta=0.0031

22:45:38 - INFO - EM Iter  25: ll=-1835.0024 log_delta_p=-6.7538 log_delta_a=-12.5253 min_alpha=0.0007 mean_alpha=0.0421 median_alpha=0.0358 max_alpha=0.2813 beta=0.0031

22:45:38 - INFO - EM Iter  26: ll=-1835.0010 log_delta_p=-6.7918 log_delta_a=-12.5466 min_alpha=0.0005 mean_alpha=0.0419 median_alpha=0.0356 max_alpha=0.2810 beta=0.0032

22:45:38 - INFO - EM Iter  27: ll=-1834.9997 log_delta_p=-6.8525 log_delta_a=-12.6629 min_alpha=0.0004 mean_alpha=0.0417 median_alpha=0.0354 max_alpha=0.2807 beta=0.0033

22:45:38 - INFO - EM Iter  28: ll=-1834.9984 log_delta_p=-6.9275 log_delta_a=-12.6023 min_alpha=0.0003 mean_alpha=0.0416 median_alpha=0.0353 max_alpha=0.2804 beta=0.0033

22:45:38 - INFO - EM Iter  29: ll=-1834.9974 log_delta_p=-7.0028 log_delta_a=-12.8949 min_alpha=0.0002 mean_alpha=0.0414 median_alpha=0.0352 max_alpha=0.2802 beta=0.0034

22:45:38 - INFO - EM Iter  30: ll=-1834.9968 log_delta_p=-7.0615 log_delta_a=-13.0671 min_alpha=0.0001 mean_alpha=0.0413 median_alpha=0.0350 max_alpha=0.2801 beta=0.0034

22:45:38 - INFO - EM Iter  31: ll=-1834.9958 log_delta_p=-7.0981 log_delta_a=-13.1384 min_alpha=0.0001 mean_alpha=0.0412 median_alpha=0.0349 max_alpha=0.2799 beta=0.0035

22:45:38 - INFO - EM Iter  32: ll=-1834.9950 log_delta_p=-7.1241 log_delta_a=-13.0226 min_alpha=0.0001 mean_alpha=0.0411 median_alpha=0.0349 max_alpha=0.2798 beta=0.0036

22:45:39 - INFO - EM Iter  33: ll=-1834.9944 log_delta_p=-7.1543 log_delta_a=-13.3287 min_alpha=0.0000 mean_alpha=0.0410 median_alpha=0.0348 max_alpha=0.2797 beta=0.0036

22:45:39 - INFO - EM Iter  34: ll=-1834.9939 log_delta_p=-7.1911 log_delta_a=-13.1471 min_alpha=0.0000 mean_alpha=0.0409 median_alpha=0.0347 max_alpha=0.2796 beta=0.0037

22:45:39 - INFO - EM Iter  35: ll=-1834.9934 log_delta_p=-7.2266 log_delta_a=-13.2555 min_alpha=0.0000 mean_alpha=0.0408 median_alpha=0.0346 max_alpha=0.2795 beta=0.0037

22:45:39 - INFO - EM Iter  36: ll=-1834.9930 log_delta_p=-7.2494 log_delta_a=-12.8715 min_alpha=0.0000 mean_alpha=0.0407 median_alpha=0.0345 max_alpha=0.2794 beta=0.0038

22:45:39 - INFO - EM Iter  37: ll=-1834.9922 log_delta_p=-7.2545 log_delta_a=-13.0378 min_alpha=0.0000 mean_alpha=0.0407 median_alpha=0.0345 max_alpha=0.2794 beta=0.0039

22:45:39 - INFO - EM Iter  38: ll=-1834.9917 log_delta_p=-7.2530 log_delta_a=-12.8571 min_alpha=0.0000 mean_alpha=0.0406 median_alpha=0.0344 max_alpha=0.2793 beta=0.0039

22:45:39 - INFO - EM Iter  39: ll=-1834.9912 log_delta_p=-7.2614 log_delta_a=-12.9782 min_alpha=0.0000 mean_alpha=0.0405 median_alpha=0.0343 max_alpha=0.2792 beta=0.0040

22:45:39 - INFO - EM Iter  40: ll=-1834.9909 log_delta_p=-7.2887 log_delta_a=-12.7165 min_alpha=0.0000 mean_alpha=0.0404 median_alpha=0.0342 max_alpha=0.2792 beta=0.0040

22:45:39 - INFO - EM Iter  41: ll=-1834.9904 log_delta_p=-7.3306 log_delta_a=-12.8454 min_alpha=0.0000 mean_alpha=0.0404 median_alpha=0.0342 max_alpha=0.2791 beta=0.0041

22:45:39 - INFO - EM Iter  42: ll=-1834.9901 log_delta_p=-7.3803 log_delta_a=-12.7372 min_alpha=0.0000 mean_alpha=0.0403 median_alpha=0.0341 max_alpha=0.2791 beta=0.0041

22:45:39 - INFO - EM Iter  43: ll=-1834.9894 log_delta_p=-7.4316 log_delta_a=-12.7157 min_alpha=0.0000 mean_alpha=0.0402 median_alpha=0.0340 max_alpha=0.2790 beta=0.0042

22:45:39 - INFO - EM Iter  44: ll=-1834.9893 log_delta_p=-7.4839 log_delta_a=-12.5987 min_alpha=0.0000 mean_alpha=0.0401 median_alpha=0.0339 max_alpha=0.2790 beta=0.0043

22:45:39 - INFO - EM Iter  45: ll=-1834.9890 log_delta_p=-7.5305 log_delta_a=-12.6983 min_alpha=0.0000 mean_alpha=0.0401 median_alpha=0.0339 max_alpha=0.2789 beta=0.0043

22:45:39 - INFO - EM Iter  46: ll=-1834.9888 log_delta_p=-7.5700 log_delta_a=-12.6521 min_alpha=0.0000 mean_alpha=0.0400 median_alpha=0.0338 max_alpha=0.2789 beta=0.0044

22:45:39 - INFO - EM Iter  47: ll=-1834.9885 log_delta_p=-7.6036 log_delta_a=-12.6243 min_alpha=0.0000 mean_alpha=0.0399 median_alpha=0.0338 max_alpha=0.2788 beta=0.0044

22:45:39 - INFO - EM Iter  48: ll=-1834.9880 log_delta_p=-7.6357 log_delta_a=-12.6747 min_alpha=0.0000 mean_alpha=0.0399 median_alpha=0.0337 max_alpha=0.2788 beta=0.0045

22:45:39 - INFO - EM Iter  49: ll=-1834.9875 log_delta_p=-7.6665 log_delta_a=-12.5911 min_alpha=0.0000 mean_alpha=0.0398 median_alpha=0.0336 max_alpha=0.2788 beta=0.0045

22:45:39 - INFO - EM Iter  50: ll=-1834.9872 log_delta_p=-7.6973 log_delta_a=-12.6106 min_alpha=0.0000 mean_alpha=0.0397 median_alpha=0.0336 max_alpha=0.2787 beta=0.0046

22:45:39 - INFO - EM Iter  51: ll=-1834.9872 log_delta_p=-7.7277 log_delta_a=-12.6272 min_alpha=0.0000 mean_alpha=0.0397 median_alpha=0.0335 max_alpha=0.2787 beta=0.0046

22:45:39 - INFO - EM Iter  52: ll=-1834.9869 log_delta_p=-7.7599 log_delta_a=-12.6229 min_alpha=0.0000 mean_alpha=0.0396 median_alpha=0.0334 max_alpha=0.2786 beta=0.0047

22:45:39 - INFO - EM Iter  53: ll=-1834.9867 log_delta_p=-7.7977 log_delta_a=-12.4952 min_alpha=0.0000 mean_alpha=0.0396 median_alpha=0.0334 max_alpha=0.2786 beta=0.0047

22:45:39 - INFO - EM Iter  54: ll=-1834.9867 log_delta_p=-7.8428 log_delta_a=-12.5604 min_alpha=0.0000 mean_alpha=0.0395 median_alpha=0.0333 max_alpha=0.2786 beta=0.0048

22:45:39 - INFO - EM Iter  55: ll=-1834.9866 log_delta_p=-7.8975 log_delta_a=-12.6019 min_alpha=0.0000 mean_alpha=0.0394 median_alpha=0.0332 max_alpha=0.2785 beta=0.0048

22:45:39 - INFO - EM Iter  56: ll=-1834.9861 log_delta_p=-7.9621 log_delta_a=-12.5993 min_alpha=0.0000 mean_alpha=0.0394 median_alpha=0.0332 max_alpha=0.2785 beta=0.0049

22:45:39 - INFO - EM Iter  57: ll=-1834.9861 log_delta_p=-8.0342 log_delta_a=-12.5125 min_alpha=0.0000 mean_alpha=0.0393 median_alpha=0.0331 max_alpha=0.2784 beta=0.0049

22:45:39 - INFO - EM Iter  58: ll=-1834.9858 log_delta_p=-8.1116 log_delta_a=-12.5299 min_alpha=0.0000 mean_alpha=0.0393 median_alpha=0.0331 max_alpha=0.2784 beta=0.0050

22:45:39 - INFO - EM Iter  59: ll=-1834.9856 log_delta_p=-8.1916 log_delta_a=-12.5488 min_alpha=0.0000 mean_alpha=0.0392 median_alpha=0.0330 max_alpha=0.2784 beta=0.0050

22:45:39 - INFO - EM Iter  60: ll=-1834.9856 log_delta_p=-8.2711 log_delta_a=-12.5329 min_alpha=0.0000 mean_alpha=0.0392 median_alpha=0.0330 max_alpha=0.2783 beta=0.0051

22:45:39 - INFO - EM Iter  61: ll=-1834.9853 log_delta_p=-8.3493 log_delta_a=-12.5524 min_alpha=0.0000 mean_alpha=0.0391 median_alpha=0.0329 max_alpha=0.2783 beta=0.0051

22:45:39 - INFO - EM Iter  62: ll=-1834.9851 log_delta_p=-8.4260 log_delta_a=-12.5447 min_alpha=0.0000 mean_alpha=0.0390 median_alpha=0.0328 max_alpha=0.2783 beta=0.0052

22:45:39 - INFO - EM Iter  63: ll=-1834.9851 log_delta_p=-8.4986 log_delta_a=-12.5310 min_alpha=0.0000 mean_alpha=0.0390 median_alpha=0.0328 max_alpha=0.2782 beta=0.0052

22:45:40 - INFO - EM Iter  64: ll=-1834.9850 log_delta_p=-8.5683 log_delta_a=-12.5756 min_alpha=0.0000 mean_alpha=0.0389 median_alpha=0.0327 max_alpha=0.2782 beta=0.0053

22:45:40 - INFO - EM Iter  65: ll=-1834.9848 log_delta_p=-8.6373 log_delta_a=-12.6662 min_alpha=0.0000 mean_alpha=0.0389 median_alpha=0.0327 max_alpha=0.2781 beta=0.0053

22:45:40 - INFO - EM Iter  66: ll=-1834.9846 log_delta_p=-8.7085 log_delta_a=-12.5994 min_alpha=0.0000 mean_alpha=0.0388 median_alpha=0.0326 max_alpha=0.2781 beta=0.0053

22:45:40 - INFO - EM Iter  67: ll=-1834.9845 log_delta_p=-8.7829 log_delta_a=-12.5927 min_alpha=0.0000 mean_alpha=0.0388 median_alpha=0.0326 max_alpha=0.2781 beta=0.0054

22:45:40 - INFO - EM Iter  68: ll=-1834.9842 log_delta_p=-8.8594 log_delta_a=-12.5626 min_alpha=0.0000 mean_alpha=0.0387 median_alpha=0.0325 max_alpha=0.2780 beta=0.0054

22:45:40 - INFO - EM Iter  69: ll=-1834.9842 log_delta_p=-8.9363 log_delta_a=-12.5367 min_alpha=0.0000 mean_alpha=0.0387 median_alpha=0.0325 max_alpha=0.2780 beta=0.0055

22:45:40 - INFO - EM Iter  70: ll=-1834.9840 log_delta_p=-9.0141 log_delta_a=-12.5814 min_alpha=0.0000 mean_alpha=0.0386 median_alpha=0.0324 max_alpha=0.2780 beta=0.0055

22:45:40 - INFO - EM Iter  71: ll=-1834.9840 log_delta_p=-9.0907 log_delta_a=-12.5493 min_alpha=0.0000 mean_alpha=0.0386 median_alpha=0.0324 max_alpha=0.2779 beta=0.0056

22:45:40 - INFO - EM Iter  72: ll=-1834.9838 log_delta_p=-9.1341 log_delta_a=-12.5363 min_alpha=0.0000 mean_alpha=0.0385 median_alpha=0.0323 max_alpha=0.2779 beta=0.0056

22:45:40 - INFO - EM Iter  73: ll=-1834.9837 log_delta_p=-9.1648 log_delta_a=-12.6468 min_alpha=0.0000 mean_alpha=0.0385 median_alpha=0.0323 max_alpha=0.2779 beta=0.0056

22:45:40 - INFO - EM Iter  74: ll=-1834.9837 log_delta_p=-9.1943 log_delta_a=-12.6000 min_alpha=0.0000 mean_alpha=0.0384 median_alpha=0.0322 max_alpha=0.2778 beta=0.0057

22:45:40 - INFO - EM Iter  75: ll=-1834.9835 log_delta_p=-9.2231 log_delta_a=-12.6386 min_alpha=0.0000 mean_alpha=0.0384 median_alpha=0.0322 max_alpha=0.2778 beta=0.0057

22:45:40 - INFO - Converged.

22:45:40 - INFO - Saving inferred adata to '/home/mcaskey/cellsweep/notebooks/data/simulation1_small_noise/celltype_granularity/adata_cellsweep_split_4.h5ad'

split_4 done

22:45:41 - INFO - Starting cellsweep denoising at 2026-10-03 22:45:41, cellsweep version 0.1.3

22:45:41 - INFO - Inferring celltype profiles.

22:45:41 - INFO - Number of celltypes: 96

Logging to /home/mcaskey/cellsweep/notebooks/data/simulation1_small_noise/celltype_granularity/cellsweep_split_8.log

22:45:41 - INFO - Inferring the ambient profile from empty droplets.

22:45:41 - INFO - adata.obs does not have 'init_alpha'. Setting to `init_alpha` argument.

22:45:41 - INFO - Performing Sparse EM with 32 Numba thread(s)

22:45:41 - INFO - EM Iter   1: ll=-1906.3851 log_delta_p=inf log_delta_a=inf min_alpha=0.3700 mean_alpha=0.5402 median_alpha=0.5447 max_alpha=0.6171 beta=0.0083

22:45:41 - INFO - EM Iter   2: ll=-1876.1238 log_delta_p=inf log_delta_a=inf min_alpha=0.2797 mean_alpha=0.4504 median_alpha=0.4524 max_alpha=0.5786 beta=0.0076

22:45:41 - INFO - EM Iter   3: ll=-1869.1634 log_delta_p=-1.7677 log_delta_a=-10.9617 min_alpha=0.2123 mean_alpha=0.3875 median_alpha=0.3880 max_alpha=0.5619 beta=0.0070

22:45:41 - INFO - EM Iter   4: ll=-1864.0182 log_delta_p=-2.1696 log_delta_a=-10.7176 min_alpha=0.1596 mean_alpha=0.3278 median_alpha=0.3272 max_alpha=0.5366 beta=0.0064

22:45:41 - INFO - EM Iter   5: ll=-1859.1966 log_delta_p=-2.3808 log_delta_a=-11.0302 min_alpha=0.1115 mean_alpha=0.2715 median_alpha=0.2698 max_alpha=0.5071 beta=0.0058

22:45:42 - INFO - EM Iter   6: ll=-1854.9037 log_delta_p=-2.6008 log_delta_a=-10.9638 min_alpha=0.0746 mean_alpha=0.2212 median_alpha=0.2182 max_alpha=0.4755 beta=0.0051

22:45:42 - INFO - EM Iter   7: ll=-1851.3230 log_delta_p=-2.8347 log_delta_a=-10.9294 min_alpha=0.0499 mean_alpha=0.1786 median_alpha=0.1745 max_alpha=0.4446 beta=0.0046

22:45:42 - INFO - EM Iter   8: ll=-1848.5230 log_delta_p=-3.1039 log_delta_a=-10.9294 min_alpha=0.0341 mean_alpha=0.1442 median_alpha=0.1391 max_alpha=0.4160 beta=0.0041

22:45:42 - INFO - EM Iter   9: ll=-1846.4557 log_delta_p=-3.3982 log_delta_a=-10.9768 min_alpha=0.0243 mean_alpha=0.1174 median_alpha=0.1119 max_alpha=0.3908 beta=0.0036

22:45:42 - INFO - EM Iter  10: ll=-1845.0032 log_delta_p=-3.7074 log_delta_a=-11.1127 min_alpha=0.0184 mean_alpha=0.0971 median_alpha=0.0912 max_alpha=0.3693 beta=0.0033

22:45:42 - INFO - EM Iter  11: ll=-1844.0261 log_delta_p=-4.0253 log_delta_a=-11.2678 min_alpha=0.0144 mean_alpha=0.0821 median_alpha=0.0760 max_alpha=0.3515 beta=0.0030

22:45:42 - INFO - EM Iter  12: ll=-1843.3922 log_delta_p=-4.3493 log_delta_a=-11.5100 min_alpha=0.0112 mean_alpha=0.0711 median_alpha=0.0649 max_alpha=0.3370 beta=0.0029

22:45:42 - INFO - EM Iter  13: ll=-1842.9936 log_delta_p=-4.6764 log_delta_a=-11.7001 min_alpha=0.0090 mean_alpha=0.0631 median_alpha=0.0568 max_alpha=0.3254 beta=0.0028

22:45:42 - INFO - EM Iter  14: ll=-1842.7486 log_delta_p=-4.9496 log_delta_a=-11.9881 min_alpha=0.0074 mean_alpha=0.0573 median_alpha=0.0511 max_alpha=0.3162 beta=0.0027

22:45:42 - INFO - EM Iter  15: ll=-1842.6008 log_delta_p=-5.0289 log_delta_a=-12.2573 min_alpha=0.0062 mean_alpha=0.0531 median_alpha=0.0467 max_alpha=0.3090 beta=0.0027

22:45:42 - INFO - EM Iter  16: ll=-1842.5122 log_delta_p=-5.1276 log_delta_a=-12.6501 min_alpha=0.0045 mean_alpha=0.0500 median_alpha=0.0437 max_alpha=0.3034 beta=0.0027

22:45:42 - INFO - EM Iter  17: ll=-1842.4584 log_delta_p=-5.2889 log_delta_a=-12.5565 min_alpha=0.0030 mean_alpha=0.0478 median_alpha=0.0414 max_alpha=0.2991 beta=0.0027

22:45:42 - INFO - EM Iter  18: ll=-1842.4261 log_delta_p=-5.5267 log_delta_a=-12.7072 min_alpha=0.0020 mean_alpha=0.0462 median_alpha=0.0397 max_alpha=0.2958 beta=0.0028

22:45:42 - INFO - EM Iter  19: ll=-1842.4053 log_delta_p=-5.6726 log_delta_a=-12.5154 min_alpha=0.0013 mean_alpha=0.0449 median_alpha=0.0385 max_alpha=0.2933 beta=0.0029

22:45:42 - INFO - EM Iter  20: ll=-1842.3918 log_delta_p=-5.7458 log_delta_a=-12.4654 min_alpha=0.0009 mean_alpha=0.0440 median_alpha=0.0376 max_alpha=0.2913 beta=0.0030

22:45:42 - INFO - EM Iter  21: ll=-1834.5154 log_delta_p=-5.8351 log_delta_a=-12.5196 min_alpha=0.0006 mean_alpha=0.0433 median_alpha=0.0369 max_alpha=0.2898 beta=0.0030

22:45:42 - INFO - EM Iter  22: ll=-1834.5090 log_delta_p=-5.9430 log_delta_a=-11.9348 min_alpha=0.0004 mean_alpha=0.0427 median_alpha=0.0363 max_alpha=0.2886 beta=0.0030

22:45:42 - INFO - EM Iter  23: ll=-1834.5040 log_delta_p=-6.0422 log_delta_a=-12.6903 min_alpha=0.0002 mean_alpha=0.0423 median_alpha=0.0358 max_alpha=0.2877 beta=0.0031

22:45:42 - INFO - EM Iter  24: ll=-1834.5003 log_delta_p=-6.1434 log_delta_a=-12.5485 min_alpha=0.0002 mean_alpha=0.0419 median_alpha=0.0356 max_alpha=0.2870 beta=0.0031

22:45:42 - INFO - EM Iter  25: ll=-1834.4974 log_delta_p=-6.2223 log_delta_a=-12.5353 min_alpha=0.0001 mean_alpha=0.0417 median_alpha=0.0353 max_alpha=0.2864 beta=0.0032

22:45:43 - INFO - EM Iter  26: ll=-1834.4949 log_delta_p=-6.2946 log_delta_a=-12.5440 min_alpha=0.0001 mean_alpha=0.0414 median_alpha=0.0351 max_alpha=0.2859 beta=0.0032

22:45:43 - INFO - EM Iter  27: ll=-1834.4925 log_delta_p=-6.3738 log_delta_a=-12.6018 min_alpha=0.0000 mean_alpha=0.0412 median_alpha=0.0349 max_alpha=0.2856 beta=0.0033

22:45:43 - INFO - EM Iter  28: ll=-1834.4904 log_delta_p=-6.4633 log_delta_a=-12.6312 min_alpha=0.0000 mean_alpha=0.0410 median_alpha=0.0347 max_alpha=0.2853 beta=0.0033

22:45:43 - INFO - EM Iter  29: ll=-1834.4886 log_delta_p=-6.5547 log_delta_a=-12.6011 min_alpha=0.0000 mean_alpha=0.0409 median_alpha=0.0345 max_alpha=0.2851 beta=0.0034

22:45:43 - INFO - EM Iter  30: ll=-1834.4869 log_delta_p=-6.6451 log_delta_a=-12.6329 min_alpha=0.0000 mean_alpha=0.0407 median_alpha=0.0344 max_alpha=0.2849 beta=0.0035

22:45:43 - INFO - EM Iter  31: ll=-1834.4854 log_delta_p=-6.7339 log_delta_a=-12.6553 min_alpha=0.0000 mean_alpha=0.0406 median_alpha=0.0343 max_alpha=0.2848 beta=0.0035

22:45:43 - INFO - EM Iter  32: ll=-1834.4840 log_delta_p=-6.8210 log_delta_a=-12.6797 min_alpha=0.0000 mean_alpha=0.0405 median_alpha=0.0342 max_alpha=0.2847 beta=0.0036

22:45:43 - INFO - EM Iter  33: ll=-1834.4822 log_delta_p=-6.9209 log_delta_a=-12.7379 min_alpha=0.0000 mean_alpha=0.0404 median_alpha=0.0341 max_alpha=0.2846 beta=0.0036

22:45:43 - INFO - EM Iter  34: ll=-1834.4811 log_delta_p=-7.0444 log_delta_a=-12.7617 min_alpha=0.0000 mean_alpha=0.0403 median_alpha=0.0339 max_alpha=0.2845 beta=0.0037

22:45:43 - INFO - EM Iter  35: ll=-1834.4800 log_delta_p=-7.1755 log_delta_a=-12.7040 min_alpha=0.0000 mean_alpha=0.0401 median_alpha=0.0338 max_alpha=0.2844 beta=0.0037

22:45:43 - INFO - EM Iter  36: ll=-1834.4789 log_delta_p=-7.2303 log_delta_a=-12.5787 min_alpha=0.0000 mean_alpha=0.0400 median_alpha=0.0337 max_alpha=0.2843 beta=0.0038

22:45:43 - INFO - EM Iter  37: ll=-1834.4776 log_delta_p=-7.2719 log_delta_a=-12.7073 min_alpha=0.0000 mean_alpha=0.0399 median_alpha=0.0336 max_alpha=0.2842 beta=0.0039

22:45:43 - INFO - EM Iter  38: ll=-1834.4768 log_delta_p=-7.2966 log_delta_a=-12.6606 min_alpha=0.0000 mean_alpha=0.0398 median_alpha=0.0335 max_alpha=0.2842 beta=0.0039

22:45:43 - INFO - EM Iter  39: ll=-1834.4757 log_delta_p=-7.3117 log_delta_a=-12.6587 min_alpha=0.0000 mean_alpha=0.0397 median_alpha=0.0334 max_alpha=0.2841 beta=0.0040

22:45:43 - INFO - EM Iter  40: ll=-1834.4749 log_delta_p=-7.3284 log_delta_a=-12.5988 min_alpha=0.0000 mean_alpha=0.0396 median_alpha=0.0333 max_alpha=0.2840 beta=0.0040

22:45:43 - INFO - EM Iter  41: ll=-1834.4739 log_delta_p=-7.3566 log_delta_a=-12.5826 min_alpha=0.0000 mean_alpha=0.0395 median_alpha=0.0333 max_alpha=0.2840 beta=0.0041

22:45:43 - INFO - EM Iter  42: ll=-1834.4731 log_delta_p=-7.3989 log_delta_a=-12.5696 min_alpha=0.0000 mean_alpha=0.0395 median_alpha=0.0332 max_alpha=0.2839 beta=0.0041

22:45:43 - INFO - EM Iter  43: ll=-1834.4723 log_delta_p=-7.4502 log_delta_a=-12.6555 min_alpha=0.0000 mean_alpha=0.0394 median_alpha=0.0331 max_alpha=0.2838 beta=0.0042

22:45:43 - INFO - EM Iter  44: ll=-1834.4715 log_delta_p=-7.5051 log_delta_a=-12.5958 min_alpha=0.0000 mean_alpha=0.0393 median_alpha=0.0330 max_alpha=0.2838 beta=0.0042

22:45:43 - INFO - EM Iter  45: ll=-1834.4709 log_delta_p=-7.5607 log_delta_a=-12.4774 min_alpha=0.0000 mean_alpha=0.0392 median_alpha=0.0329 max_alpha=0.2837 beta=0.0043

22:45:43 - INFO - EM Iter  46: ll=-1834.4701 log_delta_p=-7.6168 log_delta_a=-12.5744 min_alpha=0.0000 mean_alpha=0.0391 median_alpha=0.0328 max_alpha=0.2836 beta=0.0043

22:45:44 - INFO - EM Iter  47: ll=-1834.4694 log_delta_p=-7.6771 log_delta_a=-12.5535 min_alpha=0.0000 mean_alpha=0.0390 median_alpha=0.0327 max_alpha=0.2836 beta=0.0044

22:45:44 - INFO - EM Iter  48: ll=-1834.4688 log_delta_p=-7.7431 log_delta_a=-12.4913 min_alpha=0.0000 mean_alpha=0.0389 median_alpha=0.0327 max_alpha=0.2835 beta=0.0044

22:45:44 - INFO - EM Iter  49: ll=-1834.4682 log_delta_p=-7.8089 log_delta_a=-12.5232 min_alpha=0.0000 mean_alpha=0.0389 median_alpha=0.0326 max_alpha=0.2834 beta=0.0045

22:45:44 - INFO - EM Iter  50: ll=-1834.4675 log_delta_p=-7.8724 log_delta_a=-12.4796 min_alpha=0.0000 mean_alpha=0.0388 median_alpha=0.0325 max_alpha=0.2834 beta=0.0045

22:45:44 - INFO - EM Iter  51: ll=-1834.4674 log_delta_p=-7.9296 log_delta_a=-12.6083 min_alpha=0.0000 mean_alpha=0.0387 median_alpha=0.0324 max_alpha=0.2833 beta=0.0046

22:45:44 - INFO - EM Iter  52: ll=-1834.4666 log_delta_p=-7.9800 log_delta_a=-12.4883 min_alpha=0.0000 mean_alpha=0.0386 median_alpha=0.0323 max_alpha=0.2833 beta=0.0046

22:45:44 - INFO - EM Iter  53: ll=-1834.4662 log_delta_p=-8.0276 log_delta_a=-12.5052 min_alpha=0.0000 mean_alpha=0.0386 median_alpha=0.0323 max_alpha=0.2832 beta=0.0047

22:45:44 - INFO - EM Iter  54: ll=-1834.4658 log_delta_p=-8.0766 log_delta_a=-12.5211 min_alpha=0.0000 mean_alpha=0.0385 median_alpha=0.0322 max_alpha=0.2832 beta=0.0047

22:45:44 - INFO - EM Iter  55: ll=-1834.4653 log_delta_p=-8.1281 log_delta_a=-12.5027 min_alpha=0.0000 mean_alpha=0.0384 median_alpha=0.0321 max_alpha=0.2831 beta=0.0048

22:45:44 - INFO - EM Iter  56: ll=-1834.4648 log_delta_p=-8.1824 log_delta_a=-12.5969 min_alpha=0.0000 mean_alpha=0.0384 median_alpha=0.0321 max_alpha=0.2831 beta=0.0048

22:45:44 - INFO - EM Iter  57: ll=-1834.4643 log_delta_p=-8.2350 log_delta_a=-12.5743 min_alpha=0.0000 mean_alpha=0.0383 median_alpha=0.0320 max_alpha=0.2830 beta=0.0048

22:45:44 - INFO - EM Iter  58: ll=-1834.4638 log_delta_p=-8.2853 log_delta_a=-12.6203 min_alpha=0.0000 mean_alpha=0.0382 median_alpha=0.0319 max_alpha=0.2830 beta=0.0049

22:45:44 - INFO - EM Iter  59: ll=-1834.4635 log_delta_p=-8.3355 log_delta_a=-12.6133 min_alpha=0.0000 mean_alpha=0.0382 median_alpha=0.0319 max_alpha=0.2829 beta=0.0049

22:45:44 - INFO - EM Iter  60: ll=-1834.4634 log_delta_p=-8.3928 log_delta_a=-12.5772 min_alpha=0.0000 mean_alpha=0.0381 median_alpha=0.0318 max_alpha=0.2829 beta=0.0050

22:45:44 - INFO - EM Iter  61: ll=-1834.4629 log_delta_p=-8.4631 log_delta_a=-12.5370 min_alpha=0.0000 mean_alpha=0.0380 median_alpha=0.0317 max_alpha=0.2828 beta=0.0050

22:45:44 - INFO - EM Iter  62: ll=-1834.4626 log_delta_p=-8.5469 log_delta_a=-12.5464 min_alpha=0.0000 mean_alpha=0.0380 median_alpha=0.0317 max_alpha=0.2828 beta=0.0051

22:45:44 - INFO - EM Iter  63: ll=-1834.4619 log_delta_p=-8.6406 log_delta_a=-12.6307 min_alpha=0.0000 mean_alpha=0.0379 median_alpha=0.0316 max_alpha=0.2828 beta=0.0051

22:45:44 - INFO - EM Iter  64: ll=-1834.4618 log_delta_p=-8.7382 log_delta_a=-12.5752 min_alpha=0.0000 mean_alpha=0.0378 median_alpha=0.0316 max_alpha=0.2827 beta=0.0052

22:45:44 - INFO - EM Iter  65: ll=-1834.4614 log_delta_p=-8.8382 log_delta_a=-12.5611 min_alpha=0.0000 mean_alpha=0.0378 median_alpha=0.0315 max_alpha=0.2827 beta=0.0052

22:45:44 - INFO - EM Iter  66: ll=-1834.4613 log_delta_p=-8.9386 log_delta_a=-12.5307 min_alpha=0.0000 mean_alpha=0.0377 median_alpha=0.0314 max_alpha=0.2826 beta=0.0052

22:45:44 - INFO - EM Iter  67: ll=-1834.4610 log_delta_p=-9.0411 log_delta_a=-12.6417 min_alpha=0.0000 mean_alpha=0.0377 median_alpha=0.0314 max_alpha=0.2826 beta=0.0053

22:45:45 - INFO - EM Iter  68: ll=-1834.4605 log_delta_p=-9.1446 log_delta_a=-12.5651 min_alpha=0.0000 mean_alpha=0.0376 median_alpha=0.0313 max_alpha=0.2826 beta=0.0053

22:45:45 - INFO - EM Iter  69: ll=-1834.4603 log_delta_p=-9.1914 log_delta_a=-12.5132 min_alpha=0.0000 mean_alpha=0.0375 median_alpha=0.0312 max_alpha=0.2825 beta=0.0054

22:45:45 - INFO - EM Iter  70: ll=-1834.4600 log_delta_p=-9.2038 log_delta_a=-12.6434 min_alpha=0.0000 mean_alpha=0.0375 median_alpha=0.0312 max_alpha=0.2825 beta=0.0054

22:45:45 - INFO - EM Iter  71: ll=-1834.4598 log_delta_p=-9.2116 log_delta_a=-12.6272 min_alpha=0.0000 mean_alpha=0.0374 median_alpha=0.0311 max_alpha=0.2824 beta=0.0054

22:45:45 - INFO - Converged.

22:45:45 - INFO - Saving inferred adata to '/home/mcaskey/cellsweep/notebooks/data/simulation1_small_noise/celltype_granularity/adata_cellsweep_split_8.h5ad'

split_8 done

22:45:46 - INFO - Starting cellsweep denoising at 2026-10-03 22:45:46, cellsweep version 0.1.3

22:45:46 - INFO - Inferring celltype profiles.

22:45:46 - INFO - Number of celltypes: 12

22:45:46 - INFO - Inferring the ambient profile from empty droplets.

Logging to /home/mcaskey/cellsweep/notebooks/data/simulation1_small_noise/celltype_granularity/cellsweep_leiden_1.log

22:45:46 - INFO - adata.obs does not have 'init_alpha'. Setting to `init_alpha` argument.

22:45:46 - INFO - Performing Sparse EM with 32 Numba thread(s)

22:45:46 - INFO - EM Iter   1: ll=-1906.9173 log_delta_p=inf log_delta_a=inf min_alpha=0.3746 mean_alpha=0.5411 median_alpha=0.5452 max_alpha=0.7799 beta=0.0083

22:45:46 - INFO - EM Iter   2: ll=-1876.9106 log_delta_p=inf log_delta_a=inf min_alpha=0.2859 mean_alpha=0.4519 median_alpha=0.4535 max_alpha=0.8816 beta=0.0076

22:45:46 - INFO - EM Iter   3: ll=-1870.1187 log_delta_p=-2.0291 log_delta_a=-10.9968 min_alpha=0.2163 mean_alpha=0.3892 median_alpha=0.3896 max_alpha=0.9000 beta=0.0070

22:45:46 - INFO - EM Iter   4: ll=-1864.9883 log_delta_p=-2.1572 log_delta_a=-10.7418 min_alpha=0.1598 mean_alpha=0.3290 median_alpha=0.3282 max_alpha=0.9000 beta=0.0064

22:45:46 - INFO - EM Iter   5: ll=-1860.1034 log_delta_p=-2.3686 log_delta_a=-11.0581 min_alpha=0.1087 mean_alpha=0.2720 median_alpha=0.2700 max_alpha=0.6436 beta=0.0058

22:45:46 - INFO - EM Iter   6: ll=-1855.7550 log_delta_p=-2.5908 log_delta_a=-10.9867 min_alpha=0.0723 mean_alpha=0.2211 median_alpha=0.2181 max_alpha=0.4806 beta=0.0052

22:45:46 - INFO - EM Iter   7: ll=-1852.1462 log_delta_p=-2.8318 log_delta_a=-10.9156 min_alpha=0.0481 mean_alpha=0.1782 median_alpha=0.1741 max_alpha=0.4391 beta=0.0046

22:45:46 - INFO - EM Iter   8: ll=-1849.3371 log_delta_p=-3.1051 log_delta_a=-10.9239 min_alpha=0.0328 mean_alpha=0.1437 median_alpha=0.1388 max_alpha=0.4103 beta=0.0041

22:45:46 - INFO - EM Iter   9: ll=-1847.2704 log_delta_p=-3.4022 log_delta_a=-10.9678 min_alpha=0.0235 mean_alpha=0.1169 median_alpha=0.1115 max_alpha=0.3850 beta=0.0036

22:45:46 - INFO - EM Iter  10: ll=-1845.8232 log_delta_p=-3.7147 log_delta_a=-11.1151 min_alpha=0.0179 mean_alpha=0.0967 median_alpha=0.0910 max_alpha=0.3636 beta=0.0033

22:45:47 - INFO - EM Iter  11: ll=-1844.8515 log_delta_p=-4.0366 log_delta_a=-11.2718 min_alpha=0.0145 mean_alpha=0.0818 median_alpha=0.0757 max_alpha=0.3460 beta=0.0030

22:45:47 - INFO - EM Iter  12: ll=-1844.2235 log_delta_p=-4.3640 log_delta_a=-11.5035 min_alpha=0.0124 mean_alpha=0.0708 median_alpha=0.0647 max_alpha=0.3317 beta=0.0029

22:45:47 - INFO - EM Iter  13: ll=-1843.8310 log_delta_p=-4.6947 log_delta_a=-11.7037 min_alpha=0.0112 mean_alpha=0.0629 median_alpha=0.0567 max_alpha=0.3203 beta=0.0028

22:45:47 - INFO - EM Iter  14: ll=-1843.5922 log_delta_p=-5.0270 log_delta_a=-11.9536 min_alpha=0.0100 mean_alpha=0.0572 median_alpha=0.0510 max_alpha=0.3114 beta=0.0027

22:45:47 - INFO - EM Iter  15: ll=-1843.4498 log_delta_p=-5.3598 log_delta_a=-12.3223 min_alpha=0.0091 mean_alpha=0.0531 median_alpha=0.0468 max_alpha=0.3045 beta=0.0027

22:45:47 - INFO - EM Iter  16: ll=-1843.3666 log_delta_p=-5.6922 log_delta_a=-12.7230 min_alpha=0.0085 mean_alpha=0.0501 median_alpha=0.0438 max_alpha=0.2991 beta=0.0027

22:45:47 - INFO - EM Iter  17: ll=-1843.3182 log_delta_p=-6.0237 log_delta_a=-12.6091 min_alpha=0.0081 mean_alpha=0.0480 median_alpha=0.0416 max_alpha=0.2949 beta=0.0027

22:45:47 - INFO - EM Iter  18: ll=-1843.2904 log_delta_p=-6.3537 log_delta_a=-12.6068 min_alpha=0.0071 mean_alpha=0.0464 median_alpha=0.0399 max_alpha=0.2917 beta=0.0028

22:45:47 - INFO - EM Iter  19: ll=-1843.2733 log_delta_p=-6.6818 log_delta_a=-12.6075 min_alpha=0.0062 mean_alpha=0.0452 median_alpha=0.0388 max_alpha=0.2893 beta=0.0029

22:45:47 - INFO - EM Iter  20: ll=-1835.3955 log_delta_p=-7.0081 log_delta_a=-12.4180 min_alpha=0.0055 mean_alpha=0.0444 median_alpha=0.0379 max_alpha=0.2874 beta=0.0029

22:45:47 - INFO - EM Iter  21: ll=-1835.3898 log_delta_p=-7.3325 log_delta_a=-11.8925 min_alpha=0.0049 mean_alpha=0.0437 median_alpha=0.0373 max_alpha=0.2860 beta=0.0029

22:45:47 - INFO - EM Iter  22: ll=-1835.3864 log_delta_p=-7.5849 log_delta_a=-12.7000 min_alpha=0.0045 mean_alpha=0.0433 median_alpha=0.0369 max_alpha=0.2849 beta=0.0030

22:45:47 - INFO - EM Iter  23: ll=-1835.3840 log_delta_p=-7.9031 log_delta_a=-12.6354 min_alpha=0.0041 mean_alpha=0.0429 median_alpha=0.0365 max_alpha=0.2841 beta=0.0030

22:45:47 - INFO - EM Iter  24: ll=-1835.3829 log_delta_p=-8.2187 log_delta_a=-12.5545 min_alpha=0.0038 mean_alpha=0.0426 median_alpha=0.0362 max_alpha=0.2835 beta=0.0031

22:45:47 - INFO - EM Iter  25: ll=-1835.3821 log_delta_p=-8.4067 log_delta_a=-12.5630 min_alpha=0.0036 mean_alpha=0.0424 median_alpha=0.0360 max_alpha=0.2830 beta=0.0031

22:45:47 - INFO - EM Iter  26: ll=-1835.3813 log_delta_p=-8.5190 log_delta_a=-12.6145 min_alpha=0.0034 mean_alpha=0.0422 median_alpha=0.0358 max_alpha=0.2826 beta=0.0032

22:45:47 - INFO - EM Iter  27: ll=-1835.3811 log_delta_p=-8.5936 log_delta_a=-12.6087 min_alpha=0.0032 mean_alpha=0.0421 median_alpha=0.0357 max_alpha=0.2823 beta=0.0033

22:45:47 - INFO - EM Iter  28: ll=-1835.3806 log_delta_p=-8.5542 log_delta_a=-12.7567 min_alpha=0.0030 mean_alpha=0.0420 median_alpha=0.0355 max_alpha=0.2821 beta=0.0033

22:45:47 - INFO - EM Iter  29: ll=-1835.3802 log_delta_p=-8.5342 log_delta_a=-13.1407 min_alpha=0.0028 mean_alpha=0.0418 median_alpha=0.0354 max_alpha=0.2819 beta=0.0034

22:45:47 - INFO - EM Iter  30: ll=-1835.3798 log_delta_p=-8.5520 log_delta_a=-13.1981 min_alpha=0.0027 mean_alpha=0.0417 median_alpha=0.0353 max_alpha=0.2817 beta=0.0034

22:45:47 - INFO - EM Iter  31: ll=-1835.3797 log_delta_p=-8.6038 log_delta_a=-13.2640 min_alpha=0.0025 mean_alpha=0.0417 median_alpha=0.0352 max_alpha=0.2816 beta=0.0035

22:45:47 - INFO - EM Iter  32: ll=-1835.3795 log_delta_p=-8.6730 log_delta_a=-13.0747 min_alpha=0.0024 mean_alpha=0.0416 median_alpha=0.0352 max_alpha=0.2815 beta=0.0036

22:45:47 - INFO - EM Iter  33: ll=-1835.3794 log_delta_p=-8.7480 log_delta_a=-13.2204 min_alpha=0.0023 mean_alpha=0.0415 median_alpha=0.0351 max_alpha=0.2814 beta=0.0036

22:45:47 - INFO - EM Iter  34: ll=-1835.3790 log_delta_p=-8.8213 log_delta_a=-13.1629 min_alpha=0.0021 mean_alpha=0.0414 median_alpha=0.0350 max_alpha=0.2813 beta=0.0037

22:45:47 - INFO - EM Iter  35: ll=-1835.3790 log_delta_p=-8.8870 log_delta_a=-13.2151 min_alpha=0.0020 mean_alpha=0.0413 median_alpha=0.0350 max_alpha=0.2813 beta=0.0038

22:45:47 - INFO - EM Iter  36: ll=-1835.3790 log_delta_p=-8.9351 log_delta_a=-13.0096 min_alpha=0.0019 mean_alpha=0.0413 median_alpha=0.0349 max_alpha=0.2812 beta=0.0038

22:45:47 - INFO - EM Iter  37: ll=-1835.3787 log_delta_p=-8.9616 log_delta_a=-13.0799 min_alpha=0.0017 mean_alpha=0.0412 median_alpha=0.0348 max_alpha=0.2812 beta=0.0039

22:45:47 - INFO - EM Iter  38: ll=-1835.3786 log_delta_p=-8.9693 log_delta_a=-12.9872 min_alpha=0.0016 mean_alpha=0.0411 median_alpha=0.0348 max_alpha=0.2811 beta=0.0039

22:45:47 - INFO - EM Iter  39: ll=-1835.3784 log_delta_p=-8.9560 log_delta_a=-12.8328 min_alpha=0.0015 mean_alpha=0.0411 median_alpha=0.0347 max_alpha=0.2811 beta=0.0040

22:45:47 - INFO - EM Iter  40: ll=-1835.3784 log_delta_p=-8.9274 log_delta_a=-12.6859 min_alpha=0.0014 mean_alpha=0.0410 median_alpha=0.0347 max_alpha=0.2810 beta=0.0040

22:45:47 - INFO - EM Iter  41: ll=-1835.3779 log_delta_p=-8.8974 log_delta_a=-12.8136 min_alpha=0.0013 mean_alpha=0.0410 median_alpha=0.0346 max_alpha=0.2810 beta=0.0041

22:45:47 - INFO - EM Iter  42: ll=-1835.3778 log_delta_p=-8.8724 log_delta_a=-12.8166 min_alpha=0.0012 mean_alpha=0.0409 median_alpha=0.0345 max_alpha=0.2809 beta=0.0042

22:45:47 - INFO - EM Iter  43: ll=-1835.3778 log_delta_p=-8.8588 log_delta_a=-12.8288 min_alpha=0.0012 mean_alpha=0.0408 median_alpha=0.0345 max_alpha=0.2809 beta=0.0042

22:45:47 - INFO - EM Iter  44: ll=-1835.3778 log_delta_p=-8.8583 log_delta_a=-12.6831 min_alpha=0.0011 mean_alpha=0.0408 median_alpha=0.0344 max_alpha=0.2808 beta=0.0043

22:45:47 - INFO - EM Iter  45: ll=-1835.3776 log_delta_p=-8.8692 log_delta_a=-12.6830 min_alpha=0.0010 mean_alpha=0.0407 median_alpha=0.0344 max_alpha=0.2808 beta=0.0043

22:45:47 - INFO - EM Iter  46: ll=-1835.3774 log_delta_p=-8.8890 log_delta_a=-12.6542 min_alpha=0.0010 mean_alpha=0.0407 median_alpha=0.0343 max_alpha=0.2807 beta=0.0044

22:45:47 - INFO - EM Iter  47: ll=-1835.3774 log_delta_p=-8.9176 log_delta_a=-12.5671 min_alpha=0.0009 mean_alpha=0.0406 median_alpha=0.0343 max_alpha=0.2807 beta=0.0044

22:45:47 - INFO - EM Iter  48: ll=-1835.3774 log_delta_p=-8.9486 log_delta_a=-12.5753 min_alpha=0.0009 mean_alpha=0.0405 median_alpha=0.0342 max_alpha=0.2807 beta=0.0045

22:45:47 - INFO - EM Iter  49: ll=-1835.3771 log_delta_p=-8.9795 log_delta_a=-12.5952 min_alpha=0.0008 mean_alpha=0.0405 median_alpha=0.0341 max_alpha=0.2806 beta=0.0045

22:45:47 - INFO - EM Iter  50: ll=-1835.3771 log_delta_p=-9.0076 log_delta_a=-12.6553 min_alpha=0.0008 mean_alpha=0.0404 median_alpha=0.0341 max_alpha=0.2806 beta=0.0046

22:45:47 - INFO - EM Iter  51: ll=-1835.3771 log_delta_p=-9.0299 log_delta_a=-12.6428 min_alpha=0.0007 mean_alpha=0.0404 median_alpha=0.0340 max_alpha=0.2805 beta=0.0046

22:45:47 - INFO - EM Iter  52: ll=-1835.3770 log_delta_p=-9.0410 log_delta_a=-12.6878 min_alpha=0.0007 mean_alpha=0.0403 median_alpha=0.0340 max_alpha=0.2805 beta=0.0047

22:45:47 - INFO - EM Iter  53: ll=-1835.3768 log_delta_p=-9.0453 log_delta_a=-12.5299 min_alpha=0.0006 mean_alpha=0.0403 median_alpha=0.0339 max_alpha=0.2805 beta=0.0048

22:45:47 - INFO - EM Iter  54: ll=-1835.3768 log_delta_p=-9.0431 log_delta_a=-12.5526 min_alpha=0.0006 mean_alpha=0.0402 median_alpha=0.0339 max_alpha=0.2804 beta=0.0048

22:45:47 - INFO - EM Iter  55: ll=-1835.3766 log_delta_p=-9.0413 log_delta_a=-12.5178 min_alpha=0.0005 mean_alpha=0.0402 median_alpha=0.0338 max_alpha=0.2804 beta=0.0049

22:45:47 - INFO - EM Iter  56: ll=-1835.3766 log_delta_p=-9.0460 log_delta_a=-12.5675 min_alpha=0.0005 mean_alpha=0.0401 median_alpha=0.0338 max_alpha=0.2803 beta=0.0049

22:45:48 - INFO - EM Iter  57: ll=-1835.3766 log_delta_p=-9.0588 log_delta_a=-12.5685 min_alpha=0.0005 mean_alpha=0.0401 median_alpha=0.0337 max_alpha=0.2803 beta=0.0050

22:45:48 - INFO - EM Iter  58: ll=-1835.3765 log_delta_p=-9.0820 log_delta_a=-12.5372 min_alpha=0.0004 mean_alpha=0.0400 median_alpha=0.0337 max_alpha=0.2803 beta=0.0050

22:45:48 - INFO - EM Iter  59: ll=-1835.3763 log_delta_p=-9.1154 log_delta_a=-12.5154 min_alpha=0.0004 mean_alpha=0.0400 median_alpha=0.0336 max_alpha=0.2802 beta=0.0050

22:45:48 - INFO - EM Iter  60: ll=-1835.3763 log_delta_p=-9.1568 log_delta_a=-12.5032 min_alpha=0.0004 mean_alpha=0.0399 median_alpha=0.0336 max_alpha=0.2802 beta=0.0051

22:45:48 - INFO - EM Iter  61: ll=-1835.3763 log_delta_p=-9.2064 log_delta_a=-12.5375 min_alpha=0.0004 mean_alpha=0.0399 median_alpha=0.0335 max_alpha=0.2802 beta=0.0051

22:45:48 - INFO - EM Iter  62: ll=-1835.3763 log_delta_p=-9.2632 log_delta_a=-12.5085 min_alpha=0.0003 mean_alpha=0.0398 median_alpha=0.0335 max_alpha=0.2801 beta=0.0052

22:45:48 - INFO - Converged.

22:45:48 - INFO - Saving inferred adata to '/home/mcaskey/cellsweep/notebooks/data/simulation1_small_noise/celltype_granularity/adata_cellsweep_leiden_1.h5ad'

leiden_1 done

22:45:49 - INFO - Starting cellsweep denoising at 2026-10-03 22:45:49, cellsweep version 0.1.3

22:45:49 - INFO - Inferring celltype profiles.

22:45:49 - INFO - Number of celltypes: 32

22:45:49 - INFO - Inferring the ambient profile from empty droplets.

Logging to /home/mcaskey/cellsweep/notebooks/data/simulation1_small_noise/celltype_granularity/cellsweep_leiden_5.log

22:45:49 - INFO - adata.obs does not have 'init_alpha'. Setting to `init_alpha` argument.

22:45:49 - INFO - Performing Sparse EM with 32 Numba thread(s)

22:45:49 - INFO - EM Iter   1: ll=-1906.7578 log_delta_p=inf log_delta_a=inf min_alpha=0.3746 mean_alpha=0.5413 median_alpha=0.5453 max_alpha=0.7551 beta=0.0083

22:45:49 - INFO - EM Iter   2: ll=-1876.6765 log_delta_p=inf log_delta_a=inf min_alpha=0.2859 mean_alpha=0.4525 median_alpha=0.4538 max_alpha=0.8591 beta=0.0076

22:45:49 - INFO - EM Iter   3: ll=-1869.8269 log_delta_p=-2.0291 log_delta_a=-10.9715 min_alpha=0.2163 mean_alpha=0.3903 median_alpha=0.3903 max_alpha=0.9000 beta=0.0070

22:45:49 - INFO - EM Iter   4: ll=-1864.6837 log_delta_p=-2.1572 log_delta_a=-10.7561 min_alpha=0.1598 mean_alpha=0.3307 median_alpha=0.3295 max_alpha=0.9000 beta=0.0064

22:45:49 - INFO - EM Iter   5: ll=-1859.8110 log_delta_p=-2.3686 log_delta_a=-11.0296 min_alpha=0.1146 mean_alpha=0.2741 median_alpha=0.2715 max_alpha=0.6436 beta=0.0058

22:45:49 - INFO - EM Iter   6: ll=-1855.4755 log_delta_p=-2.5929 log_delta_a=-10.9688 min_alpha=0.0771 mean_alpha=0.2235 median_alpha=0.2196 max_alpha=0.4838 beta=0.0052

22:45:49 - INFO - EM Iter   7: ll=-1851.8720 log_delta_p=-2.8282 log_delta_a=-10.9117 min_alpha=0.0517 mean_alpha=0.1806 median_alpha=0.1757 max_alpha=0.4531 beta=0.0046

22:45:49 - INFO - EM Iter   8: ll=-1849.0637 log_delta_p=-3.0893 log_delta_a=-10.9310 min_alpha=0.0354 mean_alpha=0.1459 median_alpha=0.1401 max_alpha=0.4245 beta=0.0041

22:45:49 - INFO - EM Iter   9: ll=-1846.9968 log_delta_p=-3.3741 log_delta_a=-10.9712 min_alpha=0.0253 mean_alpha=0.1189 median_alpha=0.1126 max_alpha=0.3992 beta=0.0036

22:45:49 - INFO - EM Iter  10: ll=-1845.5494 log_delta_p=-3.6755 log_delta_a=-11.1203 min_alpha=0.0191 mean_alpha=0.0985 median_alpha=0.0919 max_alpha=0.3774 beta=0.0033

22:45:49 - INFO - EM Iter  11: ll=-1844.5789 log_delta_p=-3.9875 log_delta_a=-11.2727 min_alpha=0.0153 mean_alpha=0.0833 median_alpha=0.0766 max_alpha=0.3592 beta=0.0030

22:45:49 - INFO - EM Iter  12: ll=-1843.9523 log_delta_p=-4.3059 log_delta_a=-11.5138 min_alpha=0.0131 mean_alpha=0.0721 median_alpha=0.0654 max_alpha=0.3444 beta=0.0029

22:45:49 - INFO - EM Iter  13: ll=-1843.5610 log_delta_p=-4.6280 log_delta_a=-11.7059 min_alpha=0.0112 mean_alpha=0.0640 median_alpha=0.0572 max_alpha=0.3324 beta=0.0027

22:45:49 - INFO - EM Iter  14: ll=-1843.3230 log_delta_p=-4.9518 log_delta_a=-11.9308 min_alpha=0.0099 mean_alpha=0.0581 median_alpha=0.0515 max_alpha=0.3228 beta=0.0027

22:45:49 - INFO - EM Iter  15: ll=-1843.1818 log_delta_p=-5.2762 log_delta_a=-12.3683 min_alpha=0.0090 mean_alpha=0.0539 median_alpha=0.0473 max_alpha=0.3153 beta=0.0027

22:45:49 - INFO - EM Iter  16: ll=-1843.0987 log_delta_p=-5.6002 log_delta_a=-12.4645 min_alpha=0.0084 mean_alpha=0.0508 median_alpha=0.0440 max_alpha=0.3095 beta=0.0027

22:45:49 - INFO - EM Iter  17: ll=-1843.0506 log_delta_p=-5.9230 log_delta_a=-12.7136 min_alpha=0.0068 mean_alpha=0.0486 median_alpha=0.0418 max_alpha=0.3049 beta=0.0027

22:45:49 - INFO - EM Iter  18: ll=-1843.0221 log_delta_p=-6.2437 log_delta_a=-12.6726 min_alpha=0.0056 mean_alpha=0.0469 median_alpha=0.0402 max_alpha=0.3014 beta=0.0028

22:45:50 - INFO - EM Iter  19: ll=-1843.0050 log_delta_p=-6.5622 log_delta_a=-12.5862 min_alpha=0.0046 mean_alpha=0.0457 median_alpha=0.0390 max_alpha=0.2986 beta=0.0029

22:45:50 - INFO - EM Iter  20: ll=-1835.1269 log_delta_p=-6.8783 log_delta_a=-12.4466 min_alpha=0.0039 mean_alpha=0.0448 median_alpha=0.0381 max_alpha=0.2965 beta=0.0029

22:45:50 - INFO - EM Iter  21: ll=-1835.1205 log_delta_p=-7.1920 log_delta_a=-11.9041 min_alpha=0.0033 mean_alpha=0.0441 median_alpha=0.0374 max_alpha=0.2949 beta=0.0029

22:45:50 - INFO - EM Iter  22: ll=-1835.1166 log_delta_p=-7.4399 log_delta_a=-12.6988 min_alpha=0.0029 mean_alpha=0.0436 median_alpha=0.0369 max_alpha=0.2936 beta=0.0030

22:45:50 - INFO - EM Iter  23: ll=-1835.1142 log_delta_p=-7.7428 log_delta_a=-12.5864 min_alpha=0.0026 mean_alpha=0.0432 median_alpha=0.0365 max_alpha=0.2926 beta=0.0030

22:45:50 - INFO - EM Iter  24: ll=-1835.1125 log_delta_p=-8.0393 log_delta_a=-12.5474 min_alpha=0.0023 mean_alpha=0.0429 median_alpha=0.0363 max_alpha=0.2918 beta=0.0031

22:45:50 - INFO - EM Iter  25: ll=-1835.1112 log_delta_p=-8.3283 log_delta_a=-12.5718 min_alpha=0.0021 mean_alpha=0.0427 median_alpha=0.0360 max_alpha=0.2912 beta=0.0032

22:45:50 - INFO - EM Iter  26: ll=-1835.1102 log_delta_p=-8.5194 log_delta_a=-12.6647 min_alpha=0.0019 mean_alpha=0.0425 median_alpha=0.0359 max_alpha=0.2907 beta=0.0032

22:45:50 - INFO - EM Iter  27: ll=-1835.1094 log_delta_p=-8.5938 log_delta_a=-12.5989 min_alpha=0.0018 mean_alpha=0.0423 median_alpha=0.0357 max_alpha=0.2902 beta=0.0033

22:45:50 - INFO - EM Iter  28: ll=-1835.1090 log_delta_p=-8.5545 log_delta_a=-12.8413 min_alpha=0.0016 mean_alpha=0.0422 median_alpha=0.0356 max_alpha=0.2899 beta=0.0033

22:45:50 - INFO - EM Iter  29: ll=-1835.1083 log_delta_p=-8.5344 log_delta_a=-13.1788 min_alpha=0.0015 mean_alpha=0.0420 median_alpha=0.0355 max_alpha=0.2896 beta=0.0034

22:45:50 - INFO - EM Iter  30: ll=-1835.1080 log_delta_p=-8.5529 log_delta_a=-13.1203 min_alpha=0.0014 mean_alpha=0.0419 median_alpha=0.0354 max_alpha=0.2894 beta=0.0035

22:45:50 - INFO - EM Iter  31: ll=-1835.1074 log_delta_p=-8.6043 log_delta_a=-12.9679 min_alpha=0.0013 mean_alpha=0.0418 median_alpha=0.0353 max_alpha=0.2892 beta=0.0035

22:45:50 - INFO - EM Iter  32: ll=-1835.1070 log_delta_p=-8.6737 log_delta_a=-12.9669 min_alpha=0.0012 mean_alpha=0.0417 median_alpha=0.0352 max_alpha=0.2891 beta=0.0036

22:45:50 - INFO - EM Iter  33: ll=-1835.1066 log_delta_p=-8.7489 log_delta_a=-13.0716 min_alpha=0.0011 mean_alpha=0.0416 median_alpha=0.0351 max_alpha=0.2889 beta=0.0036

22:45:50 - INFO - EM Iter  34: ll=-1835.1061 log_delta_p=-8.8222 log_delta_a=-13.0166 min_alpha=0.0011 mean_alpha=0.0415 median_alpha=0.0350 max_alpha=0.2888 beta=0.0037

22:45:50 - INFO - EM Iter  35: ll=-1835.1058 log_delta_p=-8.8882 log_delta_a=-13.0690 min_alpha=0.0010 mean_alpha=0.0415 median_alpha=0.0349 max_alpha=0.2887 beta=0.0038

22:45:50 - INFO - EM Iter  36: ll=-1835.1054 log_delta_p=-8.9363 log_delta_a=-13.1295 min_alpha=0.0009 mean_alpha=0.0414 median_alpha=0.0348 max_alpha=0.2886 beta=0.0038

22:45:50 - INFO - EM Iter  37: ll=-1835.1051 log_delta_p=-8.9628 log_delta_a=-13.3013 min_alpha=0.0009 mean_alpha=0.0413 median_alpha=0.0347 max_alpha=0.2885 beta=0.0039

22:45:50 - INFO - EM Iter  38: ll=-1835.1048 log_delta_p=-8.9709 log_delta_a=-13.2780 min_alpha=0.0008 mean_alpha=0.0412 median_alpha=0.0347 max_alpha=0.2885 beta=0.0039

22:45:50 - INFO - EM Iter  39: ll=-1835.1046 log_delta_p=-8.9573 log_delta_a=-13.1981 min_alpha=0.0008 mean_alpha=0.0412 median_alpha=0.0346 max_alpha=0.2884 beta=0.0040

22:45:50 - INFO - EM Iter  40: ll=-1835.1045 log_delta_p=-8.9289 log_delta_a=-12.9472 min_alpha=0.0007 mean_alpha=0.0411 median_alpha=0.0345 max_alpha=0.2883 beta=0.0041

22:45:50 - INFO - EM Iter  41: ll=-1835.1040 log_delta_p=-8.8993 log_delta_a=-12.9747 min_alpha=0.0007 mean_alpha=0.0410 median_alpha=0.0344 max_alpha=0.2883 beta=0.0041

22:45:50 - INFO - EM Iter  42: ll=-1835.1037 log_delta_p=-8.8742 log_delta_a=-12.9970 min_alpha=0.0006 mean_alpha=0.0409 median_alpha=0.0344 max_alpha=0.2882 beta=0.0042

22:45:50 - INFO - EM Iter  43: ll=-1835.1035 log_delta_p=-8.8606 log_delta_a=-12.9039 min_alpha=0.0006 mean_alpha=0.0409 median_alpha=0.0343 max_alpha=0.2882 beta=0.0042

22:45:50 - INFO - EM Iter  44: ll=-1835.1032 log_delta_p=-8.8604 log_delta_a=-12.7336 min_alpha=0.0005 mean_alpha=0.0408 median_alpha=0.0342 max_alpha=0.2881 beta=0.0043

22:45:50 - INFO - EM Iter  45: ll=-1835.1030 log_delta_p=-8.8708 log_delta_a=-12.7414 min_alpha=0.0005 mean_alpha=0.0407 median_alpha=0.0342 max_alpha=0.2881 beta=0.0044

22:45:50 - INFO - EM Iter  46: ll=-1835.1027 log_delta_p=-8.8910 log_delta_a=-12.7907 min_alpha=0.0005 mean_alpha=0.0407 median_alpha=0.0341 max_alpha=0.2880 beta=0.0044

22:45:50 - INFO - EM Iter  47: ll=-1835.1027 log_delta_p=-8.9193 log_delta_a=-12.6315 min_alpha=0.0004 mean_alpha=0.0406 median_alpha=0.0341 max_alpha=0.2880 beta=0.0045

22:45:50 - INFO - EM Iter  48: ll=-1835.1026 log_delta_p=-8.9506 log_delta_a=-12.6559 min_alpha=0.0004 mean_alpha=0.0405 median_alpha=0.0340 max_alpha=0.2879 beta=0.0045

22:45:50 - INFO - EM Iter  49: ll=-1835.1022 log_delta_p=-8.9819 log_delta_a=-12.7059 min_alpha=0.0004 mean_alpha=0.0405 median_alpha=0.0339 max_alpha=0.2879 beta=0.0046

22:45:50 - INFO - EM Iter  50: ll=-1835.1021 log_delta_p=-9.0099 log_delta_a=-12.6176 min_alpha=0.0004 mean_alpha=0.0404 median_alpha=0.0339 max_alpha=0.2878 beta=0.0046

22:45:50 - INFO - EM Iter  51: ll=-1835.1019 log_delta_p=-9.0323 log_delta_a=-12.7002 min_alpha=0.0003 mean_alpha=0.0403 median_alpha=0.0338 max_alpha=0.2878 beta=0.0047

22:45:50 - INFO - EM Iter  52: ll=-1835.1016 log_delta_p=-9.0443 log_delta_a=-12.6025 min_alpha=0.0003 mean_alpha=0.0403 median_alpha=0.0338 max_alpha=0.2878 beta=0.0047

22:45:50 - INFO - EM Iter  53: ll=-1835.1014 log_delta_p=-9.0482 log_delta_a=-12.5759 min_alpha=0.0003 mean_alpha=0.0402 median_alpha=0.0337 max_alpha=0.2877 beta=0.0048

22:45:50 - INFO - EM Iter  54: ll=-1835.1011 log_delta_p=-9.0462 log_delta_a=-12.6634 min_alpha=0.0003 mean_alpha=0.0402 median_alpha=0.0336 max_alpha=0.2877 beta=0.0048

22:45:50 - INFO - EM Iter  55: ll=-1835.1010 log_delta_p=-9.0442 log_delta_a=-12.6027 min_alpha=0.0002 mean_alpha=0.0401 median_alpha=0.0336 max_alpha=0.2876 beta=0.0049

22:45:51 - INFO - EM Iter  56: ll=-1835.1010 log_delta_p=-9.0486 log_delta_a=-12.6885 min_alpha=0.0002 mean_alpha=0.0400 median_alpha=0.0335 max_alpha=0.2876 beta=0.0049

22:45:51 - INFO - EM Iter  57: ll=-1835.1010 log_delta_p=-9.0619 log_delta_a=-12.5678 min_alpha=0.0002 mean_alpha=0.0400 median_alpha=0.0335 max_alpha=0.2875 beta=0.0050

22:45:51 - INFO - EM Iter  58: ll=-1835.1008 log_delta_p=-9.0850 log_delta_a=-12.5381 min_alpha=0.0002 mean_alpha=0.0399 median_alpha=0.0334 max_alpha=0.2875 beta=0.0050

22:45:51 - INFO - EM Iter  59: ll=-1835.1005 log_delta_p=-9.1179 log_delta_a=-12.5549 min_alpha=0.0002 mean_alpha=0.0399 median_alpha=0.0334 max_alpha=0.2875 beta=0.0051

22:45:51 - INFO - EM Iter  60: ll=-1835.1002 log_delta_p=-9.1591 log_delta_a=-12.5715 min_alpha=0.0002 mean_alpha=0.0398 median_alpha=0.0333 max_alpha=0.2874 beta=0.0051

22:45:51 - INFO - EM Iter  61: ll=-1835.1002 log_delta_p=-9.2085 log_delta_a=-12.5363 min_alpha=0.0001 mean_alpha=0.0398 median_alpha=0.0332 max_alpha=0.2874 beta=0.0052

22:45:51 - INFO - EM Iter  62: ll=-1835.1000 log_delta_p=-9.2655 log_delta_a=-12.4817 min_alpha=0.0001 mean_alpha=0.0397 median_alpha=0.0332 max_alpha=0.2873 beta=0.0052

22:45:51 - INFO - Converged.

22:45:51 - INFO - Saving inferred adata to '/home/mcaskey/cellsweep/notebooks/data/simulation1_small_noise/celltype_granularity/adata_cellsweep_leiden_5.h5ad'

leiden_5 done

22:45:52 - INFO - Starting cellsweep denoising at 2026-10-03 22:45:52, cellsweep version 0.1.3

22:45:52 - INFO - Inferring celltype profiles.

Logging to /home/mcaskey/cellsweep/notebooks/data/simulation1_small_noise/celltype_granularity/cellsweep_leiden_20.log

22:45:52 - INFO - Number of celltypes: 269

22:45:52 - INFO - Inferring the ambient profile from empty droplets.

22:45:52 - INFO - adata.obs does not have 'init_alpha'. Setting to `init_alpha` argument.

22:45:52 - INFO - Performing Sparse EM with 32 Numba thread(s)

22:45:52 - INFO - EM Iter   1: ll=-1905.2379 log_delta_p=inf log_delta_a=inf min_alpha=0.3746 mean_alpha=0.5384 median_alpha=0.5422 max_alpha=0.6296 beta=0.0083

22:45:52 - INFO - EM Iter   2: ll=-1874.4118 log_delta_p=inf log_delta_a=inf min_alpha=0.2859 mean_alpha=0.4471 median_alpha=0.4482 max_alpha=0.5949 beta=0.0075

22:45:52 - INFO - EM Iter   3: ll=-1867.0218 log_delta_p=-2.0289 log_delta_a=-10.9054 min_alpha=0.2163 mean_alpha=0.3837 median_alpha=0.3832 max_alpha=0.5776 beta=0.0069

22:45:52 - INFO - EM Iter   4: ll=-1861.7755 log_delta_p=-2.1569 log_delta_a=-10.6989 min_alpha=0.1598 mean_alpha=0.3251 median_alpha=0.3236 max_alpha=0.5583 beta=0.0063

22:45:53 - INFO - EM Iter   5: ll=-1857.0472 log_delta_p=-2.3779 log_delta_a=-10.9828 min_alpha=0.1160 mean_alpha=0.2707 median_alpha=0.2680 max_alpha=0.5361 beta=0.0057

22:45:53 - INFO - EM Iter   6: ll=-1852.8880 log_delta_p=-2.6099 log_delta_a=-10.9957 min_alpha=0.0817 mean_alpha=0.2222 median_alpha=0.2184 max_alpha=0.5123 beta=0.0051

22:45:53 - INFO - EM Iter   7: ll=-1849.4045 log_delta_p=-2.8517 log_delta_a=-10.9690 min_alpha=0.0563 mean_alpha=0.1808 median_alpha=0.1761 max_alpha=0.4876 beta=0.0046

22:45:53 - INFO - EM Iter   8: ll=-1846.6509 log_delta_p=-3.0932 log_delta_a=-10.9881 min_alpha=0.0392 mean_alpha=0.1469 median_alpha=0.1414 max_alpha=0.4629 beta=0.0041

22:45:53 - INFO - EM Iter   9: ll=-1844.5947 log_delta_p=-3.3579 log_delta_a=-11.0020 min_alpha=0.0279 mean_alpha=0.1202 median_alpha=0.1141 max_alpha=0.4383 beta=0.0036

22:45:53 - INFO - EM Iter  10: ll=-1843.1360 log_delta_p=-3.6411 log_delta_a=-11.1580 min_alpha=0.0209 mean_alpha=0.0997 median_alpha=0.0930 max_alpha=0.4144 beta=0.0033

22:45:53 - INFO - EM Iter  11: ll=-1842.1458 log_delta_p=-3.9377 log_delta_a=-11.3063 min_alpha=0.0166 mean_alpha=0.0843 median_alpha=0.0775 max_alpha=0.3912 beta=0.0031

22:45:53 - INFO - EM Iter  12: ll=-1841.4981 log_delta_p=-4.2429 log_delta_a=-11.5132 min_alpha=0.0136 mean_alpha=0.0729 median_alpha=0.0660 max_alpha=0.3688 beta=0.0029

22:45:53 - INFO - EM Iter  13: ll=-1841.0872 log_delta_p=-4.5531 log_delta_a=-11.7175 min_alpha=0.0115 mean_alpha=0.0645 median_alpha=0.0577 max_alpha=0.3473 beta=0.0028

22:45:54 - INFO - EM Iter  14: ll=-1840.8317 log_delta_p=-4.8624 log_delta_a=-11.9554 min_alpha=0.0101 mean_alpha=0.0584 median_alpha=0.0515 max_alpha=0.3269 beta=0.0027

22:45:54 - INFO - EM Iter  15: ll=-1840.6752 log_delta_p=-5.1099 log_delta_a=-12.2713 min_alpha=0.0092 mean_alpha=0.0539 median_alpha=0.0471 max_alpha=0.3187 beta=0.0027

22:45:54 - INFO - EM Iter  16: ll=-1840.5792 log_delta_p=-5.3199 log_delta_a=-12.4837 min_alpha=0.0086 mean_alpha=0.0506 median_alpha=0.0438 max_alpha=0.3124 beta=0.0027

22:45:54 - INFO - EM Iter  17: ll=-1840.5194 log_delta_p=-5.5023 log_delta_a=-12.5587 min_alpha=0.0069 mean_alpha=0.0482 median_alpha=0.0413 max_alpha=0.3076 beta=0.0027

22:45:54 - INFO - EM Iter  18: ll=-1840.4805 log_delta_p=-5.6539 log_delta_a=-12.8020 min_alpha=0.0056 mean_alpha=0.0463 median_alpha=0.0395 max_alpha=0.3037 beta=0.0028

22:45:54 - INFO - EM Iter  19: ll=-1840.4534 log_delta_p=-5.7699 log_delta_a=-12.5521 min_alpha=0.0046 mean_alpha=0.0449 median_alpha=0.0380 max_alpha=0.3006 beta=0.0029

22:45:54 - INFO - EM Iter  20: ll=-1840.4333 log_delta_p=-5.8597 log_delta_a=-12.4483 min_alpha=0.0039 mean_alpha=0.0438 median_alpha=0.0370 max_alpha=0.2982 beta=0.0030

22:45:54 - INFO - EM Iter  21: ll=-1832.5494 log_delta_p=-5.9534 log_delta_a=-12.4136 min_alpha=0.0033 mean_alpha=0.0429 median_alpha=0.0361 max_alpha=0.2963 beta=0.0030

22:45:54 - INFO - EM Iter  22: ll=-1832.5355 log_delta_p=-6.0671 log_delta_a=-11.9011 min_alpha=0.0028 mean_alpha=0.0421 median_alpha=0.0354 max_alpha=0.2947 beta=0.0030

22:45:54 - INFO - EM Iter  23: ll=-1832.5230 log_delta_p=-6.1673 log_delta_a=-12.5769 min_alpha=0.0024 mean_alpha=0.0415 median_alpha=0.0349 max_alpha=0.2935 beta=0.0031

22:45:55 - INFO - EM Iter  24: ll=-1832.5117 log_delta_p=-6.2636 log_delta_a=-12.8426 min_alpha=0.0020 mean_alpha=0.0410 median_alpha=0.0343 max_alpha=0.2926 beta=0.0031

22:45:55 - INFO - EM Iter  25: ll=-1832.5011 log_delta_p=-6.3297 log_delta_a=-12.6400 min_alpha=0.0017 mean_alpha=0.0405 median_alpha=0.0338 max_alpha=0.2917 beta=0.0031

22:45:55 - INFO - EM Iter  26: ll=-1832.4914 log_delta_p=-6.3841 log_delta_a=-12.6385 min_alpha=0.0013 mean_alpha=0.0400 median_alpha=0.0333 max_alpha=0.2910 beta=0.0032

22:45:55 - INFO - EM Iter  27: ll=-1832.4821 log_delta_p=-6.4567 log_delta_a=-12.5887 min_alpha=0.0009 mean_alpha=0.0396 median_alpha=0.0330 max_alpha=0.2904 beta=0.0032

22:45:55 - INFO - EM Iter  28: ll=-1832.4734 log_delta_p=-6.5506 log_delta_a=-12.5774 min_alpha=0.0007 mean_alpha=0.0392 median_alpha=0.0326 max_alpha=0.2898 beta=0.0033

22:45:55 - INFO - EM Iter  29: ll=-1832.4654 log_delta_p=-6.6487 log_delta_a=-12.6292 min_alpha=0.0005 mean_alpha=0.0388 median_alpha=0.0322 max_alpha=0.2893 beta=0.0033

22:45:55 - INFO - EM Iter  30: ll=-1832.4578 log_delta_p=-6.7362 log_delta_a=-12.6247 min_alpha=0.0003 mean_alpha=0.0385 median_alpha=0.0319 max_alpha=0.2888 beta=0.0034

22:45:55 - INFO - EM Iter  31: ll=-1832.4504 log_delta_p=-6.8040 log_delta_a=-12.5982 min_alpha=0.0002 mean_alpha=0.0381 median_alpha=0.0315 max_alpha=0.2884 beta=0.0034

22:45:55 - INFO - EM Iter  32: ll=-1832.4440 log_delta_p=-6.8524 log_delta_a=-12.5870 min_alpha=0.0002 mean_alpha=0.0378 median_alpha=0.0312 max_alpha=0.2880 beta=0.0034

22:45:55 - INFO - EM Iter  33: ll=-1832.4373 log_delta_p=-6.8896 log_delta_a=-12.5949 min_alpha=0.0001 mean_alpha=0.0375 median_alpha=0.0309 max_alpha=0.2876 beta=0.0035

22:45:56 - INFO - EM Iter  34: ll=-1832.4312 log_delta_p=-6.8880 log_delta_a=-12.5082 min_alpha=0.0001 mean_alpha=0.0372 median_alpha=0.0306 max_alpha=0.2874 beta=0.0035

22:45:56 - INFO - EM Iter  35: ll=-1832.4254 log_delta_p=-6.8899 log_delta_a=-12.5673 min_alpha=0.0001 mean_alpha=0.0369 median_alpha=0.0303 max_alpha=0.2871 beta=0.0036

22:45:56 - INFO - EM Iter  36: ll=-1832.4200 log_delta_p=-6.9020 log_delta_a=-12.4646 min_alpha=0.0000 mean_alpha=0.0366 median_alpha=0.0300 max_alpha=0.2869 beta=0.0036

22:45:56 - INFO - EM Iter  37: ll=-1832.4147 log_delta_p=-6.9213 log_delta_a=-12.5712 min_alpha=0.0000 mean_alpha=0.0363 median_alpha=0.0297 max_alpha=0.2867 beta=0.0037

22:45:56 - INFO - EM Iter  38: ll=-1832.4101 log_delta_p=-6.9437 log_delta_a=-12.6522 min_alpha=0.0000 mean_alpha=0.0360 median_alpha=0.0294 max_alpha=0.2866 beta=0.0037

22:45:56 - INFO - EM Iter  39: ll=-1832.4054 log_delta_p=-6.9692 log_delta_a=-12.5363 min_alpha=0.0000 mean_alpha=0.0357 median_alpha=0.0291 max_alpha=0.2864 beta=0.0037

22:45:56 - INFO - EM Iter  40: ll=-1832.4011 log_delta_p=-6.9998 log_delta_a=-12.6054 min_alpha=0.0000 mean_alpha=0.0355 median_alpha=0.0288 max_alpha=0.2863 beta=0.0038

22:45:56 - INFO - EM Iter  41: ll=-1832.3966 log_delta_p=-7.0366 log_delta_a=-12.6304 min_alpha=0.0000 mean_alpha=0.0352 median_alpha=0.0286 max_alpha=0.2861 beta=0.0038

22:45:56 - INFO - EM Iter  42: ll=-1832.3926 log_delta_p=-7.0774 log_delta_a=-12.5424 min_alpha=0.0000 mean_alpha=0.0350 median_alpha=0.0283 max_alpha=0.2860 beta=0.0038

22:45:56 - INFO - EM Iter  43: ll=-1832.3890 log_delta_p=-7.1206 log_delta_a=-12.5095 min_alpha=0.0000 mean_alpha=0.0347 median_alpha=0.0281 max_alpha=0.2858 beta=0.0039

22:45:57 - INFO - EM Iter  44: ll=-1832.3851 log_delta_p=-7.1647 log_delta_a=-12.6399 min_alpha=0.0000 mean_alpha=0.0345 median_alpha=0.0279 max_alpha=0.2857 beta=0.0039

22:45:57 - INFO - EM Iter  45: ll=-1832.3819 log_delta_p=-7.2099 log_delta_a=-12.5866 min_alpha=0.0000 mean_alpha=0.0343 median_alpha=0.0277 max_alpha=0.2856 beta=0.0040

22:45:57 - INFO - EM Iter  46: ll=-1832.3784 log_delta_p=-7.2575 log_delta_a=-12.6250 min_alpha=0.0000 mean_alpha=0.0340 median_alpha=0.0275 max_alpha=0.2854 beta=0.0040

22:45:57 - INFO - EM Iter  47: ll=-1832.3755 log_delta_p=-7.3094 log_delta_a=-12.6299 min_alpha=0.0000 mean_alpha=0.0338 median_alpha=0.0273 max_alpha=0.2853 beta=0.0040

22:45:57 - INFO - EM Iter  48: ll=-1832.3725 log_delta_p=-7.3638 log_delta_a=-12.6418 min_alpha=0.0000 mean_alpha=0.0336 median_alpha=0.0271 max_alpha=0.2852 beta=0.0041

22:45:57 - INFO - EM Iter  49: ll=-1832.3696 log_delta_p=-7.4184 log_delta_a=-12.6736 min_alpha=0.0000 mean_alpha=0.0334 median_alpha=0.0268 max_alpha=0.2850 beta=0.0041

22:45:57 - INFO - EM Iter  50: ll=-1832.3670 log_delta_p=-7.4727 log_delta_a=-12.6272 min_alpha=0.0000 mean_alpha=0.0332 median_alpha=0.0266 max_alpha=0.2848 beta=0.0041

22:45:57 - INFO - EM Iter  51: ll=-1832.3643 log_delta_p=-7.5271 log_delta_a=-12.7128 min_alpha=0.0000 mean_alpha=0.0330 median_alpha=0.0265 max_alpha=0.2846 beta=0.0042

22:45:57 - INFO - EM Iter  52: ll=-1832.3616 log_delta_p=-7.5832 log_delta_a=-12.8200 min_alpha=0.0000 mean_alpha=0.0328 median_alpha=0.0263 max_alpha=0.2844 beta=0.0042

22:45:58 - INFO - EM Iter  53: ll=-1832.3595 log_delta_p=-7.6376 log_delta_a=-12.8163 min_alpha=0.0000 mean_alpha=0.0327 median_alpha=0.0261 max_alpha=0.2842 beta=0.0042

22:45:58 - INFO - EM Iter  54: ll=-1832.3571 log_delta_p=-7.6893 log_delta_a=-13.0307 min_alpha=0.0000 mean_alpha=0.0325 median_alpha=0.0259 max_alpha=0.2840 beta=0.0042

22:45:58 - INFO - EM Iter  55: ll=-1832.3550 log_delta_p=-7.7374 log_delta_a=-13.0193 min_alpha=0.0000 mean_alpha=0.0323 median_alpha=0.0258 max_alpha=0.2838 beta=0.0043

22:45:58 - INFO - EM Iter  56: ll=-1832.3528 log_delta_p=-7.7802 log_delta_a=-12.7927 min_alpha=0.0000 mean_alpha=0.0322 median_alpha=0.0257 max_alpha=0.2836 beta=0.0043

22:45:58 - INFO - EM Iter  57: ll=-1832.3506 log_delta_p=-7.8154 log_delta_a=-12.7570 min_alpha=0.0000 mean_alpha=0.0320 median_alpha=0.0255 max_alpha=0.2834 beta=0.0043

22:45:58 - INFO - EM Iter  58: ll=-1832.3488 log_delta_p=-7.8429 log_delta_a=-12.7735 min_alpha=0.0000 mean_alpha=0.0318 median_alpha=0.0254 max_alpha=0.2832 beta=0.0044

22:45:58 - INFO - EM Iter  59: ll=-1832.3467 log_delta_p=-7.8635 log_delta_a=-12.6712 min_alpha=0.0000 mean_alpha=0.0317 median_alpha=0.0252 max_alpha=0.2830 beta=0.0044

22:45:58 - INFO - EM Iter  60: ll=-1832.3450 log_delta_p=-7.8810 log_delta_a=-12.6265 min_alpha=0.0000 mean_alpha=0.0315 median_alpha=0.0250 max_alpha=0.2828 beta=0.0044

22:45:58 - INFO - EM Iter  61: ll=-1832.3430 log_delta_p=-7.9021 log_delta_a=-12.7095 min_alpha=0.0000 mean_alpha=0.0314 median_alpha=0.0249 max_alpha=0.2826 beta=0.0044

22:45:58 - INFO - EM Iter  62: ll=-1832.3413 log_delta_p=-7.9285 log_delta_a=-12.6265 min_alpha=0.0000 mean_alpha=0.0313 median_alpha=0.0247 max_alpha=0.2824 beta=0.0045

22:45:59 - INFO - EM Iter  63: ll=-1832.3398 log_delta_p=-7.9561 log_delta_a=-12.6189 min_alpha=0.0000 mean_alpha=0.0311 median_alpha=0.0246 max_alpha=0.2822 beta=0.0045

22:45:59 - INFO - EM Iter  64: ll=-1832.3381 log_delta_p=-7.9782 log_delta_a=-12.6231 min_alpha=0.0000 mean_alpha=0.0310 median_alpha=0.0245 max_alpha=0.2820 beta=0.0045

22:45:59 - INFO - EM Iter  65: ll=-1832.3366 log_delta_p=-7.9941 log_delta_a=-12.6489 min_alpha=0.0000 mean_alpha=0.0308 median_alpha=0.0243 max_alpha=0.2818 beta=0.0045

22:45:59 - INFO - EM Iter  66: ll=-1832.3352 log_delta_p=-8.0058 log_delta_a=-12.5962 min_alpha=0.0000 mean_alpha=0.0307 median_alpha=0.0242 max_alpha=0.2817 beta=0.0046

22:45:59 - INFO - EM Iter  67: ll=-1832.3338 log_delta_p=-8.0202 log_delta_a=-12.6589 min_alpha=0.0000 mean_alpha=0.0306 median_alpha=0.0240 max_alpha=0.2815 beta=0.0046

22:45:59 - INFO - EM Iter  68: ll=-1832.3323 log_delta_p=-8.0410 log_delta_a=-12.6762 min_alpha=0.0000 mean_alpha=0.0305 median_alpha=0.0239 max_alpha=0.2813 beta=0.0046

22:45:59 - INFO - EM Iter  69: ll=-1832.3309 log_delta_p=-8.0683 log_delta_a=-12.6990 min_alpha=0.0000 mean_alpha=0.0304 median_alpha=0.0238 max_alpha=0.2811 beta=0.0046

22:45:59 - INFO - EM Iter  70: ll=-1832.3294 log_delta_p=-8.1012 log_delta_a=-12.6957 min_alpha=0.0000 mean_alpha=0.0302 median_alpha=0.0237 max_alpha=0.2809 beta=0.0046

22:45:59 - INFO - EM Iter  71: ll=-1832.3283 log_delta_p=-8.1350 log_delta_a=-12.7608 min_alpha=0.0000 mean_alpha=0.0301 median_alpha=0.0236 max_alpha=0.2808 beta=0.0047

22:45:59 - INFO - EM Iter  72: ll=-1832.3270 log_delta_p=-8.1693 log_delta_a=-12.6572 min_alpha=0.0000 mean_alpha=0.0300 median_alpha=0.0235 max_alpha=0.2806 beta=0.0047

22:46:00 - INFO - EM Iter  73: ll=-1832.3261 log_delta_p=-8.2028 log_delta_a=-12.6625 min_alpha=0.0000 mean_alpha=0.0299 median_alpha=0.0234 max_alpha=0.2805 beta=0.0047

22:46:00 - INFO - EM Iter  74: ll=-1832.3248 log_delta_p=-8.2356 log_delta_a=-12.7238 min_alpha=0.0000 mean_alpha=0.0298 median_alpha=0.0233 max_alpha=0.2803 beta=0.0047

22:46:00 - INFO - EM Iter  75: ll=-1832.3235 log_delta_p=-8.2680 log_delta_a=-12.6513 min_alpha=0.0000 mean_alpha=0.0297 median_alpha=0.0232 max_alpha=0.2802 beta=0.0047

22:46:00 - INFO - EM Iter  76: ll=-1832.3226 log_delta_p=-8.3023 log_delta_a=-12.6726 min_alpha=0.0000 mean_alpha=0.0296 median_alpha=0.0231 max_alpha=0.2800 beta=0.0048

22:46:00 - INFO - EM Iter  77: ll=-1832.3214 log_delta_p=-8.3389 log_delta_a=-12.7350 min_alpha=0.0000 mean_alpha=0.0295 median_alpha=0.0230 max_alpha=0.2799 beta=0.0048

22:46:00 - INFO - EM Iter  78: ll=-1832.3202 log_delta_p=-8.3773 log_delta_a=-12.6329 min_alpha=0.0000 mean_alpha=0.0294 median_alpha=0.0229 max_alpha=0.2797 beta=0.0048

22:46:00 - INFO - EM Iter  79: ll=-1832.3195 log_delta_p=-8.4169 log_delta_a=-12.6417 min_alpha=0.0000 mean_alpha=0.0293 median_alpha=0.0228 max_alpha=0.2796 beta=0.0048

22:46:00 - INFO - EM Iter  80: ll=-1832.3182 log_delta_p=-8.4597 log_delta_a=-12.6799 min_alpha=0.0000 mean_alpha=0.0292 median_alpha=0.0227 max_alpha=0.2794 beta=0.0048

22:46:00 - INFO - EM Iter  81: ll=-1832.3176 log_delta_p=-8.4800 log_delta_a=-12.6303 min_alpha=0.0000 mean_alpha=0.0291 median_alpha=0.0226 max_alpha=0.2793 beta=0.0048

22:46:00 - INFO - EM Iter  82: ll=-1832.3165 log_delta_p=-8.5135 log_delta_a=-12.7055 min_alpha=0.0000 mean_alpha=0.0290 median_alpha=0.0226 max_alpha=0.2792 beta=0.0049

22:46:01 - INFO - EM Iter  83: ll=-1832.3157 log_delta_p=-8.5593 log_delta_a=-12.7048 min_alpha=0.0000 mean_alpha=0.0289 median_alpha=0.0225 max_alpha=0.2790 beta=0.0049

22:46:01 - INFO - EM Iter  84: ll=-1832.3147 log_delta_p=-8.5759 log_delta_a=-12.7677 min_alpha=0.0000 mean_alpha=0.0288 median_alpha=0.0224 max_alpha=0.2789 beta=0.0049

22:46:01 - INFO - EM Iter  85: ll=-1832.3141 log_delta_p=-8.5894 log_delta_a=-12.7635 min_alpha=0.0000 mean_alpha=0.0287 median_alpha=0.0223 max_alpha=0.2788 beta=0.0049

22:46:01 - INFO - EM Iter  86: ll=-1832.3133 log_delta_p=-8.6023 log_delta_a=-12.7545 min_alpha=0.0000 mean_alpha=0.0287 median_alpha=0.0222 max_alpha=0.2787 beta=0.0049

22:46:01 - INFO - EM Iter  87: ll=-1832.3123 log_delta_p=-8.6129 log_delta_a=-12.7448 min_alpha=0.0000 mean_alpha=0.0286 median_alpha=0.0221 max_alpha=0.2786 beta=0.0049

22:46:01 - INFO - EM Iter  88: ll=-1832.3115 log_delta_p=-8.6236 log_delta_a=-12.7978 min_alpha=0.0000 mean_alpha=0.0285 median_alpha=0.0220 max_alpha=0.2785 beta=0.0049

22:46:01 - INFO - EM Iter  89: ll=-1832.3107 log_delta_p=-8.6334 log_delta_a=-12.7240 min_alpha=0.0000 mean_alpha=0.0284 median_alpha=0.0220 max_alpha=0.2784 beta=0.0050

22:46:01 - INFO - EM Iter  90: ll=-1832.3099 log_delta_p=-8.6427 log_delta_a=-12.6939 min_alpha=0.0000 mean_alpha=0.0283 median_alpha=0.0219 max_alpha=0.2783 beta=0.0050

22:46:01 - INFO - EM Iter  91: ll=-1832.3094 log_delta_p=-8.6512 log_delta_a=-12.6907 min_alpha=0.0000 mean_alpha=0.0283 median_alpha=0.0218 max_alpha=0.2782 beta=0.0050

22:46:01 - INFO - EM Iter  92: ll=-1832.3088 log_delta_p=-8.6610 log_delta_a=-12.6813 min_alpha=0.0000 mean_alpha=0.0282 median_alpha=0.0218 max_alpha=0.2781 beta=0.0050

22:46:02 - INFO - EM Iter  93: ll=-1832.3080 log_delta_p=-8.6724 log_delta_a=-12.7216 min_alpha=0.0000 mean_alpha=0.0281 median_alpha=0.0217 max_alpha=0.2780 beta=0.0050

22:46:02 - INFO - EM Iter  94: ll=-1832.3075 log_delta_p=-8.6868 log_delta_a=-12.6367 min_alpha=0.0000 mean_alpha=0.0280 median_alpha=0.0217 max_alpha=0.2780 beta=0.0050

22:46:02 - INFO - EM Iter  95: ll=-1832.3067 log_delta_p=-8.7028 log_delta_a=-12.6205 min_alpha=0.0000 mean_alpha=0.0280 median_alpha=0.0216 max_alpha=0.2779 beta=0.0050

22:46:02 - INFO - EM Iter  96: ll=-1832.3061 log_delta_p=-8.7212 log_delta_a=-12.6501 min_alpha=0.0000 mean_alpha=0.0279 median_alpha=0.0215 max_alpha=0.2778 beta=0.0050

22:46:02 - INFO - EM Iter  97: ll=-1832.3056 log_delta_p=-8.7414 log_delta_a=-12.7179 min_alpha=0.0000 mean_alpha=0.0278 median_alpha=0.0214 max_alpha=0.2777 beta=0.0051

22:46:02 - INFO - EM Iter  98: ll=-1832.3050 log_delta_p=-8.7652 log_delta_a=-12.7162 min_alpha=0.0000 mean_alpha=0.0278 median_alpha=0.0214 max_alpha=0.2776 beta=0.0051

22:46:02 - INFO - EM Iter  99: ll=-1832.3046 log_delta_p=-8.7927 log_delta_a=-12.7140 min_alpha=0.0000 mean_alpha=0.0277 median_alpha=0.0213 max_alpha=0.2776 beta=0.0051

22:46:02 - INFO - EM Iter 100: ll=-1832.3038 log_delta_p=-8.8228 log_delta_a=-12.6903 min_alpha=0.0000 mean_alpha=0.0276 median_alpha=0.0213 max_alpha=0.2775 beta=0.0051

22:46:02 - INFO - EM Iter 101: ll=-1832.3034 log_delta_p=-8.8561 log_delta_a=-12.7025 min_alpha=0.0000 mean_alpha=0.0276 median_alpha=0.0212 max_alpha=0.2774 beta=0.0051

22:46:02 - INFO - EM Iter 102: ll=-1832.3027 log_delta_p=-8.8908 log_delta_a=-12.7351 min_alpha=0.0000 mean_alpha=0.0275 median_alpha=0.0212 max_alpha=0.2773 beta=0.0051

22:46:03 - INFO - EM Iter 103: ll=-1832.3022 log_delta_p=-8.9210 log_delta_a=-12.7236 min_alpha=0.0000 mean_alpha=0.0275 median_alpha=0.0211 max_alpha=0.2773 beta=0.0051

22:46:03 - INFO - EM Iter 104: ll=-1832.3018 log_delta_p=-8.9292 log_delta_a=-12.7724 min_alpha=0.0000 mean_alpha=0.0274 median_alpha=0.0211 max_alpha=0.2772 beta=0.0051

22:46:03 - INFO - EM Iter 105: ll=-1832.3013 log_delta_p=-8.9403 log_delta_a=-12.7178 min_alpha=0.0000 mean_alpha=0.0274 median_alpha=0.0210 max_alpha=0.2771 beta=0.0051

22:46:03 - INFO - EM Iter 106: ll=-1832.3006 log_delta_p=-8.9545 log_delta_a=-12.7721 min_alpha=0.0000 mean_alpha=0.0273 median_alpha=0.0210 max_alpha=0.2771 beta=0.0051

22:46:03 - INFO - EM Iter 107: ll=-1832.3003 log_delta_p=-8.9685 log_delta_a=-12.7656 min_alpha=0.0000 mean_alpha=0.0272 median_alpha=0.0209 max_alpha=0.2770 beta=0.0052

22:46:03 - INFO - EM Iter 108: ll=-1832.2998 log_delta_p=-8.9832 log_delta_a=-12.7700 min_alpha=0.0000 mean_alpha=0.0272 median_alpha=0.0209 max_alpha=0.2769 beta=0.0052

22:46:03 - INFO - EM Iter 109: ll=-1832.2994 log_delta_p=-8.9969 log_delta_a=-12.8395 min_alpha=0.0000 mean_alpha=0.0271 median_alpha=0.0208 max_alpha=0.2769 beta=0.0052

22:46:03 - INFO - EM Iter 110: ll=-1832.2990 log_delta_p=-9.0101 log_delta_a=-12.8881 min_alpha=0.0000 mean_alpha=0.0271 median_alpha=0.0208 max_alpha=0.2768 beta=0.0052

22:46:03 - INFO - EM Iter 111: ll=-1832.2986 log_delta_p=-9.0214 log_delta_a=-12.8054 min_alpha=0.0000 mean_alpha=0.0270 median_alpha=0.0208 max_alpha=0.2768 beta=0.0052

22:46:04 - INFO - EM Iter 112: ll=-1832.2981 log_delta_p=-9.0343 log_delta_a=-12.7935 min_alpha=0.0000 mean_alpha=0.0270 median_alpha=0.0207 max_alpha=0.2767 beta=0.0052

22:46:04 - INFO - EM Iter 113: ll=-1832.2978 log_delta_p=-9.0360 log_delta_a=-12.7780 min_alpha=0.0000 mean_alpha=0.0269 median_alpha=0.0207 max_alpha=0.2767 beta=0.0052

22:46:04 - INFO - EM Iter 114: ll=-1832.2974 log_delta_p=-9.0257 log_delta_a=-12.8461 min_alpha=0.0000 mean_alpha=0.0269 median_alpha=0.0206 max_alpha=0.2766 beta=0.0052

22:46:04 - INFO - EM Iter 115: ll=-1832.2973 log_delta_p=-9.0158 log_delta_a=-12.9096 min_alpha=0.0000 mean_alpha=0.0269 median_alpha=0.0205 max_alpha=0.2766 beta=0.0052

22:46:04 - INFO - EM Iter 116: ll=-1832.2970 log_delta_p=-9.0051 log_delta_a=-12.9362 min_alpha=0.0000 mean_alpha=0.0268 median_alpha=0.0205 max_alpha=0.2765 beta=0.0052

22:46:04 - INFO - EM Iter 117: ll=-1832.2963 log_delta_p=-8.9921 log_delta_a=-12.9030 min_alpha=0.0000 mean_alpha=0.0268 median_alpha=0.0205 max_alpha=0.2765 beta=0.0052

22:46:04 - INFO - EM Iter 118: ll=-1832.2960 log_delta_p=-8.9777 log_delta_a=-12.9689 min_alpha=0.0000 mean_alpha=0.0267 median_alpha=0.0204 max_alpha=0.2764 beta=0.0052

22:46:04 - INFO - EM Iter 119: ll=-1832.2957 log_delta_p=-8.9594 log_delta_a=-12.9121 min_alpha=0.0000 mean_alpha=0.0267 median_alpha=0.0204 max_alpha=0.2764 beta=0.0052

22:46:04 - INFO - EM Iter 120: ll=-1832.2954 log_delta_p=-8.9416 log_delta_a=-12.8692 min_alpha=0.0000 mean_alpha=0.0266 median_alpha=0.0203 max_alpha=0.2763 beta=0.0053

22:46:04 - INFO - EM Iter 121: ll=-1832.2952 log_delta_p=-8.9253 log_delta_a=-12.7676 min_alpha=0.0000 mean_alpha=0.0266 median_alpha=0.0203 max_alpha=0.2763 beta=0.0053

22:46:05 - INFO - EM Iter 122: ll=-1832.2949 log_delta_p=-8.9136 log_delta_a=-12.8602 min_alpha=0.0000 mean_alpha=0.0266 median_alpha=0.0203 max_alpha=0.2762 beta=0.0053

22:46:05 - INFO - EM Iter 123: ll=-1832.2944 log_delta_p=-8.9064 log_delta_a=-12.8843 min_alpha=0.0000 mean_alpha=0.0265 median_alpha=0.0203 max_alpha=0.2762 beta=0.0053

22:46:05 - INFO - EM Iter 124: ll=-1832.2939 log_delta_p=-8.9058 log_delta_a=-12.8683 min_alpha=0.0000 mean_alpha=0.0265 median_alpha=0.0202 max_alpha=0.2761 beta=0.0053

22:46:05 - INFO - EM Iter 125: ll=-1832.2939 log_delta_p=-8.9111 log_delta_a=-12.8811 min_alpha=0.0000 mean_alpha=0.0264 median_alpha=0.0202 max_alpha=0.2761 beta=0.0053

22:46:05 - INFO - EM Iter 126: ll=-1832.2936 log_delta_p=-8.9229 log_delta_a=-12.8878 min_alpha=0.0000 mean_alpha=0.0264 median_alpha=0.0201 max_alpha=0.2761 beta=0.0053

22:46:05 - INFO - EM Iter 127: ll=-1832.2933 log_delta_p=-8.9400 log_delta_a=-12.9402 min_alpha=0.0000 mean_alpha=0.0264 median_alpha=0.0201 max_alpha=0.2760 beta=0.0053

22:46:05 - INFO - EM Iter 128: ll=-1832.2930 log_delta_p=-8.9647 log_delta_a=-12.8894 min_alpha=0.0000 mean_alpha=0.0263 median_alpha=0.0201 max_alpha=0.2760 beta=0.0053

22:46:05 - INFO - EM Iter 129: ll=-1832.2928 log_delta_p=-8.9939 log_delta_a=-12.8375 min_alpha=0.0000 mean_alpha=0.0263 median_alpha=0.0200 max_alpha=0.2760 beta=0.0053

22:46:05 - INFO - EM Iter 130: ll=-1832.2926 log_delta_p=-9.0270 log_delta_a=-12.8257 min_alpha=0.0000 mean_alpha=0.0263 median_alpha=0.0200 max_alpha=0.2759 beta=0.0053

22:46:05 - INFO - EM Iter 131: ll=-1832.2923 log_delta_p=-9.0607 log_delta_a=-12.9540 min_alpha=0.0000 mean_alpha=0.0262 median_alpha=0.0200 max_alpha=0.2759 beta=0.0053

22:46:06 - INFO - EM Iter 132: ll=-1832.2922 log_delta_p=-9.0931 log_delta_a=-12.8994 min_alpha=0.0000 mean_alpha=0.0262 median_alpha=0.0199 max_alpha=0.2759 beta=0.0053

22:46:06 - INFO - EM Iter 133: ll=-1832.2915 log_delta_p=-9.1227 log_delta_a=-12.9759 min_alpha=0.0000 mean_alpha=0.0262 median_alpha=0.0199 max_alpha=0.2759 beta=0.0053

22:46:06 - INFO - EM Iter 134: ll=-1832.2912 log_delta_p=-9.1488 log_delta_a=-12.9262 min_alpha=0.0000 mean_alpha=0.0261 median_alpha=0.0199 max_alpha=0.2758 beta=0.0053

22:46:06 - INFO - EM Iter 135: ll=-1832.2912 log_delta_p=-9.1690 log_delta_a=-12.9571 min_alpha=0.0000 mean_alpha=0.0261 median_alpha=0.0198 max_alpha=0.2758 beta=0.0053

22:46:06 - INFO - EM Iter 136: ll=-1832.2907 log_delta_p=-9.1848 log_delta_a=-12.9636 min_alpha=0.0000 mean_alpha=0.0261 median_alpha=0.0198 max_alpha=0.2758 beta=0.0053

22:46:06 - INFO - EM Iter 137: ll=-1832.2906 log_delta_p=-9.1971 log_delta_a=-12.9452 min_alpha=0.0000 mean_alpha=0.0260 median_alpha=0.0198 max_alpha=0.2758 beta=0.0054

22:46:06 - INFO - EM Iter 138: ll=-1832.2906 log_delta_p=-9.2063 log_delta_a=-13.0822 min_alpha=0.0000 mean_alpha=0.0260 median_alpha=0.0197 max_alpha=0.2758 beta=0.0054

22:46:06 - INFO - EM Iter 139: ll=-1832.2902 log_delta_p=-9.2145 log_delta_a=-12.9612 min_alpha=0.0000 mean_alpha=0.0260 median_alpha=0.0197 max_alpha=0.2757 beta=0.0054

22:46:06 - INFO - Converged.

22:46:07 - INFO - Saving inferred adata to '/home/mcaskey/cellsweep/notebooks/data/simulation1_small_noise/celltype_granularity/adata_cellsweep_leiden_20.h5ad'

leiden_20 done

22:46:07 - INFO - Starting cellsweep denoising at 2026-10-03 22:46:07, cellsweep version 0.1.3

22:46:07 - INFO - Inferring celltype profiles.

22:46:07 - INFO - Number of celltypes: 12

22:46:08 - INFO - Inferring the ambient profile from empty droplets.

Logging to /home/mcaskey/cellsweep/notebooks/data/simulation1_small_noise/celltype_granularity/cellsweep_shuffled.log

22:46:08 - INFO - adata.obs does not have 'init_alpha'. Setting to `init_alpha` argument.

22:46:08 - INFO - Performing Sparse EM with 32 Numba thread(s)

22:46:08 - INFO - EM Iter   1: ll=-1999.0083 log_delta_p=inf log_delta_a=inf min_alpha=0.6043 mean_alpha=0.7013 median_alpha=0.7017 max_alpha=0.7617 beta=0.0101

22:46:08 - INFO - EM Iter   2: ll=-2005.1312 log_delta_p=inf log_delta_a=inf min_alpha=0.4865 mean_alpha=0.6981 median_alpha=0.6995 max_alpha=0.8362 beta=0.0103

22:46:08 - INFO - EM Iter   3: ll=-2004.6565 log_delta_p=-2.2053 log_delta_a=-10.3832 min_alpha=0.3860 mean_alpha=0.6949 median_alpha=0.6981 max_alpha=0.9000 beta=0.0106

22:46:08 - INFO - EM Iter   4: ll=-2003.9682 log_delta_p=-2.5881 log_delta_a=-11.6114 min_alpha=0.3060 mean_alpha=0.6914 median_alpha=0.6976 max_alpha=0.9000 beta=0.0109

22:46:08 - INFO - EM Iter   5: ll=-2002.9544 log_delta_p=-2.8684 log_delta_a=-11.7404 min_alpha=0.2433 mean_alpha=0.6875 median_alpha=0.6994 max_alpha=0.9000 beta=0.0111

22:46:08 - INFO - EM Iter   6: ll=-2001.5165 log_delta_p=-2.7888 log_delta_a=-11.6745 min_alpha=0.1727 mean_alpha=0.6829 median_alpha=0.7036 max_alpha=0.9000 beta=0.0114

22:46:08 - INFO - EM Iter   7: ll=-1999.4998 log_delta_p=-2.7782 log_delta_a=-11.7185 min_alpha=0.1120 mean_alpha=0.6767 median_alpha=0.7113 max_alpha=0.9000 beta=0.0115

22:46:08 - INFO - EM Iter   8: ll=-1996.8843 log_delta_p=-2.8033 log_delta_a=-12.0156 min_alpha=0.0705 mean_alpha=0.6676 median_alpha=0.7226 max_alpha=0.9000 beta=0.0116

22:46:08 - INFO - EM Iter   9: ll=-1993.2002 log_delta_p=-1.4512 log_delta_a=-11.9270 min_alpha=0.0428 mean_alpha=0.6531 median_alpha=0.7295 max_alpha=0.9000 beta=0.0117

22:46:08 - INFO - EM Iter  10: ll=-1987.2677 log_delta_p=-0.9483 log_delta_a=-12.3020 min_alpha=0.0259 mean_alpha=0.6314 median_alpha=0.7067 max_alpha=0.9000 beta=0.0116

22:46:08 - INFO - EM Iter  11: ll=-1978.7822 log_delta_p=-1.1808 log_delta_a=-12.6229 min_alpha=0.0159 mean_alpha=0.6011 median_alpha=0.6492 max_alpha=0.9000 beta=0.0114

22:46:08 - INFO - EM Iter  12: ll=-1970.1186 log_delta_p=-1.0954 log_delta_a=-12.3823 min_alpha=0.0100 mean_alpha=0.5667 median_alpha=0.5787 max_alpha=0.9000 beta=0.0110

22:46:08 - INFO - EM Iter  13: ll=-1962.7442 log_delta_p=-1.8599 log_delta_a=-11.7790 min_alpha=0.0066 mean_alpha=0.5321 median_alpha=0.5111 max_alpha=0.9000 beta=0.0107

22:46:08 - INFO - EM Iter  14: ll=-1954.8883 log_delta_p=-1.9257 log_delta_a=-11.5845 min_alpha=0.0047 mean_alpha=0.4908 median_alpha=0.4532 max_alpha=0.9000 beta=0.0103

22:46:08 - INFO - EM Iter  15: ll=-1946.9843 log_delta_p=-1.5497 log_delta_a=-11.4752 min_alpha=0.0043 mean_alpha=0.4446 median_alpha=0.4000 max_alpha=0.9000 beta=0.0098

22:46:08 - INFO - EM Iter  16: ll=-1937.6686 log_delta_p=-1.3091 log_delta_a=-11.2943 min_alpha=0.0054 mean_alpha=0.3953 median_alpha=0.3528 max_alpha=0.9000 beta=0.0092

22:46:08 - INFO - EM Iter  17: ll=-1930.7822 log_delta_p=-2.4411 log_delta_a=-11.1040 min_alpha=0.0073 mean_alpha=0.3500 median_alpha=0.3046 max_alpha=0.9000 beta=0.0086

22:46:08 - INFO - EM Iter  18: ll=-1925.6069 log_delta_p=-2.7137 log_delta_a=-11.0143 min_alpha=0.0078 mean_alpha=0.3117 median_alpha=0.2651 max_alpha=0.9000 beta=0.0081

22:46:08 - INFO - EM Iter  19: ll=-1921.6168 log_delta_p=-2.4084 log_delta_a=-11.0185 min_alpha=0.0064 mean_alpha=0.2790 median_alpha=0.2275 max_alpha=0.9000 beta=0.0076

22:46:08 - INFO - EM Iter  20: ll=-1918.2875 log_delta_p=-2.3444 log_delta_a=-11.1158 min_alpha=0.0053 mean_alpha=0.2508 median_alpha=0.1938 max_alpha=0.9000 beta=0.0071

22:46:08 - INFO - EM Iter  21: ll=-1915.4576 log_delta_p=-2.5041 log_delta_a=-11.1658 min_alpha=0.0045 mean_alpha=0.2267 median_alpha=0.1642 max_alpha=0.9000 beta=0.0067

22:46:08 - INFO - EM Iter  22: ll=-1913.1251 log_delta_p=-2.7359 log_delta_a=-11.1849 min_alpha=0.0040 mean_alpha=0.2056 median_alpha=0.1395 max_alpha=0.9000 beta=0.0063

22:46:08 - INFO - EM Iter  23: ll=-1910.4795 log_delta_p=-2.9801 log_delta_a=-11.2475 min_alpha=0.0036 mean_alpha=0.1858 median_alpha=0.1190 max_alpha=0.9000 beta=0.0059

22:46:08 - INFO - EM Iter  24: ll=-1907.5541 log_delta_p=-3.2395 log_delta_a=-11.3179 min_alpha=0.0034 mean_alpha=0.1660 median_alpha=0.1019 max_alpha=0.9000 beta=0.0056

22:46:08 - INFO - EM Iter  25: ll=-1904.3461 log_delta_p=-3.0901 log_delta_a=-11.3938 min_alpha=0.0032 mean_alpha=0.1467 median_alpha=0.0878 max_alpha=0.9000 beta=0.0053

22:46:08 - INFO - EM Iter  26: ll=-1901.8509 log_delta_p=-3.7412 log_delta_a=-11.5252 min_alpha=0.0027 mean_alpha=0.1299 median_alpha=0.0771 max_alpha=0.9000 beta=0.0051

22:46:08 - INFO - EM Iter  27: ll=-1899.9456 log_delta_p=-3.3285 log_delta_a=-11.6897 min_alpha=0.0024 mean_alpha=0.1162 median_alpha=0.0683 max_alpha=0.9000 beta=0.0049

22:46:08 - INFO - EM Iter  28: ll=-1898.5986 log_delta_p=-4.2289 log_delta_a=-11.8266 min_alpha=0.0021 mean_alpha=0.1048 median_alpha=0.0615 max_alpha=0.9000 beta=0.0048

22:46:08 - INFO - EM Iter  29: ll=-1897.4314 log_delta_p=-3.7974 log_delta_a=-11.9740 min_alpha=0.0018 mean_alpha=0.0949 median_alpha=0.0564 max_alpha=0.9000 beta=0.0047

22:46:08 - INFO - EM Iter  30: ll=-1895.6835 log_delta_p=-3.9188 log_delta_a=-12.0856 min_alpha=0.0017 mean_alpha=0.0844 median_alpha=0.0522 max_alpha=0.9000 beta=0.0046

22:46:08 - INFO - EM Iter  31: ll=-1894.2858 log_delta_p=-3.5746 log_delta_a=-12.3407 min_alpha=0.0015 mean_alpha=0.0750 median_alpha=0.0492 max_alpha=0.9000 beta=0.0045

22:46:08 - INFO - EM Iter  32: ll=-1893.2597 log_delta_p=-2.3841 log_delta_a=-12.3510 min_alpha=0.0014 mean_alpha=0.0677 median_alpha=0.0469 max_alpha=0.9000 beta=0.0045

22:46:08 - INFO - EM Iter  33: ll=-1892.6579 log_delta_p=-4.0293 log_delta_a=-12.5985 min_alpha=0.0013 mean_alpha=0.0621 median_alpha=0.0448 max_alpha=0.9000 beta=0.0045

22:46:09 - INFO - EM Iter  34: ll=-1892.2701 log_delta_p=-3.5178 log_delta_a=-12.6179 min_alpha=0.0012 mean_alpha=0.0578 median_alpha=0.0432 max_alpha=0.9000 beta=0.0046

22:46:09 - INFO - EM Iter  35: ll=-1892.0024 log_delta_p=-3.6444 log_delta_a=-12.8880 min_alpha=0.0011 mean_alpha=0.0545 median_alpha=0.0417 max_alpha=0.8845 beta=0.0046

22:46:09 - INFO - EM Iter  36: ll=-1891.8272 log_delta_p=-3.9493 log_delta_a=-12.9422 min_alpha=0.0010 mean_alpha=0.0519 median_alpha=0.0405 max_alpha=0.9000 beta=0.0047

22:46:09 - INFO - EM Iter  37: ll=-1891.7146 log_delta_p=-4.2916 log_delta_a=-12.5441 min_alpha=0.0010 mean_alpha=0.0500 median_alpha=0.0394 max_alpha=0.9000 beta=0.0047

22:46:09 - INFO - EM Iter  38: ll=-1891.6410 log_delta_p=-4.6539 log_delta_a=-12.5847 min_alpha=0.0009 mean_alpha=0.0485 median_alpha=0.0384 max_alpha=0.9000 beta=0.0048

22:46:09 - INFO - EM Iter  39: ll=-1891.5915 log_delta_p=-5.0240 log_delta_a=-12.4283 min_alpha=0.0008 mean_alpha=0.0473 median_alpha=0.0376 max_alpha=0.8151 beta=0.0049

22:46:09 - INFO - EM Iter  40: ll=-1891.5606 log_delta_p=-5.3689 log_delta_a=-12.3193 min_alpha=0.0008 mean_alpha=0.0464 median_alpha=0.0372 max_alpha=0.6976 beta=0.0051

22:46:09 - INFO - EM Iter  41: ll=-1891.5397 log_delta_p=-5.7350 log_delta_a=-12.3142 min_alpha=0.0007 mean_alpha=0.0456 median_alpha=0.0365 max_alpha=0.5640 beta=0.0052

22:46:09 - INFO - EM Iter  42: ll=-1891.5254 log_delta_p=-6.0989 log_delta_a=-12.2422 min_alpha=0.0006 mean_alpha=0.0450 median_alpha=0.0361 max_alpha=0.4384 beta=0.0053

22:46:09 - INFO - EM Iter  43: ll=-1891.5155 log_delta_p=-6.4585 log_delta_a=-12.1681 min_alpha=0.0006 mean_alpha=0.0445 median_alpha=0.0356 max_alpha=0.3985 beta=0.0055

22:46:09 - INFO - EM Iter  44: ll=-1891.5086 log_delta_p=-6.8123 log_delta_a=-12.1428 min_alpha=0.0005 mean_alpha=0.0440 median_alpha=0.0352 max_alpha=0.3980 beta=0.0056

22:46:09 - INFO - EM Iter  45: ll=-1891.5034 log_delta_p=-7.1602 log_delta_a=-12.0762 min_alpha=0.0005 mean_alpha=0.0436 median_alpha=0.0348 max_alpha=0.3974 beta=0.0058

22:46:09 - INFO - EM Iter  46: ll=-1891.4995 log_delta_p=-7.5026 log_delta_a=-12.0393 min_alpha=0.0004 mean_alpha=0.0433 median_alpha=0.0346 max_alpha=0.3968 beta=0.0059

22:46:09 - INFO - EM Iter  47: ll=-1891.4963 log_delta_p=-7.8394 log_delta_a=-12.1102 min_alpha=0.0004 mean_alpha=0.0430 median_alpha=0.0343 max_alpha=0.3960 beta=0.0061

22:46:09 - INFO - EM Iter  48: ll=-1891.4938 log_delta_p=-8.1715 log_delta_a=-12.1087 min_alpha=0.0004 mean_alpha=0.0427 median_alpha=0.0341 max_alpha=0.3952 beta=0.0063

22:46:09 - INFO - EM Iter  49: ll=-1891.4910 log_delta_p=-8.3655 log_delta_a=-12.1937 min_alpha=0.0003 mean_alpha=0.0424 median_alpha=0.0339 max_alpha=0.3943 beta=0.0064

22:46:09 - INFO - EM Iter  50: ll=-1883.6506 log_delta_p=-8.4277 log_delta_a=-12.1008 min_alpha=0.0003 mean_alpha=0.0421 median_alpha=0.0337 max_alpha=0.3934 beta=0.0064

22:46:09 - INFO - EM Iter  51: ll=-1883.6496 log_delta_p=-8.4865 log_delta_a=-11.2310 min_alpha=0.0003 mean_alpha=0.0419 median_alpha=0.0335 max_alpha=0.3924 beta=0.0064

22:46:09 - INFO - EM Iter  52: ll=-1883.6491 log_delta_p=-8.3363 log_delta_a=-14.0410 min_alpha=0.0002 mean_alpha=0.0418 median_alpha=0.0333 max_alpha=0.3913 beta=0.0064

22:46:09 - INFO - EM Iter  53: ll=-1883.6486 log_delta_p=-8.4149 log_delta_a=-12.8582 min_alpha=0.0002 mean_alpha=0.0416 median_alpha=0.0332 max_alpha=0.3902 beta=0.0065

22:46:09 - INFO - EM Iter  54: ll=-1883.6480 log_delta_p=-8.4895 log_delta_a=-12.7100 min_alpha=0.0002 mean_alpha=0.0415 median_alpha=0.0331 max_alpha=0.3891 beta=0.0065

22:46:09 - INFO - EM Iter  55: ll=-1883.6477 log_delta_p=-8.5588 log_delta_a=-12.6230 min_alpha=0.0002 mean_alpha=0.0414 median_alpha=0.0330 max_alpha=0.3880 beta=0.0065

22:46:09 - INFO - EM Iter  56: ll=-1883.6475 log_delta_p=-8.6238 log_delta_a=-12.6833 min_alpha=0.0001 mean_alpha=0.0412 median_alpha=0.0330 max_alpha=0.3868 beta=0.0065

22:46:09 - INFO - EM Iter  57: ll=-1883.6472 log_delta_p=-8.6856 log_delta_a=-12.7024 min_alpha=0.0001 mean_alpha=0.0412 median_alpha=0.0329 max_alpha=0.3857 beta=0.0066

22:46:09 - INFO - EM Iter  58: ll=-1883.6470 log_delta_p=-8.7443 log_delta_a=-12.6439 min_alpha=0.0001 mean_alpha=0.0411 median_alpha=0.0328 max_alpha=0.3845 beta=0.0066

22:46:09 - INFO - EM Iter  59: ll=-1883.6467 log_delta_p=-8.8020 log_delta_a=-12.6965 min_alpha=0.0001 mean_alpha=0.0410 median_alpha=0.0328 max_alpha=0.3833 beta=0.0066

22:46:09 - INFO - EM Iter  60: ll=-1883.6466 log_delta_p=-8.8579 log_delta_a=-12.6504 min_alpha=0.0001 mean_alpha=0.0409 median_alpha=0.0328 max_alpha=0.3821 beta=0.0066

22:46:09 - INFO - EM Iter  61: ll=-1883.6464 log_delta_p=-8.9136 log_delta_a=-12.7301 min_alpha=0.0001 mean_alpha=0.0408 median_alpha=0.0327 max_alpha=0.3809 beta=0.0067

22:46:09 - INFO - EM Iter  62: ll=-1883.6464 log_delta_p=-8.9682 log_delta_a=-12.8336 min_alpha=0.0001 mean_alpha=0.0408 median_alpha=0.0327 max_alpha=0.3798 beta=0.0067

22:46:09 - INFO - EM Iter  63: ll=-1883.6461 log_delta_p=-9.0225 log_delta_a=-12.7052 min_alpha=0.0001 mean_alpha=0.0407 median_alpha=0.0326 max_alpha=0.3786 beta=0.0067

22:46:09 - INFO - EM Iter  64: ll=-1883.6461 log_delta_p=-9.0771 log_delta_a=-12.8500 min_alpha=0.0001 mean_alpha=0.0406 median_alpha=0.0326 max_alpha=0.3774 beta=0.0068

22:46:09 - INFO - EM Iter  65: ll=-1883.6459 log_delta_p=-9.1312 log_delta_a=-12.8848 min_alpha=0.0000 mean_alpha=0.0406 median_alpha=0.0325 max_alpha=0.3763 beta=0.0068

22:46:09 - INFO - EM Iter  66: ll=-1883.6458 log_delta_p=-9.1853 log_delta_a=-12.9293 min_alpha=0.0000 mean_alpha=0.0405 median_alpha=0.0325 max_alpha=0.3752 beta=0.0068

22:46:09 - INFO - EM Iter  67: ll=-1883.6454 log_delta_p=-9.2397 log_delta_a=-12.7974 min_alpha=0.0000 mean_alpha=0.0405 median_alpha=0.0325 max_alpha=0.3741 beta=0.0069

22:46:09 - INFO - Converged.

22:46:10 - WARNING - 99% of the 621 cells assigned to cell type 3 (input label 'Type_10') were reassigned there from other input labels: 'Type_7' (128), 'Type_0' (102), 'Type_1' (98), 'Type_2' (97), 'Type_5' (48), 'Type_11' (44), 'Type_9' (43), 'Type_6' (41), 'Type_3' (12), 'Type_8' (2), 'Type_4' (1). The input annotation may not match the structure of this dataset; consider a different or finer annotation, for example one that splits the cell types these cells came from.

22:46:10 - WARNING - 89% of the 1163 cells assigned to cell type 4 (input label 'Type_11') were reassigned there from other input labels: 'Type_7' (304), 'Type_1' (237), 'Type_0' (212), 'Type_5' (131), 'Type_6' (113), 'Type_3' (23), 'Type_10' (11), 'Type_4' (6), 'Type_8' (3). The input annotation may not match the structure of this dataset; consider a different or finer annotation, for example one that splits the cell types these cells came from.

22:46:10 - WARNING - 95% of the 468 cells assigned to cell type 6 (input label 'Type_3') were reassigned there from other input labels: 'Type_7' (163), 'Type_0' (117), 'Type_5' (89), 'Type_11' (57), 'Type_10' (7), 'Type_4' (6), 'Type_8' (5). The input annotation may not match the structure of this dataset; consider a different or finer annotation, for example one that splits the cell types these cells came from.

22:46:10 - WARNING - 99% of the 832 cells assigned to cell type 7 (input label 'Type_4') were reassigned there from other input labels: 'Type_7' (291), 'Type_2' (240), 'Type_6' (140), 'Type_11' (118), 'Type_3' (24), 'Type_8' (4), 'Type_10' (3). The input annotation may not match the structure of this dataset; consider a different or finer annotation, for example one that splits the cell types these cells came from.

22:46:10 - WARNING - 70% of the 1258 cells assigned to cell type 10 (input label 'Type_7') were reassigned there from other input labels: 'Type_2' (244), 'Type_1' (144), 'Type_0' (117), 'Type_5' (90), 'Type_11' (88), 'Type_9' (88), 'Type_6' (66), 'Type_3' (32), 'Type_8' (7), 'Type_10' (4), 'Type_4' (3). The input annotation may not match the structure of this dataset; consider a different or finer annotation, for example one that splits the cell types these cells came from.

22:46:10 - WARNING - 99% of the 1655 cells assigned to cell type 11 (input label 'Type_8') were reassigned there from other input labels: 'Type_7' (389), 'Type_1' (289), 'Type_2' (277), 'Type_5' (198), 'Type_6' (182), 'Type_11' (141), 'Type_9' (111), 'Type_3' (39), 'Type_10' (7), 'Type_4' (7). The input annotation may not match the structure of this dataset; consider a different or finer annotation, for example one that splits the cell types these cells came from.

22:46:10 - INFO - Saving inferred adata to '/home/mcaskey/cellsweep/notebooks/data/simulation1_small_noise/celltype_granularity/adata_cellsweep_shuffled.h5ad'

shuffled done

,condition,n_labels,noise_recall,removal_precision,real_retained,fraction_removed,true_fraction_noise,entry_rmse,cell_frac_spearman,cell_frac_mae,offtarget_marker_removed,ontarget_marker_retained,mean_cell_size_per_label
0,merge_1,1,0.7440,0.0491,0.4011,0.6047,0.0399,8.3223,0.1177,0.5678,0.8803,0.3972,10157.0000
1,merge_2,2,0.3962,0.1552,0.9105,0.1017,0.0399,2.7110,0.7665,0.0702,0.6469,0.9172,5078.5000
2,merge_3,3,0.3842,0.3784,0.9738,0.0405,0.0399,0.4033,0.8870,0.0078,0.7255,0.9847,3385.6667
3,merge_6,6,0.4347,0.4288,0.9760,0.0404,0.0399,0.3715,0.9113,0.0068,0.9060,0.9912,1692.8333
4,truth,12,0.4571,0.4555,0.9773,0.0400,0.0399,0.3586,0.9230,0.0062,0.9946,0.9945,846.4167
5,split_2,24,0.4532,0.4555,0.9775,0.0397,0.0399,0.3589,0.9195,0.0064,0.9870,0.9946,423.2083
6,split_4,48,0.4468,0.4553,0.9778,0.0391,0.0399,0.3595,0.9126,0.0066,0.9737,0.9946,211.6042
7,split_8,96,0.4325,0.4551,0.9785,0.0379,0.0399,0.3607,0.9016,0.0070,0.9425,0.9947,105.8021
8,leiden_1,12,0.4571,0.4555,0.9773,0.0400,0.0399,0.3586,0.9230,0.0062,0.9946,0.9945,846.4167
9,leiden_5,32,0.4531,0.4546,0.9774,0.0397,0.0399,0.3588,0.9243,0.0064,0.9869,0.9946,317.4062
10,leiden_20,269,0.3168,0.4600,0.9846,0.0275,0.0399,0.3747,0.7903,0.0147,0.6837,0.9964,37.7584
11,shuffled,12,0.4172,0.3954,0.9735,0.0421,0.0399,0.4174,0.8412,0.0102,0.8367,0.9867,846.4167

## 5. Metrics

Scored with a fixed reference annotation (CellTypist Immune_All_Low collapsed to major populations): lineage-marker
removal from expressing and non-expressing cells, subtype markers inside a coarse label, per-cell and per-gene removal
fractions, and kNN purity of the reference populations and of each run's own labels.

In [6]:
matplotlib.use("Agg")
gran_out_dir = os.path.join(cellsweep_dir, "notebooks", "output", "pbmc8k", "celltype_granularity")
os.makedirs(gran_out_dir, exist_ok=True)
DEFAULT = "ct_high"
REF_GROUP = {
    "Tcm/Naive helper T cells": "CD4 T", "Tem/Effector helper T cells": "CD4 T", "Regulatory T cells": "CD4 T", "Treg(diff)": "CD4 T",
    "Tcm/Naive cytotoxic T cells": "CD8 T", "Tem/Temra cytotoxic T cells": "CD8 T", "Tem/Trm cytotoxic T cells": "CD8 T",
    "MAIT cells": "MAIT",
    "CD16+ NK cells": "NK", "NK cells": "NK",
    "Naive B cells": "Naive B", "Memory B cells": "Memory B",
    "Classical monocytes": "CD14 Mono", "Non-classical monocytes": "CD16 Mono",
    "DC1": "cDC", "DC2": "cDC", "pDC": "pDC",
    "Megakaryocytes/platelets": "Platelet", "HSC/MPP": "HSC",
}
T = {"CD4 T", "CD8 T", "MAIT"}
B = {"Naive B", "Memory B"}
MONO = {"CD14 Mono", "CD16 Mono"}
MYELOID = MONO | {"cDC", "pDC"}
ALL = set(REF_GROUP.values())
LINEAGE_PANELS = {
    "Myeloid (LYZ, S100A8/9, CST3, FCN1)": (["LYZ", "S100A8", "S100A9", "CST3", "FCN1"], MYELOID, T | B | {"NK"}),
    "B (MS4A1, CD79A/B)": (["MS4A1", "CD79A", "CD79B"], B, T | MONO | {"NK"}),
    "T (CD3D/E, TRAC)": (["CD3D", "CD3E", "TRAC"], T, B | MYELOID),
    "NK (NKG7, GNLY, KLRF1)": (["NKG7", "GNLY", "KLRF1"], {"NK"}, B | MYELOID),
    "Platelet (PPBP, PF4)": (["PPBP", "PF4"], {"Platelet"}, ALL - {"Platelet"}),
    "Erythrocyte (HBB, HBA1/2)": (["HBB", "HBA1", "HBA2"], set(), ALL),
}
SUBTYPE_MARKERS = {
    "CD8A": ("CD8 T", "CD4 T"), "CD8B": ("CD8 T", "CD4 T"),
    "SLC4A10": ("MAIT", "CD4 T"), "KLRB1": ("MAIT", "CD4 T"),
    "FCGR3A": ("CD16 Mono", "CD14 Mono"), "CDKN1C": ("CD16 Mono", "CD14 Mono"), "MS4A7": ("CD16 Mono", "CD14 Mono"),
    "CD14": ("CD14 Mono", "CD16 Mono"), "VCAN": ("CD14 Mono", "CD16 Mono"), "S100A12": ("CD14 Mono", "CD16 Mono"),
    "TCL1A": ("Naive B", "Memory B"), "IGHD": ("Naive B", "Memory B"),
}
N_NEIGHBORS = 15
N_PCS = 25
def condition_order():
    k = labels.nunique()
    order = sorted([c for c in labels.columns if c != "shuffled"], key=lambda c: (k[c], c))
    return order + ["shuffled"]
def pretty(c):
    names = {"all_one": "Single label", "lineage": "Lymphoid/myeloid", "ct_high": "CellTypist High (default)", "ct_low": "CellTypist Low", "shuffled": "Shuffled High (control)"}
    if c in names:
        return f"{names[c]} (K={labels[c].nunique()})"
    return f"Leiden r={c.split('_')[1]} (K={labels[c].nunique()})"
def load(condition, genes):
    a = ad.read_h5ad(os.path.join(run_dir, f"adata_cellsweep_{condition}.h5ad"))
    a = a[~a.obs["is_empty"].values].copy()
    a.var_names_make_unique()
    a = a[labels.index]
    raw = sp.csr_matrix(a.layers["raw"], dtype=np.float64)
    den = sp.csr_matrix(a.X, dtype=np.float64)
    return a, raw, den
def knn_purity(emb, groups):
    nn = NearestNeighbors(n_neighbors=N_NEIGHBORS + 1).fit(emb)
    idx = nn.kneighbors(emb, return_distance=False)[:, 1:]
    g = np.asarray(groups)
    return float(np.mean(g[idx] == g[:, None]))
def embed(X, hvg_idx):
    ad_tmp = ad.AnnData(X=X[:, hvg_idx].copy())
    sc.pp.normalize_total(ad_tmp, target_sum=1e4)
    sc.pp.log1p(ad_tmp)
    sc.pp.scale(ad_tmp, max_value=10)
    sc.tl.pca(ad_tmp, n_comps=N_PCS, random_state=0)
    return ad_tmp.obsm["X_pca"]
def make_figure(summary, lineage, subtype, order):
    plt.rcParams.update({"font.size": 8, "axes.spines.top": False, "axes.spines.right": False})
    s = summary.set_index("condition").loc[order]
    main_conds = [c for c in order if c != "shuffled"]
    ms = s.loc[main_conds]
    x = ms["n_labels"].values
    named = {"all_one": "1 label", "lineage": "lineage", "ct_high": "CT High", "ct_low": "CT Low"}
    ct_color, leiden_color, coarse_color, shuf_color = "#DD8452", "#4C72B0", "#8C8C8C", "#C44E52"

    def ccolor(c):
        return leiden_color if c.startswith("leiden") else ct_color if c.startswith("ct_") else coarse_color

    def points(ax, series, label_points=True, shuffled_value=None):
        leiden = [c for c in main_conds if c.startswith("leiden")]
        ax.plot(s.loc[leiden, "n_labels"], series.loc[leiden], "-", color=leiden_color, lw=1, zorder=2)
        for c in main_conds:
            ax.scatter(s.loc[c, "n_labels"], series.loc[c], color=ccolor(c), s=20, zorder=3)
            if label_points and c in named:
                ax.annotate(named[c], (s.loc[c, "n_labels"], series.loc[c]), textcoords="offset points", xytext=(4, 3), fontsize=6)
        if shuffled_value is not None:
            ax.scatter(s.loc["shuffled", "n_labels"], shuffled_value, marker="x", color=shuf_color, s=28, zorder=4)
        ax.set_xscale("log")
        ax.set_xlabel("Number of labels K (log)")

    fig, axes = plt.subplots(2, 3, figsize=(11, 7))

    # a: pooled lineage-marker removal, off vs on target
    ax = axes[0, 0]
    points(ax, s["pooled_offtarget_marker_removed"], shuffled_value=s.loc["shuffled", "pooled_offtarget_marker_removed"])
    points(ax, s["pooled_ontarget_marker_removed"], label_points=False, shuffled_value=s.loc["shuffled", "pooled_ontarget_marker_removed"])
    ax.text(0.98, 0.62, "off-target counts\n(should be removed)", transform=ax.transAxes, ha="right", fontsize=6.5)
    ax.text(0.98, 0.12, "on-target counts\n(should be kept)", transform=ax.transAxes, ha="right", fontsize=6.5)
    ax.set_ylabel("Fraction of lineage-marker counts removed")
    ax.set_title("a  Lineage markers, pooled", loc="left", fontsize=8.5)

    # b / c: per panel on-target (over-correction) and off-target (under-correction)
    # line = merged-High labels then Leiden; squares = CellTypist High/Low; x = shuffled
    line_conds = ["all_one", "lineage"] + [c for c in main_conds if c.startswith("leiden")]
    panel_colors = dict(zip(LINEAGE_PANELS.keys(), plt.cm.tab10.colors))
    for ax, col, title, ylabel in [
        (axes[0, 1], "ontarget_removed", "b  Over-correction (on-target removed)", "Fraction removed from expressing cells"),
        (axes[0, 2], "offtarget_removed", "c  Under-correction (off-target removed)", "Fraction removed from non-expressing cells"),
    ]:
        for panel, sub in lineage.groupby("panel", sort=False):
            sub = sub.set_index("condition")
            if sub[col].isna().all():
                continue
            color = panel_colors[panel]
            ax.plot(s.loc[line_conds, "n_labels"], sub.loc[line_conds, col], "-o", ms=2.5, lw=1, color=color, label=panel)
            ax.scatter(s.loc[["ct_high", "ct_low"], "n_labels"], sub.loc[["ct_high", "ct_low"], col], marker="s", s=22, color=color, edgecolor="k", lw=0.5, zorder=4)
            ax.scatter(s.loc["shuffled", "n_labels"], sub.loc["shuffled", col], marker="x", color=color, s=22)
        ax.set_xscale("log")
        ax.set_xlabel("Number of labels K (log)")
        ax.set_ylabel(ylabel)
        ax.set_title(title, loc="left", fontsize=8.5)
    axes[0, 2].legend(fontsize=5.5, frameon=False, loc="lower left")
    axes[0, 1].text(0.97, 0.97, "line: merged High, then Leiden\nsquares: CellTypist High / Low\nx: shuffled High", transform=axes[0, 1].transAxes, ha="right", va="top", fontsize=6)

    # d: subtype-marker retention heatmap
    ax = axes[1, 0]
    piv = subtype.pivot(index="gene", columns="condition", values="retained_in_expressing")[order].loc[list(SUBTYPE_MARKERS.keys())]
    im = ax.imshow(piv.values, aspect="auto", cmap="viridis", vmin=0.8, vmax=1.0)
    for i in range(piv.shape[0]):
        for j in range(piv.shape[1]):
            v = piv.values[i, j]
            ax.text(j, i, f"{v:.2f}", ha="center", va="center", fontsize=4.5, color="w" if v < 0.9 else "k")
    ax.set_yticks(range(piv.shape[0]))
    ax.set_yticklabels([f"{g} in {SUBTYPE_MARKERS[g][0]}" for g in piv.index], fontsize=6)
    ax.set_xticks(range(len(order)))
    ax.set_xticklabels([f"{named.get(c, c.replace('leiden_', 'r=')) if c != 'shuffled' else 'shuffled'} ({labels[c].nunique()})" for c in order], rotation=90, fontsize=6)
    cb = fig.colorbar(im, ax=ax, fraction=0.04, pad=0.02)
    cb.set_label("Fraction retained (clipped at 0.8)", fontsize=6)
    ax.set_title("d  Subtype markers in the expressing subtype", loc="left", fontsize=8.5)

    # e: model parameters absorb contamination as K grows
    ax = axes[1, 1]
    points(ax, s["fraction_counts_removed"], shuffled_value=s.loc["shuffled", "fraction_counts_removed"])
    ax2 = ax.twinx()
    leiden = [c for c in main_conds if c.startswith("leiden")] 
    ax2.plot(ms["n_labels"], ms["beta_hat"], ":", color="k", lw=1)
    ax2.scatter(ms["n_labels"], ms["beta_hat"], marker="d", s=10, color="k")
    ax2.set_ylabel("beta_hat (dotted)", fontsize=7)
    ax2.spines["right"].set_visible(True)
    ax.set_ylabel("Fraction of all counts removed")
    ax.set_title("e  Total removal and beta_hat", loc="left", fontsize=8.5)

    # f: circularity control
    ax = axes[1, 2]
    points(ax, s["own_label_purity_gain"], shuffled_value=s.loc["shuffled", "own_label_purity_gain"])
    ax.axhline(0, color="k", ls=":", lw=1)
    ax.set_ylim(-0.05, 0.05)
    ax.set_ylabel(f"{N_NEIGHBORS}-NN purity of input labels,\ndenoised minus raw")
    ax.set_title("f  Label self-reinforcement", loc="left", fontsize=8.5)

    handles = [plt.Line2D([], [], marker="o", ls="", color=ct_color, label="CellTypist"), plt.Line2D([], [], marker="o", ls="-", color=leiden_color, label="Leiden"),
               plt.Line2D([], [], marker="o", ls="", color=coarse_color, label="Merged CellTypist High"), plt.Line2D([], [], marker="x", ls="", color=shuf_color, label="Shuffled High (control)")]
    fig.legend(handles=handles, loc="lower center", ncol=4, frameon=False, fontsize=7)
    fig.tight_layout(rect=(0, 0.03, 1, 1))
    for ext in ["png", "pdf"]:
        fig.savefig(os.path.join(gran_out_dir, f"celltype_granularity_sensitivity.{ext}"), dpi=300)
    plt.close(fig)

    if os.path.exists(sim_metrics_csv):
        sim = pd.read_csv(sim_metrics_csv)
        sim_main = sim[sim.condition != "shuffled"].sort_values("n_labels")
        shuf = sim[sim.condition == "shuffled"].iloc[0]
        styles = {"leiden": "o", "merge": "s", "split": "^", "truth": "*"}
        fig, axes = plt.subplots(1, 3, figsize=(10.5, 3.2))
        for ax, cols, ylab in [
            (axes[0], ["fraction_removed", "true_fraction_noise"], "Fraction of counts"),
            (axes[1], ["offtarget_marker_removed", "ontarget_marker_retained", "real_retained"], "Fraction"),
            (axes[2], ["cell_frac_spearman"], "Spearman, estimated vs true\nper-cell contamination"),
        ]:
            for col in cols:
                line, = ax.plot(sim_main["n_labels"], sim_main[col], "-", lw=1, label=col.replace("_", " "))
                for _, row in sim_main.iterrows():
                    ax.scatter(row["n_labels"], row[col], marker=styles[row["condition"].split("_")[0]], s=18, color=line.get_color(), zorder=3)
                ax.scatter(shuf["n_labels"], shuf[col], marker="x", color="#C44E52", s=30, zorder=4)
            ax.axvline(12, color="#2CA02C", lw=1, ls=":")
            ax.set_xscale("log")
            ax.set_xlabel("Number of labels (true K = 12)")
            ax.set_ylabel(ylab)
            ax.legend(fontsize=6, frameon=False)
        fig.suptitle("Simulation with ground truth: merged types (squares), truth (star), random splits (triangles), Leiden (circles), shuffled (red x)", fontsize=7.5)
        fig.tight_layout()
        for ext in ["png", "pdf"]:
            fig.savefig(os.path.join(gran_out_dir, f"celltype_granularity_simulation.{ext}"), dpi=300)
        plt.close(fig)

In [7]:
def main():
    ref = labels["ct_low"].map(REF_GROUP)
    assert ref.notna().all(), labels.loc[ref.isna(), "ct_low"].unique()
    ref = ref.values
    order = condition_order()

    summary, lineage_rows, subtype_rows = [], [], []
    per_cell_frac, per_gene_frac = {}, {}
    hvg_idx = None
    raw_embed = None

    for cond in order:
        print(f"scoring {cond}", flush=True)
        a, raw, den = load(cond, None)
        var_names = a.var_names
        removed = raw - den
        removed.data = np.clip(removed.data, 0, None)

        if hvg_idx is None:
            # fixed HVG set from the raw cells, shared by every run
            tmp = ad.AnnData(X=raw.copy(), var=pd.DataFrame(index=var_names))
            sc.pp.highly_variable_genes(tmp, n_top_genes=2000, flavor="seurat_v3")
            hvg_idx = np.where(tmp.var["highly_variable"].values)[0]
            raw_embed = embed(raw, hvg_idx)
            raw_ref_purity = knn_purity(raw_embed, ref)

        raw_cell = np.asarray(raw.sum(1)).ravel()
        per_cell_frac[cond] = np.asarray(removed.sum(1)).ravel() / raw_cell
        raw_gene = np.asarray(raw.sum(0)).ravel()
        keep_gene = raw_gene >= 100
        per_gene_frac[cond] = np.asarray(removed.sum(0)).ravel()[keep_gene] / raw_gene[keep_gene]

        rawc, denc = raw.tocsc(), den.tocsc()
        gidx = {g: i for i, g in enumerate(var_names)}

        # 1. lineage-marker specificity
        off_raw_all = off_rem_all = on_raw_all = on_rem_all = 0.0
        for panel, (genes, on, off) in LINEAGE_PANELS.items():
            cols = [gidx[g] for g in genes]
            r, d = rawc[:, cols], denc[:, cols]
            on_mask, off_mask = np.isin(ref, list(on)), np.isin(ref, list(off))
            off_raw, off_rem = r[off_mask].sum(), (r[off_mask] - d[off_mask]).sum()
            on_raw, on_rem = r[on_mask].sum(), (r[on_mask] - d[on_mask]).sum()
            lineage_rows.append(dict(condition=cond, panel=panel, offtarget_removed=off_rem / off_raw,
                                     ontarget_removed=(on_rem / on_raw) if on_raw > 0 else np.nan,
                                     offtarget_raw_counts=off_raw, ontarget_raw_counts=on_raw))
            if on_raw > 0:
                off_raw_all += off_raw; off_rem_all += off_rem; on_raw_all += on_raw; on_rem_all += on_rem

        # 2. subtype markers
        for g, (pos, neg) in SUBTYPE_MARKERS.items():
            c = gidx[g]
            r, d = np.asarray(rawc[:, c].todense()).ravel(), np.asarray(denc[:, c].todense()).ravel()
            pm, nm = ref == pos, ref == neg
            # pseudobulk CPM using each matrix's own library sizes
            den_cell = np.asarray(den.sum(1)).ravel()
            cpm = lambda x, lib, m: 1e6 * x[m].sum() / lib[m].sum()
            lfc_raw = np.log2((cpm(r, raw_cell, pm) + 1) / (cpm(r, raw_cell, nm) + 1))
            lfc_den = np.log2((cpm(d, den_cell, pm) + 1) / (cpm(d, den_cell, nm) + 1))
            subtype_rows.append(dict(condition=cond, gene=g, expressing=pos, sibling=neg,
                                     retained_in_expressing=d[pm].sum() / r[pm].sum(),
                                     removed_in_sibling=1 - d[nm].sum() / r[nm].sum(),
                                     log2fc_raw=lfc_raw, log2fc_denoised=lfc_den, log2fc_gain=lfc_den - lfc_raw))

        # 4. downstream structure
        emb = embed(den, hvg_idx)
        own = labels[cond].values
        summary.append(dict(
            condition=cond, label=pretty(cond), n_labels=labels[cond].nunique(),
            median_cells_per_label=float(labels[cond].value_counts().median()),
            min_cells_per_label=int(labels[cond].value_counts().min()),
            fraction_counts_removed=removed.sum() / raw.sum(),
            median_alpha_hat=float(np.median(a.obs["alpha_hat"])),
            n_cells_reassigned=int((np.asarray(a.uns["celltype_names"]).astype(str)[a.obs["z_hat"].values.astype(int) - 1] != own).sum()),  # z_hat is a 1-based index into celltype_names
            beta_hat=float(a.uns["beta_hat"]),
            loglike=float(a.uns["loglike"]),
            pooled_offtarget_marker_removed=off_rem_all / off_raw_all,
            pooled_ontarget_marker_removed=on_rem_all / on_raw_all,
            ref_knn_purity=knn_purity(emb, ref), ref_knn_purity_raw=raw_ref_purity,
            own_label_knn_purity=knn_purity(emb, own), own_label_knn_purity_raw=knn_purity(raw_embed, own),
        ))

    summary = pd.DataFrame(summary)
    for other in [DEFAULT, "ct_low"]:
        summary[f"cell_removed_frac_spearman_vs_{other}"] = [spearmanr(per_cell_frac[c], per_cell_frac[other]).correlation for c in summary.condition]
        summary[f"gene_removed_frac_spearman_vs_{other}"] = [spearmanr(per_gene_frac[c], per_gene_frac[other]).correlation for c in summary.condition]
    summary["marker_specificity"] = summary["pooled_offtarget_marker_removed"] - summary["pooled_ontarget_marker_removed"]
    summary["own_label_purity_gain"] = summary["own_label_knn_purity"] - summary["own_label_knn_purity_raw"]
    summary["ref_purity_gain"] = summary["ref_knn_purity"] - summary["ref_knn_purity_raw"]
    lineage = pd.DataFrame(lineage_rows)
    subtype = pd.DataFrame(subtype_rows)

    summary.to_csv(os.path.join(gran_out_dir, "summary_metrics.csv"), index=False)
    lineage.to_csv(os.path.join(gran_out_dir, "lineage_marker_metrics.csv"), index=False)
    subtype.to_csv(os.path.join(gran_out_dir, "subtype_marker_metrics.csv"), index=False)

    pd.set_option("display.width", 300)
    pd.set_option("display.max_columns", 50)
    print(summary.drop(columns=["label"]).round(3).to_string(index=False))
    print(lineage.pivot(index="panel", columns="condition", values="offtarget_removed")[order].round(3).to_string())
    print(lineage.pivot(index="panel", columns="condition", values="ontarget_removed")[order].round(3).to_string())
    print(subtype.pivot(index="gene", columns="condition", values="retained_in_expressing")[order].round(3).to_string())
    print(subtype.pivot(index="gene", columns="condition", values="log2fc_gain")[order].round(3).to_string())

    make_figure(summary, lineage, subtype, order)


main()

scoring all_one

/home/mcaskey/.conda/envs/cellsweep/lib/python3.10/functools.py:889: UserWarning: zero-centering a sparse array/matrix densifies it.
  return dispatch(args[0].__class__)(*args, **kw)

/home/mcaskey/.conda/envs/cellsweep/lib/python3.10/functools.py:889: UserWarning: zero-centering a sparse array/matrix densifies it.
  return dispatch(args[0].__class__)(*args, **kw)

scoring leiden_0.001

/home/mcaskey/.conda/envs/cellsweep/lib/python3.10/functools.py:889: UserWarning: zero-centering a sparse array/matrix densifies it.
  return dispatch(args[0].__class__)(*args, **kw)

scoring lineage

/home/mcaskey/.conda/envs/cellsweep/lib/python3.10/functools.py:889: UserWarning: zero-centering a sparse array/matrix densifies it.
  return dispatch(args[0].__class__)(*args, **kw)

scoring leiden_0.005

/home/mcaskey/.conda/envs/cellsweep/lib/python3.10/functools.py:889: UserWarning: zero-centering a sparse array/matrix densifies it.
  return dispatch(args[0].__class__)(*args, **kw)

scoring leiden_0.01

/home/mcaskey/.conda/envs/cellsweep/lib/python3.10/functools.py:889: UserWarning: zero-centering a sparse array/matrix densifies it.
  return dispatch(args[0].__class__)(*args, **kw)

scoring leiden_0.1

/home/mcaskey/.conda/envs/cellsweep/lib/python3.10/functools.py:889: UserWarning: zero-centering a sparse array/matrix densifies it.
  return dispatch(args[0].__class__)(*args, **kw)

scoring ct_high

/home/mcaskey/.conda/envs/cellsweep/lib/python3.10/functools.py:889: UserWarning: zero-centering a sparse array/matrix densifies it.
  return dispatch(args[0].__class__)(*args, **kw)

scoring leiden_0.5

/home/mcaskey/.conda/envs/cellsweep/lib/python3.10/functools.py:889: UserWarning: zero-centering a sparse array/matrix densifies it.
  return dispatch(args[0].__class__)(*args, **kw)

scoring ct_low

/home/mcaskey/.conda/envs/cellsweep/lib/python3.10/functools.py:889: UserWarning: zero-centering a sparse array/matrix densifies it.
  return dispatch(args[0].__class__)(*args, **kw)

scoring leiden_1

/home/mcaskey/.conda/envs/cellsweep/lib/python3.10/functools.py:889: UserWarning: zero-centering a sparse array/matrix densifies it.
  return dispatch(args[0].__class__)(*args, **kw)

scoring leiden_1.5

/home/mcaskey/.conda/envs/cellsweep/lib/python3.10/functools.py:889: UserWarning: zero-centering a sparse array/matrix densifies it.
  return dispatch(args[0].__class__)(*args, **kw)

scoring leiden_2

/home/mcaskey/.conda/envs/cellsweep/lib/python3.10/functools.py:889: UserWarning: zero-centering a sparse array/matrix densifies it.
  return dispatch(args[0].__class__)(*args, **kw)

scoring leiden_5

/home/mcaskey/.conda/envs/cellsweep/lib/python3.10/functools.py:889: UserWarning: zero-centering a sparse array/matrix densifies it.
  return dispatch(args[0].__class__)(*args, **kw)

scoring leiden_10

/home/mcaskey/.conda/envs/cellsweep/lib/python3.10/functools.py:889: UserWarning: zero-centering a sparse array/matrix densifies it.
  return dispatch(args[0].__class__)(*args, **kw)

scoring leiden_20

/home/mcaskey/.conda/envs/cellsweep/lib/python3.10/functools.py:889: UserWarning: zero-centering a sparse array/matrix densifies it.
  return dispatch(args[0].__class__)(*args, **kw)

scoring shuffled

/home/mcaskey/.conda/envs/cellsweep/lib/python3.10/functools.py:889: UserWarning: zero-centering a sparse array/matrix densifies it.
  return dispatch(args[0].__class__)(*args, **kw)

   condition  n_labels  median_cells_per_label  min_cells_per_label  fraction_counts_removed  median_alpha_hat  n_cells_reassigned  beta_hat  loglike  pooled_offtarget_marker_removed  pooled_ontarget_marker_removed  ref_knn_purity  ref_knn_purity_raw  own_label_knn_purity  own_label_knn_purity_raw  cell_removed_frac_spearman_vs_ct_high  gene_removed_frac_spearman_vs_ct_high  cell_removed_frac_spearman_vs_ct_low  gene_removed_frac_spearman_vs_ct_low  marker_specificity  own_label_purity_gain  ref_purity_gain
     all_one         1                  8381.0                 8381                    0.474             0.234                   0     0.040 -418.846                            0.897                           0.894           0.934               0.943                 1.000                     1.000                                  0.430                                  0.207                                 0.327                                 0.199               0.003                  0.000           -0.009
leiden_0.001         2                  4190.5                 2359                    0.211             0.101                  43     0.013 -416.907                            0.896                           0.105           0.939               0.943                 0.999                     0.998                                  0.667                                  0.816                                 0.326                                 0.734               0.791                  0.000           -0.004
     lineage         2                  4190.5                 2366                    0.211             0.101                  68     0.013 -416.907                            0.896                           0.105           0.939               0.943                 0.999                     0.999                                  0.667                                  0.815                                 0.326                                 0.733               0.791                 -0.000           -0.004
leiden_0.005         3                  2359.0                 1251                    0.176             0.072                  72     0.011 -416.090                            0.974                           0.089           0.938               0.943                 0.999                     0.997                                  0.830                                  0.894                                 0.492                                 0.814               0.885                  0.001           -0.006
 leiden_0.01         3                  2359.0                 1235                    0.176             0.072                  72     0.011 -416.089                            0.974                           0.090           0.938               0.943                 0.999                     0.998                                  0.830                                  0.892                                 0.491                                 0.813               0.884                  0.001           -0.005
  leiden_0.1         6                  1215.0                    9                    0.142             0.065                  23     0.011 -415.369                            0.966                           0.059           0.940               0.943                 0.995                     0.985                                  0.788                                  0.935                                 0.727                                 0.954               0.907                  0.009           -0.003
     ct_high         7                   356.0                   19                    0.149             0.070                  46     0.011 -415.205                            0.965                           0.060           0.944               0.943                 0.996                     0.990                                  1.000                                  1.000                                 0.629                                 0.944               0.905                  0.005            0.001
  leiden_0.5        14                   333.0                   10                    0.110             0.060                   2     0.010 -414.455                            0.910                           0.056           0.944               0.943                 0.940                     0.920                                  0.633                                  0.905                                 0.858                                 0.950               0.855                  0.021            0.000
      ct_low        18                   255.0                   14                    0.124             0.058                  20     0.010 -414.358                            0.930                           0.055           0.958               0.943                 0.920                     0.894                                  0.629                                  0.944                                 1.000                                 1.000               0.875                  0.025            0.015
    leiden_1        19                   409.0                   30                    0.101             0.057                   2     0.010 -414.228                            0.893                           0.052           0.944               0.943                 0.834                     0.805                                  0.575                                  0.902                                 0.790                                 0.946               0.841                  0.029            0.001
  leiden_1.5        23                   281.0                   30                    0.098             0.057                   2     0.009 -414.042                            0.874                           0.051           0.944               0.943                 0.820                     0.792                                  0.569                                  0.895                                 0.754                                 0.941               0.823                  0.028            0.001
    leiden_2        25                   282.0                   10                    0.100             0.056                   3     0.009 -413.996                            0.877                           0.051           0.945               0.943                 0.756                     0.729                                  0.590                                  0.898                                 0.762                                 0.944               0.826                  0.027            0.002
    leiden_5        48                   185.0                   15                    0.062             0.030                   5     0.008 -413.564                            0.587                           0.028           0.945               0.943                 0.576                     0.548                                  0.388                                  0.886                                 0.614                                 0.926               0.559                  0.027            0.002
   leiden_10        95                    83.0                   16                    0.046             0.011                  10     0.006 -413.036                            0.391                           0.021           0.944               0.943                 0.440                     0.423                                  0.510                                  0.851                                 0.527                                 0.890               0.370                  0.017            0.001
   leiden_20       202                    35.5                    3                    0.026             0.000                  10     0.004 -412.010                            0.198                           0.013           0.944               0.943                 0.308                     0.299                                  0.562                                  0.768                                 0.504                                 0.807               0.185                  0.009            0.001
    shuffled         7                   356.0                   19                    0.311             0.216                2594     0.019 -416.694                            0.886                           0.205           0.936               0.943                 0.376                     0.366                                  0.630                                  0.814                                 0.445                                 0.805               0.681                  0.010           -0.007
condition                            all_one  leiden_0.001  lineage  leiden_0.005  leiden_0.01  leiden_0.1  ct_high  leiden_0.5  ct_low  leiden_1  leiden_1.5  leiden_2  leiden_5  leiden_10  leiden_20  shuffled
panel
B (MS4A1, CD79A/B)                     0.538         0.487    0.487         0.775        0.777       0.740    0.770       0.662   0.666     0.642       0.629     0.629     0.362      0.260      0.139     0.524
Erythrocyte (HBB, HBA1/2)              0.962         0.893    0.893         0.895        0.895       0.373    0.784       0.291   0.146     0.190       0.200     0.241     0.043      0.038      0.011     0.926
Myeloid (LYZ, S100A8/9, CST3, FCN1)    1.000         0.999    0.999         0.999        0.999       0.998    0.997       0.995   0.970     0.987       0.962     0.963     0.673      0.420      0.204     0.991
NK (NKG7, GNLY, KLRF1)                 0.884         0.884    0.884         1.000        1.000       0.988    0.974       0.831   0.938     0.784       0.781     0.778     0.486      0.350      0.180     0.853
Platelet (PPBP, PF4)                   1.000         1.000    1.000         1.000        1.000       0.976    0.972       0.976   0.959     0.909       0.910     0.886     0.686      0.610      0.297     0.998
T (CD3D/E, TRAC)                       0.656         0.694    0.694         0.967        0.965       0.950    0.944       0.746   0.915     0.716       0.710     0.733     0.414      0.344      0.210     0.658
condition                            all_one  leiden_0.001  lineage  leiden_0.005  leiden_0.01  leiden_0.1  ct_high  leiden_0.5  ct_low  leiden_1  leiden_1.5  leiden_2  leiden_5  leiden_10  leiden_20  shuffled
panel
B (MS4A1, CD79A/B)                     0.265         0.261    0.261         0.018        0.018       0.018    0.018       0.016   0.017     0.013       0.013     0.013     0.010      0.008      0.004     0.269
Erythrocyte (HBB, HBA1/2)                NaN           NaN      NaN           NaN          NaN         NaN      NaN         NaN     NaN       NaN         NaN       NaN       NaN        NaN        NaN       NaN
Myeloid (LYZ, S100A8/9, CST3, FCN1)    1.000         0.060    0.060         0.062        0.062       0.060    0.058       0.058   0.058     0.055       0.054     0.054     0.029      0.022      0.013     0.204
NK (NKG7, GNLY, KLRF1)                 0.910         0.904    0.904         0.737        0.742       0.011    0.023       0.019   0.013     0.016       0.015     0.017     0.007      0.007      0.004     0.304
Platelet (PPBP, PF4)                   1.000         1.000    1.000         1.000        1.000       0.400    0.790       0.410   0.069     0.250       0.263     0.376     0.116      0.115      0.084     1.000
T (CD3D/E, TRAC)                       0.129         0.125    0.125         0.090        0.090       0.077    0.096       0.049   0.060     0.048       0.045     0.044     0.032      0.021      0.009     0.119
condition  all_one  leiden_0.001  lineage  leiden_0.005  leiden_0.01  leiden_0.1  ct_high  leiden_0.5  ct_low  leiden_1  leiden_1.5  leiden_2  leiden_5  leiden_10  leiden_20  shuffled
gene
CD14         0.000         0.946    0.946         0.945        0.945       0.945    0.946       0.941   0.949     0.944       0.946     0.945     0.976      0.986      0.991     0.800
CD8A         0.853         0.857    0.857         0.900        0.899       0.947    0.890       0.969   0.980     0.971       0.971     0.972     0.983      0.990      0.994     0.865
CD8B         0.906         0.909    0.910         0.933        0.932       0.949    0.927       0.970   0.982     0.972       0.972     0.972     0.983      0.991      0.994     0.912
CDKN1C       0.000         0.907    0.907         0.905        0.905       0.905    0.908       0.977   0.993     0.988       0.990     0.993     0.990      0.995      0.998     0.774
FCGR3A       0.000         0.861    0.861         0.858        0.858       0.858    0.860       0.982   0.992     0.988       0.989     0.990     0.991      0.994      0.997     0.657
IGHD         0.798         0.805    0.805         0.987        0.987       0.988    0.988       0.989   0.991     0.992       0.992     0.992     0.994      0.996      0.998     0.798
KLRB1        0.763         0.770    0.770         0.863        0.861       0.965    0.825       0.982   0.994     0.992       0.993     0.993     0.997      0.997      0.999     0.760
MS4A7        0.000         0.913    0.913         0.911        0.911       0.911    0.911       0.988   0.990     0.990       0.990     0.990     0.991      0.993      0.997     0.786
S100A12      0.000         0.959    0.959         0.958        0.958       0.958    0.961       0.961   0.965     0.962       0.962     0.962     0.985      0.990      0.993     0.836
SLC4A10      0.831         0.839    0.839         0.897        0.896       0.973    0.885       0.990   0.998     0.996       0.996     0.996     0.998      0.998      1.000     0.820
TCL1A        0.714         0.719    0.719         0.984        0.984       0.983    0.983       0.985   0.989     0.990       0.989     0.989     0.992      0.994      0.997     0.711
VCAN         0.000         0.954    0.954         0.953        0.953       0.953    0.954       0.953   0.958     0.954       0.955     0.954     0.981      0.988      0.992     0.825
condition  all_one  leiden_0.001  lineage  leiden_0.005  leiden_0.01  leiden_0.1  ct_high  leiden_0.5  ct_low  leiden_1  leiden_1.5  leiden_2  leiden_5  leiden_10  leiden_20  shuffled
gene
CD14        -3.587        -0.102   -0.102        -0.103       -0.103      -0.104   -0.113       0.585   0.767     0.543       0.604     0.607     0.468      0.120      0.054    -0.151
CD8A         0.043         0.042    0.042         0.028        0.028       0.099    0.046       0.316   1.400     0.278       0.276     0.287     0.274      0.127      0.048     0.063
CD8B         0.102         0.101    0.101         0.069        0.070       0.041    0.087       0.344   0.966     0.288       0.296     0.289     0.234      0.128      0.063     0.104
CDKN1C      -6.169         0.141    0.141         0.144        0.144       0.145    0.171       0.782   1.008     0.679       0.697     0.737     0.329      0.249      0.121     0.445
FCGR3A      -5.910         0.092    0.091         0.093        0.093       0.093    0.114       1.201   1.723     0.974       0.974     0.965     0.550      0.321      0.151     0.172
IGHD         0.017         0.018    0.018         0.048        0.048       0.046    0.046      -0.010   0.083     0.004       0.017     0.017    -0.003     -0.014     -0.021     0.029
KLRB1        0.119         0.120    0.120         0.103        0.103       0.227    0.115       0.035   0.069     0.049       0.049     0.056     0.016      0.009      0.011     0.117
MS4A7       -2.507         0.069    0.069         0.071        0.071       0.072    0.088       0.048   0.004     0.050       0.056     0.054     0.110      0.088      0.029     0.140
S100A12     -4.796        -0.085   -0.085        -0.087       -0.087      -0.087   -0.100       1.660   2.257     0.885       1.063     1.061     1.558      0.505      0.390    -0.140
SLC4A10      0.188         0.186    0.185         0.138        0.139       0.452    0.192       0.157   0.131     0.180       0.165     0.189     0.058      0.020      0.010     0.185
TCL1A        0.015         0.016    0.016         0.055        0.054       0.052    0.052      -0.006   0.534     0.237       0.221     0.218     0.206      0.200      0.156     0.085
VCAN        -3.993        -0.097   -0.097        -0.099       -0.099      -0.099   -0.113       1.011   1.223     0.793       0.868     0.875     0.883      0.281      0.219    -0.147

## 6. Signal and noise retained (Fig. S19)

Lineage-marker counts kept in expressing cells (signal) and in cells of other lineages, where they are ambient (noise),
against the number of labels (A) and of non-cellular barcodes (B).

In [8]:
matplotlib.rcdefaults()   # section 5 changes the font size and spines globally

matplotlib.use("Agg")
EMPTY_TAGS = ["10", "100", "1000", "10000", "50000", "100000", "500000", "all"]
N_EMPTY_ALL = 728899
EXAMPLES = {
    "CD16 monocyte program (FCGR3A, CDKN1C, MS4A7)": (["FCGR3A", "CDKN1C", "MS4A7"], {"CD16 Mono"}, T | B, "#4C72B0"),
    "NK program (NKG7, GNLY, KLRF1)": (["NKG7", "GNLY", "KLRF1"], {"NK"}, B | MYELOID, "#C44E52"),
}
def series(path, ref):
    """Fraction of marker counts retained, in expressing cells (signal) and in other cells (noise)."""
    a = ad.read_h5ad(path)
    a = a[~a.obs["is_empty"].values].copy()
    a.var_names_make_unique()
    a = a[labels.index]
    raw = sp.csr_matrix(a.layers["raw"], dtype=np.float64).tocsc()
    den = sp.csr_matrix(a.X, dtype=np.float64).tocsc()
    gidx = {g: i for i, g in enumerate(a.var_names)}

    out = {}
    sig_raw = sig_den = noi_raw = noi_den = 0.0
    for panel, (genes, on, off) in LINEAGE_PANELS.items():
        cols = [gidx[g] for g in genes]
        r, d = raw[:, cols], den[:, cols]
        on_mask, off_mask = np.isin(ref, list(on)), np.isin(ref, list(off))
        noi_raw += r[off_mask].sum(); noi_den += d[off_mask].sum()
        if on_mask.sum():
            sig_raw += r[on_mask].sum(); sig_den += d[on_mask].sum()
    out["signal_retained"] = sig_den / sig_raw
    out["noise_retained"] = noi_den / noi_raw

    for name, (genes, on, off, _color) in EXAMPLES.items():
        cols = [gidx[g] for g in genes]
        r, d = raw[:, cols], den[:, cols]
        on_mask, off_mask = np.isin(ref, list(on)), np.isin(ref, list(off))
        out[f"{name}|signal_retained"] = d[on_mask].sum() / r[on_mask].sum()
        out[f"{name}|noise_retained"] = d[off_mask].sum() / r[off_mask].sum()
    return out
def collect():
    ref = labels["ct_low"].map(REF_GROUP).values
    rows = []
    for cond in labels.columns:
        print(f"scoring labels: {cond}", flush=True)
        row = dict(sweep="labels", condition=cond, x=labels[cond].nunique())
        row.update(series(os.path.join(run_dir, f"adata_cellsweep_{cond}.h5ad"), ref))
        rows.append(row)
    for tag in EMPTY_TAGS:
        print(f"scoring empty barcodes: {tag}", flush=True)
        row = dict(sweep="empty", condition=tag, x=N_EMPTY_ALL if tag == "all" else int(tag))
        row.update(series(os.path.join(empty_run_dir, f"adata_cellsweep_empty_{tag}.h5ad"), ref))
        rows.append(row)
    df = pd.DataFrame(rows)
    df.to_csv(os.path.join(gran_out_dir, "signal_vs_noise_retained.csv"), index=False)
    return df
def draw(ax, df, color="k", label_prefix="", sig_col="signal_retained", noi_col="noise_retained"):
    df = df.sort_values("x")
    ax.plot(df["x"], df[sig_col], "-", color=color, lw=1.2, marker="o", ms=5, mfc=color, mec=color, label=f"{label_prefix}signal retained")
    ax.plot(df["x"], df[noi_col], "--", color=color, lw=1.2, marker="o", ms=5, mfc="none", mec=color, label=f"{label_prefix}noise retained")
def finish(ax, xlabel):
    ax.set_xscale("log")
    ax.set_ylim(-0.03, 1.03)
    ax.set_yticks(np.arange(0, 1.01, 0.1))
    ax.set_xlabel(xlabel)
    ax.set_ylabel("Fraction of counts retained")
    ax.axhline(1, color="0.85", lw=0.8, zorder=0)
    ax.axhline(0, color="0.85", lw=0.8, zorder=0)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
def save_fig(fig, name, tight_bbox=False):
    for ext in ["png", "pdf"]:
        fig.savefig(os.path.join(gran_out_dir, f"{name}.{ext}"), dpi=300, bbox_inches="tight" if tight_bbox else None)
    plt.close(fig)
def save_legend(handles, labels, name):
    """Legend as its own file, one entry per line."""
    fig = plt.figure(figsize=(3.4, 0.32 * len(labels) + 0.2))
    fig.legend(handles, labels, loc="center", frameon=False, fontsize=8, ncol=1)
    save_fig(fig, name, tight_bbox=True)
def figure_labels(df):
    d = df[df.sweep == "labels"].set_index("condition")
    # Leiden sweep; a single label for every cell (all_one) is its K = 1 limit
    leiden = d.loc[["all_one"] + [c for c in d.index if c.startswith("leiden")]]
    fig, ax = plt.subplots(figsize=(5.4, 4.2))
    draw(ax, leiden)

    # CellTypist annotations, plotted as squares (High) and diamonds (Low)
    red = "#d62728"
    ct_handles = []
    for cond, marker, name in [("ct_high", "s", "CellTypist High"), ("ct_low", "D", "CellTypist Low")]:
        row = d.loc[cond]
        filled = ax.scatter(row["x"], row["signal_retained"], marker=marker, s=55, color=red, zorder=5)
        hollow = ax.scatter(row["x"], row["noise_retained"], marker=marker, s=55, facecolor="none", edgecolor=red, lw=1.2, zorder=5)
        ax.annotate(name, (row["x"], row["noise_retained"]), textcoords="offset points", xytext=(0, -13), ha="center", fontsize=6.5, color=red)
        ct_handles.append(((filled, hollow), name))

    finish(ax, "Number of celltypes (Leiden)")
    handles, labels_ = ax.get_legend_handles_labels()
    handles += [h for h, _ in ct_handles]
    labels_ += [n for _, n in ct_handles]
    ax.legend(handles, labels_, handler_map={tuple: HandlerTuple(ndivide=None, pad=0.3)}, loc="lower right",
              frameon=False, fontsize=8)
    fig.tight_layout()
    save_fig(fig, "celltype_granularity_signal_vs_noise")
def figure_empty(df):
    d = df[df.sweep == "empty"]
    fig, ax = plt.subplots(figsize=(5.4, 4.2))
    draw(ax, d)
    ax.axvline(N_EMPTY_ALL, color="0.6", ls=":", lw=1)
    ax.annotate(f"all {N_EMPTY_ALL:,}", (N_EMPTY_ALL, 0.5), rotation=90, va="center", ha="right", fontsize=6.5, color="0.35")
    finish(ax, "Number of empty barcodes")
    ax.legend(loc="center right", bbox_to_anchor=(0.97, 0.25), frameon=False, fontsize=8)
    fig.tight_layout()
    save_fig(fig, "empty_barcode_signal_vs_noise")

df = collect()
figure_labels(df)
figure_empty(df)
df.round(3)

scoring labels: ct_high

scoring labels: all_one

scoring labels: lineage

scoring labels: shuffled

scoring labels: ct_low

scoring labels: leiden_0.001

scoring labels: leiden_0.005

scoring labels: leiden_0.01

scoring labels: leiden_0.1

scoring labels: leiden_0.5

scoring labels: leiden_1

scoring labels: leiden_1.5

scoring labels: leiden_2

scoring labels: leiden_5

scoring labels: leiden_10

scoring labels: leiden_20

scoring empty barcodes: 10

scoring empty barcodes: 100

scoring empty barcodes: 1000

scoring empty barcodes: 10000

scoring empty barcodes: 50000

scoring empty barcodes: 100000

scoring empty barcodes: 500000

scoring empty barcodes: all

     sweep     condition       x  signal_retained  noise_retained  CD16 monocyte program (FCGR3A, CDKN1C, MS4A7)|signal_retained  CD16 monocyte program (FCGR3A, CDKN1C, MS4A7)|noise_retained  NK program (NKG7, GNLY, KLRF1)|signal_retained  NK program (NKG7, GNLY, KLRF1)|noise_retained
0   labels       ct_high       7            0.940           0.035                                              0.881                                                          0.127                                                      0.977                                          0.026
1   labels       all_one       1            0.106           0.103                                              0.000                                                          0.000                                                      0.090                                          0.116
2   labels       lineage       2            0.895           0.104                                              0.883                                                          0.001                                                      0.096                                          0.116
3   labels      shuffled       7            0.795           0.114                                              0.711                                                          0.064                                                      0.696                                          0.147
4   labels        ct_low      18            0.945           0.071                                              0.991                                                          0.508                                                      0.987                                          0.062
5   labels  leiden_0.001       2            0.895           0.104                                              0.883                                                          0.001                                                      0.096                                          0.116
6   labels  leiden_0.005       3            0.911           0.026                                              0.880                                                          0.130                                                      0.263                                          0.000
7   labels   leiden_0.01       3            0.910           0.026                                              0.880                                                          0.120                                                      0.258                                          0.000
8   labels    leiden_0.1       6            0.941           0.035                                              0.880                                                          0.513                                                      0.989                                          0.012
9   labels    leiden_0.5      14            0.944           0.090                                              0.984                                                          0.519                                                      0.981                                          0.169
10  labels      leiden_1      19            0.948           0.108                                              0.989                                                          0.543                                                      0.984                                          0.216
11  labels    leiden_1.5      23            0.949           0.126                                              0.989                                                          0.555                                                      0.985                                          0.219
12  labels      leiden_2      25            0.949           0.124                                              0.991                                                          0.553                                                      0.983                                          0.222
13  labels      leiden_5      48            0.972           0.414                                              0.991                                                          0.673                                                      0.993                                          0.514
14  labels     leiden_10      95            0.979           0.610                                              0.993                                                          0.799                                                      0.993                                          0.650
15  labels     leiden_20     202            0.987           0.803                                              0.997                                                          0.913                                                      0.996                                          0.820
16   empty            10      10            0.959           0.476                                              0.837                                                          0.258                                                      0.698                                          0.024
17   empty           100     100            0.955           0.473                                              0.995                                                          0.905                                                      0.998                                          0.884
18   empty          1000    1000            0.983           0.310                                              0.994                                                          0.897                                                      0.984                                          0.349
19   empty         10000   10000            0.956           0.060                                              0.947                                                          0.303                                                      0.971                                          0.143
20   empty         50000   50000            0.945           0.035                                              0.900                                                          0.126                                                      0.962                                          0.028
21   empty        100000  100000            0.943           0.035                                              0.884                                                          0.121                                                      0.978                                          0.030
22   empty        500000  500000            0.939           0.034                                              0.882                                                          0.124                                                      0.977                                          0.025
23   empty           all  728899            0.940           0.035                                              0.881                                                          0.127                                                      0.977                                          0.026